### ISSUE TITLE
data_dirs environment wrongly expanded

### ISSUE THREAD

**Issue by smalenfant** [elastic/ansible-elasticsearch#104]
Somehow this showed up after running the playbook in the `/etc/system/multi-user.target.wants/node1_elasticsearch.service` file 

`Environment=DATA_DIR=[,',/,v,a,r,/,l,i,b,/,e,l,a,s,t,i,c,s,e,a,r,c,h,/,e,s,-,0,1,-,n,o,d,e,1,',]`

Also shows in `/etc/elasticsearch/node1/elasticsearch.yml `
`path.data: [,',/,v,a,r,/,l,i,b,/,e,l,a,s,t,i,c,s,e,a,r,c,h,/,e,s,-,0,1,-,n,o,d,e,1,',]`

Expect : 

Template

```
[Service]
Environment=ES_HOME={{es_home}}
Environment=CONF_DIR={{conf_dir}}
Environment=DATA_DIR={{ data_dirs | array_to_str }}
Environment=LOG_DIR={{log_dir}}
Environment=PID_DIR={{pid_dir}}
EnvironmentFile=-{{instance_default_file}}
```

**Comment by gingerwizard** [comment]
What version of Ansible are you using? This was a known issue with Ansible < 2.0 where variables would not retain their type when passed to Jinja

**Comment by jakommo** [comment]
No feedback on the ansible version used. 
Closing for now.
