### ISSUE TITLE
Plugins Installation fails on the 2nd run

### ISSUE THREAD

**Issue by sirkjohannsen** [elastic/ansible-elasticsearch#116]
Plugin Installation works fine on the first execution but fails on every extra run due to plugins already installed.
This PR should fix it: 
https://github.com/elastic/ansible-elasticsearch/pull/115

**Comment by yaron-idan** [comment]
I've also noticed this issue, is there any expected time for it to be solved?

**Comment by gingerwizard** [comment]
Tracking through https://github.com/elastic/ansible-elasticsearch/issues/125
