### ISSUE TITLE
Ensure Java is installed fails when running without root

### ISSUE THREAD

**Issue by yaron-idan** [elastic/ansible-elasticsearch#117]
Failure message - 
'
```
TASK [elasticsearch : Debian - Ensure Java is installed] ***********************
fatal: [ES1]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to lock apt for exclusive operation"}
```

Playbook ran on an EC2 ubuntu 14.04 instance (ami-fce3c696).
When instructing the role to become root the playbook fails as well (although much later, when trying to start elasticsearch) with this message - 
```
TASK [elasticsearch : Start elasticsearch service] *****************************
fatal: [ES1]: FAILED! => {"changed": false, "failed": true, "msg": " * Starting Elasticsearch Server - node1\n   ...fail!\n"}
```

Anyway I felt weird about letting the playbook becoming sudo when it's not explicitly mentioned in the examples.
Any help?

**Comment by yaron-idan** [comment]
Turns out my configuration was faulty, managed to overcome it.

**Comment by bobbrez** [comment]
@yaron-idan I believe that I'm running into the same issue. What was the fault / how'd you overcome it?

**Comment by yaron-idan** [comment]
My problem was trying to run the playbook without root privileges. Once I thought it through it became clear the playbook should become sudo since it's meant to install packages, an action that requires root privileges.

**Comment by tomekit** [comment]
Having same issues, how did you solve it @yaron-idan?
The user that's used to apply playbook has sudo permissions, I've also specified a password for sudo using: `--ask-become`, getting fatal:
`TASK [elasticsearch : Debian - Ensure Java is installed] ***********************
fatal: [52.8.47.43]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to lock apt for exclusive operation"}`

**Comment by tomekit** [comment]
For me adding `become: yes` on the same level as defining `hosts` and `roles` forced it to run as a privileged user.

**Comment by ashokc** [comment]
Yes, on ubuntu/xenial. I needed to add "become: true" to the playbook to overcome this issue... Was getting

TASK [elastic.elasticsearch : Refresh java repo] *******************************************************************************************************
fatal: [192.168.33.20]: FAILED! => {"changed": false, "cmd": "apt-get update", "failed": true, "msg": "W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)\nE
