### ISSUE TITLE
EC2 discovery plugin does not work

### ISSUE THREAD

**Issue by yaron-idan** [elastic/ansible-elasticsearch#118]
This is the playbook I'm running - 
```
---
- name: Simple Example
  hosts: ES_master
  become: true
  become_user: root
  roles:
      #expand to all available parameters
      - { role: elasticsearch, es_instance_name: "{{ ansible_hostname }}", es_data_dirs: "/opt/elasticsearch/data", es_log_dir: "/opt/elasticsearch/logs", es_work_dir: "/opt/elasticsearch/temp",
      es_config: {
          node.name: "{{ ansible_hostname }}",
          cluster.name: "custom-cluster",
          node.data: true,
          node.master: true,
          bootstrap.mlockall: true,
          discovery.zen.ping.multicast.enabled: false,
          network.publish_host: "{{ ansible_eth0.ipv4.address }}",
          network.host: "{{ ansible_eth0.ipv4.address }}",
          discovery.type: "ec2",
          transport.tcp.port: 9300,
          http.port: 9200,
          discovery.ec2.tag.ES-suggester: True,
          network.bind_host: "{{ ansible_eth0.ipv4.address }}"
          }
      }
  vars:
      es_major_version: "2.x"
      es_version: "2.3.4"
      es_heap_size: "100m"
      es_plugins:
          - plugin: cloud-aws
```

The instances launch alright but each one is nominating itself as master and doesn't recognize any of the other instances. The cluster is comprised of 3 EC2 instances. All of them carry the ES-suggester:True tag, and can access each other freely. What is missing from my configuration that doesn't allow them to discover each other?

**Comment by vanga** [comment]
@yaron-idan this would happen if instances don't have enough permissions,
do those instances have permission to do `DescribeInstances` operation?
Did you setup any access keys or iam roles?

**Comment by yaron-idan** [comment]
I've thought of that as well. Tried running describe-instances using the AWS CLI and it worked. The instances are assigned an IAM role that has ample permissions.
In fact - this role is used for another ES cluster we are using, launched with Bitnami AMI. I've tried comparing the two clusters and the main difference I saw is the way nodes on both clusters publish their addresses. 
On the working clusters the node starts up publishing himself like this - 
`bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.0.0.169:9300]}`
While in my new cluster nodes start up like this - 
`publish_address {10.0.0.71:9200}, bound_addresses {10.0.0.71:9200}`

Since the network.bind_host is not set in the Bitnami AMI, I don't know how to make my new instnaces behave the same, any advice? Am I in the right direction at all?

**Comment by gingerwizard** [comment]
@yaron-idan have you tried binding to 0.0.0.0 and using you current publish configuration?

@jakommo any thoughts/experience here?

**Comment by yaron-idan** [comment]
I tried that now, setting the network.bind_host parameter to "0.0.0.0". It did not fix my issue.
When I look at the log file I see that the instances bounded themselves to an empty string. Here's an excerpt from the log file - 
`publish_address {10.0.0.79:9300}, bound_addresses {[::]:9300}`
Is this the expected result of such configuration?

**Comment by yaron-idan** [comment]
OK, I found the problem, and it's on my end. I used a playbook to create my EC2 instances and gave them the right tag to look for. The play capitalized my tag value, causing the EC2 instances to be invisible to the plugin. Now that I fixed the case of the tag value everything is working fine. Thanks for the help!
