### ISSUE TITLE
Use uri module to interact with the API

### ISSUE THREAD

**Issue by barryib** [elastic/ansible-elasticsearch#128]
We should consider using the [uri module](http://docs.ansible.com/ansible/uri_module.html) instead of curl (with shell or command) when interacting with the API. It's more ansible friendly, avoid warnings and most of all idempotent.

**Comment by gingerwizard** [comment]
Agreed i've moved to this for shield management. Templates still uses curl. I'll change.

**Comment by aosagie** [comment]
I like this decision, but just out of curiosity: how is using the uri module to PUT more idempotent than using curl to PUT? I thought it was basically the same just at a different abstraction level.

**Comment by barryib** [comment]
@aosagie This issue doesn't refer to PUT method only, but all API interactions (with shield by example).

As for idempotency, I meant that you can run the task as many time you want without breaking things (have the same result) and have the **changed** feedbacks. Indeed, for PUT method, the module will always send the file if it your concern, but we have the changed feedback ([uri module](https://github.com/ansible/ansible-modules-core/blob/devel/network/basics/uri.py#L430)) without doing some hacks with ``register`` and ``changed_when``.

**Comment by gingerwizard** [comment]
Proposed solution for this is [here](https://github.com/elastic/ansible-elasticsearch/pull/129/commits/605baf9a96be9109db46ff1c162565d8f7dfde94)

This is part of the shield support PR so auth and a no auth supported.

**Comment by gingerwizard** [comment]
Merged in.
