### ISSUE TITLE
Is there a reason why `set_fact:` is used instead of `vars/main.yml`?

### ISSUE THREAD

**Issue by strootman** [elastic/ansible-elasticsearch#133]
I've been working on roles which complement/supplement this role, specifically for rolling restarts.
In doing so, I wanted to avoid duplicating variable creation for things this role calculates based off of the `es_instance_name`, like the default `es_config['node.name']` and the service name.

However, because those variables are created as facts with `set_fact:`, they aren't available to other `pre_tasks` or other roles within the same play.

Currently, I have to duplicate the same variables if I want to use them _before_ this role executes.

**Comment by gingerwizard** [comment]
Hi @strootman apologies for the delayed response ive been out.

So they reason we didn't expose them was they weren't intended to be overwritten or differ based on logic.  However, if you have explicit requirements please feel free to raise a PR or request what you need to be made a var.  I'm happy to consider moving them on a case by case basis- i'm just not convinced its best to change the current approach for all.  Happy to discuss.

All variables are now set in [tasks/elasticsearch-parameters.yml](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-parameters.yml)

**Comment by strootman** [comment]
@gingerwizard What _needs_ to be a var which can be shared? A variable to access the computed service name would be a good start. 

This is just a quick reply, I'll come back with a more thorough list later.

**Comment by gingerwizard** [comment]
That seems reasonable to access. Do you want to make a pull request @strootman

**Comment by gingerwizard** [comment]
Returning to this. @strootman exposing the service_name might actually simplify single node installs as users could then set this to `elasticsearch`. I'm going to propose a PR for this and update the tests. We will close after this - raise separate tickets if we want other variables exposed.

**Comment by gingerwizard** [comment]
Returning to this. @strootman exposing the service_name might actually simplify single node installs as users could then set this to `elasticsearch`. I'm going to propose a PR for this and update the tests. We will close after this - raise separate tickets if we want other variables exposed.
