### ISSUE TITLE
support for elasticsearch 5.0

### ISSUE THREAD

**Issue by babadofar** [elastic/ansible-elasticsearch#135]
I suspect you are hard at work developing support for elasticsearch 5.0? Any idea of when a public beta is available? I volunteer for testing :)

**Comment by strootman** [comment]
Have you looked at the [Elastic Pioneer](https://www.elastic.co/blog/elastic-pioneer-program) program?

**Comment by jakommo** [comment]
@babadofar you don't need to "join" the pioneer program, you can just download v5 https://www.elastic.co/downloads/elasticsearch (scroll down a bit) and the other tools as well on https://www.elastic.co/v5.

We haven't started developing for 5 support yet, as we wanted to wait on the beta/feature freeze.
But it's definitely on the agenda once the beta is out.

**Comment by tallakh** [comment]
My apologies for commenting on a closed issue, but do you have any idea on when elasticsearch 5.0 support will be available?
