### ISSUE TITLE
[Discussion] How to ask question or help

### ISSUE THREAD

**Issue by barryib** [elastic/ansible-elasticsearch#148]
The ansible-elasticsearch role is getting fancy and broadly used. So we need to add a new canal where users can ask question, help.

The Github issue tracker is not the best place for questions. Maybe gitter, irc or slack and a mailing list would be more appropriate.

**Comment by gingerwizard** [comment]
discuss.elastic.co is the best place.

**Comment by gingerwizard** [comment]
Specifically please raise issues here and include "Ansible" in the title 
https://discuss.elastic.co/c/elasticsearch

Make it clear you are using this role.

**Comment by barryib** [comment]
LGTM. 

Maybe we should write it some were in the README with the correct link.

**Comment by gingerwizard** [comment]
Agreed.

**Comment by gingerwizard** [comment]
https://github.com/elastic/ansible-elasticsearch#questions-on-usage
