### ISSUE TITLE
Provide a license in this repository/for this work

### ISSUE THREAD

**Issue by mscook-Itoc** [elastic/ansible-elasticsearch#152]
Hi this is great work. However for us to use it we require a license to be defined.

Via [GitHub licensing page](https://help.github.com/articles/open-source-licensing):

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

Please provide a license in this repository/for this work.

Thanks
Mitch

**Comment by jakommo** [comment]
Thanks for reporting @mscook-Itoc . Fixed now.
