### ISSUE TITLE
update doc

### ISSUE THREAD

**Issue by barryib** [elastic/ansible-elasticsearch#162]
The doc is somehow outdated. There are some missing parts:
- [x] xpack (and shield) support
- [ ] tags description
- [x] Is ES 1.x still supported?

Feel free to complete.

**Comment by gingerwizard** [comment]
+1 prior to release on Ansible 2.1.2

**Comment by gingerwizard** [comment]
Xpack and shield documented in https://github.com/elastic/ansible-elasticsearch/pull/224

**Comment by gingerwizard** [comment]
@strootman would you mind enhancing the docs with tags usage - a simple summary section would be fine. I haven't actually tested these or used them. We should probably add a test.

**Comment by strootman** [comment]
@gingerwizard It will have to be a separate doc. Can't do that without listing some examples, and this role has A LOT of tasks ;)

Also, I'm not sure that testing Ansible tag usage is necessary, though I'm not against it.

**Comment by gingerwizard** [comment]
I think the usage of tags is quite advanced. I'm not convinced we need to document. Closing. We can take questions on this as an issue if needed.

**Comment by strootman** [comment]
Completely agree! If your Ansible-fu is strong, then you'll understand how to use the tags.
The current mention of tags in the `Usage` section is sufficient.
