### ISSUE TITLE
Install elasticsearch shield plugin issue with multi node cluster

### ISSUE THREAD

**Issue by GaneshbabuRamamoorthy** [elastic/ansible-elasticsearch#167]
Hi All,

I am trying to setup multi node in the same host using my own ansible playbook.

Also I am trying to install shield using xpack feature but I am facing an issue in doing mulit node setup,

So what I did is, I first executed the multi.yml file under the test folder to try and see if the nodes are created but it failed to do so.
Below are the error which I got during execution of
**"anisble-playbook -vv multi.yml"**

> failed: [localhost](item=esreaduser) => {"changed": true, "cmd": ["/usr/share/elasticsearch/bin/shield/esusers", "useradd", "esreaduser", "-p", "Read01"], "delta": "0:00:00.002708", "end": "2016-10-20 11:15:44.796417", "failed": true, "item": "esreaduser", "rc": 1, "start": "2016-10-20 11:15:44.793709", "stderr": "", "stdout": "ERROR: The configuration directory [/etc/elasticsearch/node1/shield] does not exist. The esusers tool expects Shield configuration files in that location.\nThe plugin may not have been installed with the correct configuration path. If [/usr/share/elasticsearch/config/shield] exists, please copy the shield directory to [/etc/elasticsearch/node1]", "stdout_lines": ["ERROR: The configuration directory [/etc/elasticsearch/node1/shield] does not exist. The esusers tool expects Shield configuration files in that location.", "The plugin may not have been installed with the correct configuration path. If [/usr/share/elasticsearch/config/shield] exists, please copy the shield directory to [/etc/elasticsearch/node1]"], "warnings": []}

I have the attached modified multi.yml file for your reference to replicate the issue for the ansible elasticsearch project and also I am attaching my own playbook for our ES installation setup,

Regards,
Ganeshbabu R

[ansible yml.zip](https://github.com/elastic/ansible-elasticsearch/files/547798/ansible.yml.zip)

**Comment by jakommo** [comment]
Hi @GaneshbabuRamamoorthy,

I spent quite some time today to dig into this and found a lot off issues. I fixed some of them, but it's not ready for commit yet.

With the multi node setup and master only/data only on one machine, there is currently a catch-22. The native realm commands run against every node defined, which currently leads to, that in both cases (master only or data only), the command is not successful.
Because either the index isn't ready (master installed first) or there is no master available (data installed first). 

Not sure how to work around this. I think we might need to find a way to run the commands after the cluster is operational. 

cc @gingerwizard @jpcarey

**Comment by jpcarey** [comment]
@jakommo maybe `run_once: true` and `retries: 5` and  `delay: 10`. That feels hacky but, could give the master node time to come online, and keeps the native realm commands to only being run one time?

**Comment by GaneshbabuRamamoorthy** [comment]
Hi @jakommo 

Can I get any update on this request?

**Comment by jakommo** [comment]
Hi @GaneshbabuRamamoorthy, I just pushed https://github.com/elastic/ansible-elasticsearch/pull/188 and once it is merged in, it should work.

I had to adjust your playbook a little to work around the chicken/egg problem mentioned above. 
With splitting up the dedicated master or data node into a separate call of the role, it's working now.

Basically the first run installs the master nodes, only setting up file based users. The second step installs the data nodes and then applies the Native User/Roles.
This is required as the native realm relies on an index in Elasticsearch and this index does not assign if there are no data nodes. 

This is the ansible `hosts` file I used: (Note: each host is defined twice, once in each "role" section)

```
[master-nodes]
10.148.200.137  ansible_connection=ssh ansible_ssh_user=root
10.148.200.27 ansible_connection=ssh ansible_ssh_user=root
10.148.200.237 ansible_connection=ssh ansible_ssh_user=root
[data-nodes]
10.148.200.137 ansible_connection=ssh ansible_ssh_user=root
10.148.200.27 ansible_connection=ssh ansible_ssh_user=root
10.148.200.237  ansible_connection=ssh ansible_ssh_user=root
```

And this is the playbook I used:

```
---
  #strategy: debug
- hosts: master-nodes
  roles:
    - { role: elasticsearch, es_instance_name: "master_node",
        es_config: {
        node.name: "master_node",
        cluster.name: "ES_LOCAL_CLUSTER",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: true,
        bootstrap.mlockall: true,
        discovery.zen.ping.multicast.enabled: false,
        discovery.zen.minimum_master_nodes: 2,
        discovery.zen.ping.unicast.hosts: "{{ groups['master-nodes'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(':9300,') }}:9300",
        network.host: "{{ansible_default_ipv4.address}}"}
    }
  vars:
    es_scripts: true
    es_templates: false
    es_version_lock: false
    es_heap_size: 1g
    es_enable_xpack: true
    es_xpack_features:
      - license
      - shield
    es_api_basic_auth_username: esadmin
    es_api_basic_auth_password: XXX
    es_message_auth_file: system_key
    es_role_mapping:
      power_user:
        - "cn=admins,dc=example,dc=com"
      user:
        - "cn=users,dc=example,dc=com"
        - "cn=admins,dc=example,dc=com"
    es_users:
      file:
        esadmin:
          password: XXX
          roles:
            - admin
        esreaduser:
          password: Read01
          roles:
            - read_user
    es_roles:
      file:
        admin:
          cluster:
            - all
          indices:
            - names: '*'
              privileges:
                - all
        power_user:
          cluster:
            - monitor
          indices:
            - names: '*'
              privileges:
                - all
        read_user:
          indices:
            - names: '*'
              privileges:
                - read
        kibana4_server:
          cluster:
              - monitor
          indices:
            - names: '.kibana'
              privileges:
                - all

- hosts: data-nodes
  roles:
    - { role: elasticsearch, es_instance_name: "data_node",
        es_config: {
        node.name: "data_node",
        cluster.name: "ES_LOCAL_CLUSTER",
        http.port: 9201,
        transport.tcp.port: 9301,
        node.data: true,
        node.master: false,
        bootstrap.mlockall: true,
        discovery.zen.ping.multicast.enabled: false,
        discovery.zen.minimum_master_nodes: 2,
        discovery.zen.ping.unicast.hosts: "{{ groups['master-nodes'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(':9300,') }}:9300",
        network.host: "{{ansible_default_ipv4.address}}"}
    }
  vars:
    es_scripts: true
    es_templates: false
    es_version_lock: false
    es_heap_size: 2g
    es_enable_xpack: true
    es_xpack_features:
      - license
      - shield
      # - watcher
      # - marvel-agent
    es_api_basic_auth_username: esadmin
    es_api_basic_auth_password: XXX
    es_message_auth_file: system_key
    es_role_mapping:
      power_user:
        - "cn=admins,dc=example,dc=com"
      user:
        - "cn=users,dc=example,dc=com"
        - "cn=admins,dc=example,dc=com"
    es_users:
      native:
        kibana4_server:
          password: XXX
          roles:
            - kibana4_server
      file:
        esadmin:
          password: XXX
          roles:
            - admin
        esreaduser:
          password: XXX
          roles:
            - read_user
        test:
          password: XXX
          roles:
            - read_user
    es_roles:
      file:
        admin:
          cluster:
            - all
          indices:
            - names: '*'
              privileges:
                - all
        power_user:
          cluster:
            - monitor
          indices:
            - names: '*'
              privileges:
                - all
        read_user:
          indices:
            - names: '*'
              privileges:
                - read
        kibana4_server:
          cluster:
              - monitor
          indices:
            - names: '.kibana'
              privileges:
                - all
      native:
        logstash:
          cluster:
            - manage_index_templates
          indices:
            - names: 'logstash-*'
              privileges:
                - write
                - delete
                - create_index
```

Please test after https://github.com/elastic/ansible-elasticsearch/pull/188 is merged and let me know if it works

**Comment by jakommo** [comment]
@GaneshbabuRamamoorthy I merged the PR today, so if you update the role and use the example above, you should be good to go.

**Comment by GaneshbabuRamamoorthy** [comment]
Thanks @jakommo 

Let me try it and get back to you with the response 👍

**Comment by GaneshbabuRamamoorthy** [comment]
Hi @jakommo 

I modified the playbook with your changes & I executed the below command to setup ES
**ansible-playbook --vv multi-elasticsearch.yml**
but getting error,

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: u'{u'discovery.zen.minimum_master_nodes': 1, u'node.data': False, u'bootstrap.mlockall': True, u'discovery.zen.ping.unicast.hosts': u"{{ groups['master-nodes'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(':9302,') }}:9302", u'http.port': 9202, u'network.host': u'{{ansible_default_ipv4.address}}', u'discovery.zen.ping.multicast.enabled': False, u'transport.tcp.port': 9302, u'cluster.name': u'ES_LOCAL_CLUSTER', u'node.name': u'master_node', u'node.master': True}: ipv4'
> fatal: [10.7.147.21]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}


**Also If I am trying to run with this (rdaas-elasticsearch.yml) playbook and its working fine.**
[es_playbooks.zip](https://github.com/elastic/ansible-elasticsearch/files/591244/es_playbooks.zip)

Please kindly correct me if am doing anything wrong in playbook.

```
Note:- Below is the etc/ansible/hosts file contains like this
10.7.147.21
[master-nodes]
10.7.147.21 ansible_connection=ssh ansible_ssh_user=esadmin
[data-nodes]
10.7.147.21 ansible_connection=ssh ansible_ssh_user=esadmin
```

Regards,
Ganeshbabu R

**Comment by GaneshbabuRamamoorthy** [comment]
@jakommo by debugging deeper and I have got the following error msg during the playbook run,

```
 An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 401, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/task.py", line 246, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/base.py", line 330, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 358, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 330, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 494, in _do_template
    res = j2_concat(rf)
  File "<template>", line 6, in root
  File "/usr/lib/python2.7/dist-packages/jinja2/runtime.py", line 153, in resolve
    return self.parent[key]
  File "/usr/lib/python2.7/dist-packages/ansible/template/vars.py", line 91, in __getitem__
    raise type(e)(to_unicode(variable) + ': ' + e.message)
KeyError: u'{u\'discovery.zen.minimum_master_nodes\': 1, u\'node.data\': False, u\'bootstrap.mlockall\': True, u\'discovery.zen.ping.unicast.hosts\': u"{{ groups[\'master-nodes\'] | map(\'extract\', hostvars, [\'ansible_eth0\', \'ipv4\', \'address\']) | join(\':9302,\') }}:9302", u\'http.port\': 9202, u\'network.host\': u\'{{ansible_default_ipv4.address}}\', u\'discovery.zen.ping.multicast.enabled\': False, u\'transport.tcp.port\': 9302, u\'cluster.name\': u\'ES_LOCAL_CLUSTER\', u\'node.name\': u\'master_node\', u\'node.master\': True}: ipv4'

fatal: [10.7.147.21]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```


It's trying to find the python 2.7 but currently in my server I have 2.6.6 Is that because of lower version?

Please let me know your thoughts.

Regards,
Ganeshbabu R

**Comment by GaneshbabuRamamoorthy** [comment]
I slightly modified my playbook with setting up multi node ES 2.x cluster and though I am able to install all the plugins(including shield)but I am finding some strange in head plugin and in which shards are unassigned for indices?

![image](https://cloud.githubusercontent.com/assets/20658619/20311891/7f1bfd3e-ab77-11e6-8d93-b2eaad922c66.png)

I have created two data nodes(data & client) & one master but still the replicas of the indices are unassigned and I attached my playbook for your reference and let me know your response.

[dev-elasticsearch.zip](https://github.com/elastic/ansible-elasticsearch/files/592417/dev-elasticsearch.zip)

**Comment by GaneshbabuRamamoorthy** [comment]
The setting which I given in my playbook **cluster.routing.allocation.same_shard.host: true** 
prevent allocation of multiple instances of the same shard on a single host, based on host name and host address.

But still I am getting the below error when I ran the playbook multi-elasticsearch.yml

` An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 401, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/task.py", line 246, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/base.py", line 330, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 358, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 330, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 494, in _do_template
    res = j2_concat(rf)
  File "<template>", line 6, in root
  File "/usr/lib/python2.7/dist-packages/jinja2/runtime.py", line 153, in resolve
    return self.parent[key]
  File "/usr/lib/python2.7/dist-packages/ansible/template/vars.py", line 91, in __getitem__
    raise type(e)(to_unicode(variable) + ': ' + e.message)
KeyError: u'{u\'discovery.zen.minimum_master_nodes\': 1, u\'node.data\': False, u\'bootstrap.mlockall\': True, u\'discovery.zen.ping.unicast.hosts\': u"{{ groups[\'master-nodes\'] | map(\'extract\', hostvars, [\'ansible_eth0\', \'ipv4\', \'address\']) | join(\':9302,\') }}:9302", u\'http.port\': 9202, u\'network.host\': u\'{{ansible_default_ipv4.address}}\', u\'discovery.zen.ping.multicast.enabled\': False, u\'transport.tcp.port\': 9302, u\'cluster.name\': u\'ES_LOCAL_CLUSTER\', u\'node.name\': u\'master_node\', u\'node.master\': True}: ipv4'

fatal: [10.7.147.21]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}`


Let me know your thoughts

**Comment by jpcarey** [comment]
With `cluster.routing.allocation.same_shard.host: true`, this should prevent the replica from being allocated to another node on the same host.

You are getting a KeyError on `ipv4`. It looks like `ipv4` is an array, not an object. You would need something like `map("extract", hostvars, ["ansible_en0", "ipv4", 0, "address"]) | list`, but hardcoding the to the first item in the array is not a great idea in general.

```
            "ansible_en0": {
                "device": "en0",
                "flags": [
                    "UP",
                    "BROADCAST",
                    "SMART",
                    "RUNNING",
                    "SIMPLEX",
                    "MULTICAST"
                ],
                "ipv4": [
                    {
                        "address": "192.168.1.17",
                        "broadcast": "192.168.1.255",
                        "netmask": "255.255.255.0",
                        "network": "192.168.1.0"
                    }
                ],
...
```

**Comment by jakommo** [comment]
@GaneshbabuRamamoorthy I second @jpcarey . I used this to automatically populate the `discovery.zen.ping.unicast.hosts` with the IP:Port of the masters, but it looks like your ENV uses other interface names than `eth0`.

`discovery.zen.ping.unicast.hosts: "{{ groups['master-nodes'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(':9300,') }}:9300", network.host: "{{ansible_default_ipv4.address}}"}`

You could try to change `ansible_eth0` to the interface name matching your ENV, or you just go with a static setting of your masters IPs. 

E.g.:

Replace both occurrences of the above with `discovery.zen.ping.unicast.hosts: "10.7.147.21:9300"` (note this should point to the transport port of your master in both entries. 

You also need to remove `discovery.zen.minimum_master_nodes: 2,` if you are testing with just one master.
