### ISSUE TITLE
Retink repo handling

### ISSUE THREAD

**Issue by jakommo** [elastic/ansible-elasticsearch#174]
Currently apt uses the `apt_repository` module, while `yum` is using a template. 
There is now `yum_repository` module available.

Would be good to use the dedicated module for both apt and yum.

Also the apt_repository does not use the `filename` setting, so between major versions, this would result in a new repo file getting created. Would be better to have a fixed, generic filename.

Lastly, 5.x used a new URL for the repo, so we should think of a new/generic way of handling this to work wit all versions (even if the url changes).

**Comment by gingerwizard** [comment]
@jakommo did you ever put a PR together for this? If not, i can have a stab at it.
