### ISSUE TITLE
Does this role support installing ES v5.x?

### ISSUE THREAD

**Issue by strootman** [elastic/ansible-elasticsearch#180]
Looking at the plugins tasks, it looks like this will fail since `{{es_home}}/bin/plugin` doesn't exist in ES `v5.0`. 

Shouldn't it be `{{ es_home }}/bin/elasticsearch-plugin`?

**Comment by veger** [comment]
I believe I have fixed this issue with PR #178

**Comment by bdgscotland** [comment]
Is this working with v5 now then?

**Comment by jakommo** [comment]
@bdgscotland it does not yet, but I just created a `5.x` branch and will merge https://github.com/elastic/ansible-elasticsearch/pull/182 (or the follow up PR) as soon as possible.

**Comment by gingerwizard** [comment]
I have created a 2.x branch. This will be maintained separately to master which will be for 5.x support only.  1.x support is no longer supported as 1.x is EOL shortly.

**Comment by gingerwizard** [comment]
I hope to make a pull request on master today which will resolve all issues re 5.x. Master will support 5.x and 2.x support will be via a branch.

**Comment by gingerwizard** [comment]
It does now https://github.com/elastic/ansible-elasticsearch/pull/234 !
