### ISSUE TITLE
Problem while Ensuring Java is installed

### ISSUE THREAD

**Issue by KevinSonnie** [elastic/ansible-elasticsearch#185]
Hey together,

I was testing your first example playbook and stumbled over what I think may be an error within the role:

I've got a Fedora VM with Ansible 2.2 for Deployment and an Vanilla Debian 8 VM as to-be elastic server.

During the step which ensures Java is installed ansible hangs without any notification.
Running -vvv gives this step as the last one executed:
`<192.168.101.***> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/*****/.ansible/cp/ansible-ssh-%C -tt 192.168.101.*** '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1478180368.12-58490932807117/apt.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1478180368.12-58490932807117/" > /dev/null 2>&1 && sleep 0'"'"''
`

After that I tried to execute the **/root/.ansible/tmp/ansible-tmp-1478180368.12-58490932807117/apt.py** script on the target server and got the following error:
`Traceback (most recent call last):
   File "/tmp/ansible_AdqqTY/ansible_module_apt.py", line 909, in <module> main()
   File "/tmp/ansible_AdqqTY/ansible_module_apt.py", line 892, in main
      if updated_cache and not retvals['changed']:
KeyError: 'changed'`

If you've got any questions feel free to ask.
Thank you for your work

**Comment by jakommo** [comment]
Hi @KevinSonnie , interesting, not sure if this is the real issue.
When you say Vanilla Debian 8, I guess there is no Java installed on that VM, correct?

Debian 8 is part of our [integration tests](http://build-eu-00.elastic.co/job/ansible_elasticsearch_acceptance_pr/) , and I don't see it failing. 
The ensure Java is installed should run on almost all configurations and it sure does on the integration tests.

**Comment by ponchowang** [comment]
encountered the same issue as well. After some digging, it turns out that it because of the machine does not have outbound connection, so running apt-get failed.

I am using ec2. So try to run apt-get directly on that box, to see whether it can succeed

sudo apt-get update
