### ISSUE TITLE
Support for 'path.repo' setting

### ISSUE THREAD

**Issue by jvjensen** [elastic/ansible-elasticsearch#189]
Hey all,

From the default setting, main.yml the options for dirs in the elasticsearch.yml conf are:
```
es_pid_dir: "/var/run/elasticsearch"
es_data_dirs: "/var/lib/elasticsearch"
es_log_dir: "/var/log/elasticsearch"
es_work_dir: "/tmp/elasticsearch"
```

Please add support for: __path.repo__ via setting __es_repo_dir__

Best Jannik

**Comment by gingerwizard** [comment]
@jvjensen you can just specify this in the config hash.  The reason we have the others is we manipulate them with the es_instance_name - something im not sure you'd want to do with this setting.
