### ISSUE TITLE
Redhat: Init scripts should be parametrized based on instance_name

### ISSUE THREAD

**Issue by zouzias** [elastic/ansible-elasticsearch#195]
I think there is an issue with the Redhat init scripts. More precisely, L40-45 at 

https://github.com/elastic/ansible-elasticsearch/blob/master/templates/init/redhat/elasticsearch.j2#L40

are

```
LOG_DIR="/var/log/elasticsearch"
DATA_DIR="/var/lib/elasticsearch"
CONF_DIR="/etc/elasticsearch"
PID_DIR="/var/run/elasticsearch"
```
but should be

```
LOG_DIR={{ log_dir }}
DATA_DIR={{ data_dirs }}
CONF_DIR={{conf_dir}}
PID_DIR={{ pid_dir }}
```

If this is an issue, I could PR this fix. Thank you for making the ansible scripts available!

**Comment by jakommo** [comment]
Hi @zouzias thanks for reporting. The init script sources the [sysconfig file](https://github.com/elastic/ansible-elasticsearch/blob/master/templates/init/redhat/elasticsearch.j2#L47L50) and these variables are defined [there](https://github.com/elastic/ansible-elasticsearch/blob/master/templates/elasticsearch.j2#L12L18). 

The sysconfig file should always be created, so these values should never be used. 

Closing for now. If this caused an issue for you, feel free to reopen.
