### ISSUE TITLE
Installation fails on EC2 instances when specifying "es_version=5.0.0-alpha5"

### ISSUE THREAD

**Issue by yaron-idan** [elastic/ansible-elasticsearch#197]
I have managed to use the role to successfully install ES 2.3.4 on my EC2 instances but now when I try to use the same configuration for ES 5.0 the role fails with the following error  - 
```
TASK [elasticsearch : Start elasticsearch service] *****************************
fatal: [ES2]: FAILED! => {"changed": false, "failed": true, "msg": " * Starting Elasticsearch Server - ip-10-0-10-198\n   ...fail!\n"}
```
I am using the following AWS AMI - ami-40d28157 (after installing python manually, for ansible to work), and this is my playbook - 
```
---
- name: Install and configure ES
  hosts: ES_master
  become: true
  become_user: root
  roles:
      #expand to all available parameters
      - { role: elasticsearch, es_instance_name: "{{ ansible_hostname }}", es_data_dirs: "/mnt/elasticsearch/data", es_log_dir: "/mnt/elasticsearch/logs", es_work_dir: "/mnt/elasticsearch/temp",
      es_config: {
          node.name: "{{ ansible_hostname }}",
          cluster.name: "custom-cluster",
          node.data: true,
          node.master: true,
          bootstrap.mlockall: true,
          discovery.zen.ping.multicast.enabled: false,
          discovery.ec2.tag.ES-suggester: true,
          discovery.type: "ec2",
          cloud.aws.region: "us-east-1",
          network.bind_host: "0.0.0.0",
          transport.tcp.port: 9300,
          http.port: 9200,
          }
      }
  vars:
      es_major_version: "5.x"
      es_version: "5.0.0-alpha5"
      es_heap_size: "500m"
```

I saw previous issues claiming that this role should support 5.0, but I'm wondering if the problem is due to the support of an alpha version?
When I try to install ES 5.0.1 manually, following the instructions on elastic.co website, the install passes successfully.

**Comment by jakommo** [comment]
@yaron-idan no, the role does not yet officially support 5, see the readme.
There is a PR https://github.com/elastic/ansible-elasticsearch/pull/182 for 5 though.
