### ISSUE TITLE
Missing from Ansible Galaxy

### ISSUE THREAD

**Issue by kaikousa** [elastic/ansible-elasticsearch#198]
Just tried to install this role via Galaxy and got the following error: ` [WARNING]: - elastic.ansible-elasticsearch was NOT installed successfully: - sorry, elastic.ansible-elasticsearch was not found on https://galaxy.ansible.com.`

Also if I go to Galaxy and browse the roles I can see this role in the search results but I get a `404` when I click on the link.

Was it pulled away for a reason or something else happened?

**Comment by jpcarey** [comment]
Issue: [Deploy to Ansible Galaxy #89](https://github.com/elastic/ansible-elasticsearch/issues/89) is already open for this.  It has not been published to Galaxy.
