### ISSUE TITLE
Add Role to Ansible Galaxy

### ISSUE THREAD

**Issue by miskolc** [elastic/ansible-elasticsearch#201]
I did a search on [Ansible Galaxy](https://galaxy.ansible.com/) for this role and it does not exist there even though it seems to be the most popular on github.
It would be nice if it was added to Galaxy, a lot of people go there first when they are searching for roles.

**Comment by jpcarey** [comment]
Issue: "Deploy to Ansible Galaxy" #89 is already open for this.
