### ISSUE TITLE
Tasks incorrectly reference es_config['network.host']

### ISSUE THREAD

**Issue by pixelrebel** [elastic/ansible-elasticsearch#208]
https://github.com/elastic/ansible-elasticsearch/blob/master/handlers/elasticsearch-templates.yml#L7

Results in the following when `es_config['network.host'] = ['_local_', '_eth0_']`
```
fatal: [es]: FAILED! => {"changed": false, "elapsed": 310, "failed": true, "msg": "Timeout when waiting for ['_local_', '_eth0_']:9200"}
```

**Comment by pixelrebel** [comment]
I have submitted a [PR](https://github.com/elastic/ansible-elasticsearch/pull/209) to clean this up.  Sticking with the `es_api_host` as the only variable to use for the host in API calls, etc.  `es_api_host ` defaults to `localhost` which is a good default since many elasticsearch configs set `_local_` in `network.host`.

**Comment by gingerwizard** [comment]
Merged fix. Thanks @pixelrebel
