### ISSUE TITLE
5.x can't be installed when bootstrap.mlockall: true is set

### ISSUE THREAD

**Issue by keelson** [elastic/ansible-elasticsearch#211]
The parameter check fails because heap is no longer configured as es_heap_size in 5.x 
https://github.com/elastic/ansible-elasticsearch/blob/5.x/tasks/elasticsearch-parameters.yml#L22
It should check for the follwowing es_java_opts to make it compatible with 5. 
```
es_java_opts:
  - "-Xms16g"
  - "-Xmx16g"
```

**Comment by tomekit** [comment]
I am not sure if this is the problem, but in ES5 it's: `bootstrap.memory_lock: true`
Check: https://www.elastic.co/guide/en/elasticsearch/reference/master/setup-configuration-memory.html

**Comment by jakommo** [comment]
I second @tomekit , this sounds to be the issue/solution.

**Comment by keelson** [comment]
Thanks, I can no longer reproduce the issue.
