### ISSUE TITLE
How do I config elasticsearch to run as a daemon?

### ISSUE THREAD

**Issue by ponchowang** [elastic/ansible-elasticsearch#230]
Right now if i killed the process, it won‘t be restarted.
I am on ubuntu。

**Comment by jakommo** [comment]
> Right now if i killed the process, it won‘t be restarted.

What do you mean by kill the process. Killing it with `kill` or using the init/systemd script to gracefully shut it down? 

You need to provide more information's on this.

* Your playbook
* Ubuntu version
* command used to `kill` the process

**Comment by gingerwizard** [comment]
Not relevant to the playbook.
