### ISSUE TITLE
5.x: incorrect es_package_url

### ISSUE THREAD

**Issue by akhayyat** [elastic/ansible-elasticsearch#232]
The `es_package_url` is set to "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch" (`defaults/main.yml`). However, this is an invalid URL for 5.x, or at least for Debian packages.

As a result, with `es_use_repository: no`, installation fails (tested on Debian).

**Comment by jakommo** [comment]
Thanks for reporting. Can you manually set it to `https://artifacts.elastic.co/packages/5.x/apt stable main` in https://github.com/elastic/ansible-elasticsearch/blob/master/defaults/main.yml#L7 and see if that helps? 

@gingerwizard is this on your radar for the PR you are working on?

**Comment by gingerwizard** [comment]
Yes ill fix.

**Comment by dekhtyarev** [comment]
Hello everybody!

I'm testing the cluster upgrade from 2.4.3 to 5.1.2, via this role, and today or tomorrow I will do PR on this bug and some others.

**Comment by jakommo** [comment]
Hi @dekhtyarev that sounds awesome, however I know that @gingerwizard is also working on a big PR and it would be good if you are not working on the same parts, to avoid merging conflicts. 
Can you share what you are planing to do? E.g. which areas this PR will be for?

**Comment by dekhtyarev** [comment]
@jakommo, I put a branch with the changes in my fork.  
Here is a comparison with the current master: https://github.com/elastic/ansible-elasticsearch/compare/master...dekhtyarev:fix_for_es_5_ubuntu_install

Please see it, if they will be useful, then I would be happy to create a PR.

**Comment by jakommo** [comment]
Thanks, I'm not exactly sure which areas @gingerwizard is working on. Let's wait for his reply.

One note about the change in `defaults/main.yml`, this would make it only work for 5.x while we need to keep backwards compatibility with 2.x. Unfortunately the repo urls are different and the new one used in 5 does not have 2.x packages, as we switched our build system. 
We need some condition around this to check if it's 2.x or 5.x, but see https://github.com/elastic/ansible-elasticsearch/issues/232#issuecomment-272148360 @gingerwizard is already working on this part.

**Comment by dekhtyarev** [comment]
@jakommo 

Yes, there breaks backwards compatibility. But I think that people who want to use the role for 2.x version ES - will use the 2.x branch. Or use a specific commit, when pulling the role in his deploy.
To alter the current role for backward compatibility versions pretty hard :) Though for Logstash I did like.

For Logstash I made backward compatibility as follows:
* Variables: https://github.com/dekhtyarev/logstash-role/blob/master/defaults/main.yml#L14
* Set variables for a particular installation: https://github.com/dekhtyarev/logstash-role/blob/master/tasks/020_logstash_installation_Debian.yml#L15

Maybe it will be useful to you. @gingerwizard

**Comment by jakommo** [comment]
> But I think that people who want to use the role for 2.x version ES - will use the 2.x branch

Yeah this would be in an ideal world, but there are many issues opened by users that are new to elasticsearch and/or ansible and they probably don't know how to pull another branch or checkout an certain commit.

**Comment by gingerwizard** [comment]
Hi @dekhtyarev im about to make a pull where all 5.x tests pass on master. I've removed 2.x support on master - people can use the branch as you state.

**Comment by gingerwizard** [comment]
Resolved through https://github.com/elastic/ansible-elasticsearch/pull/234
