### ISSUE TITLE
Syntax error in tasks/xpack/elasticsearch-xpack-install.yml?

### ISSUE THREAD

**Issue by mj84** [elastic/ansible-elasticsearch#233]
Hello,

using Ubuntu 16.04.1 with ansible 2.2.0.0-1ppa~xenial and a minimal playbook for elasticsearch I receive the following error 4 times (line breaks converted for better readability):

```
fatal: [localhost]: FAILED! => {
  "failed": true,
  "reason": "Syntax Error while loading YAML.
  
  
  The error appears to have been in '/etc/ansible/roles/elasticsearch/tasks/xpack/elasticsearch-xpack-install.yml': line 16, column 23, but may
  be elsewhere in the file depending on the exact syntax problem.
  
  The offending line appears to be:
  
  - name: Remove {{item}} plugin
  command: {{es_home}}/bin/plugin remove {{item}}
  ^ here
  We could be wrong, but this one looks like it might be an issue with
  missing quotes.  Always quote template expression brackets when they
  start a value. For instance:

  with_items:
  - {{ foo }}
  
  Should be written as:


  with_items:
  - "{{ foo }}"
}
```

After some digging around i found that the error message from ansible seems to be spot-on, when i put the command line in line 16 in tasks/xpack/elasticsearch-xpack-install.yml in quotes the installation works without errors:
`command: "{{es_home}}/bin/plugin remove {{item}}" `

Regards,
Markus

**Comment by gingerwizard** [comment]
Yes will be fixed in the latest pull we intend to make today for 5.x. We'll also need to fix for the 2.x branch

**Comment by gingerwizard** [comment]
Resolved on master.
