### ISSUE TITLE
Problem with location of jvm.options - master branch - ES 5.1.2 - Ubuntu 14

### ISSUE THREAD

**Issue by welchwilmerck** [elastic/ansible-elasticsearch#235]
ansible-playbook times out waiting for service to start. Service won't start because it's looking in a different place for jvm.options than this role configures.

This role removes jvm.options from 'default' (/etc/elasticsearch) in favor of /etc/elasticsearch/{{es-instance_name}}. See roles/elasticsearch/task/elasticsearch-conf.yml, lines 90-91 and lines 60-63.

Unfortunately, the /usr/share/elasticsearch/bin/elasticsearch in the ES repo doesn't seem to be es_instance_name aware. See lines 113-121.
elasticsearch |      5.1.2 | https://artifacts.elastic.co/packages/5.x/apt/ stable/main amd64 Packages

Tried adding ES_JVM_OPTIONS to play to no avail:

    environment:
      ES_JVM_OPTIONS: "/etc/elasticsearch/{{es_instance_name}}/jvm.options"

**Comment by gingerwizard** [comment]
@welchwilmerck the 5.x branch is void. master is now 5.x

**Comment by gingerwizard** [comment]
> Can't work around by setting and exporting ES_JVM_OPTIONS. Exports don't seem to pass through Ubuntu's start-stop-daemon.

This shouldn't happen. Investigating why this isn't passed down.

**Comment by gingerwizard** [comment]
This was resolved in https://github.com/elastic/elasticsearch/pull/21445

**Comment by welchwilmerck** [comment]
Updated comment to remove distraction about how commandline administration works. The key here is that this role doesn't result in a running ES, even after switching to master branch and starting over with completely new instances.

**Comment by gingerwizard** [comment]
This https://github.com/elastic/ansible-elasticsearch/pull/234 hasn't been merged. This will resolve these issues when it is merged.  Currently master is dev only and not ready for usage.  Expect it to be merged this week. A few tests are not passing due to ansible's handling of vars.

**Comment by gingerwizard** [comment]
https://github.com/elastic/ansible-elasticsearch/pull/234 has been merged. Resolves this. Thanks for reporting @welchwilmerck
