### ISSUE TITLE
Ansible galaxy role not pulling down latest 5.x changes

### ISSUE THREAD

**Issue by strootman** [elastic/ansible-elasticsearch#236]
From the [Push to GitHub section](https://galaxy.ansible.com/intro#role-github), scroll down to `Versions`:

> If you applied any tags to your repository, Galaxy will automatically display a “version” for each tag. This means users can choose the version (tag) to download.

Currently, the [elastic/elasticsearch role](https://galaxy.ansible.com/elastic/elasticsearch/) on Ansible Galaxy is pulling down the `0.2` tag.

> The default behavior, if there are no tags, is to make the “HEAD” version available. This means users downloading the role will always get the latest from the github repository.

So, if you want the Galaxy role to pull down latest, you will have to tag appropriately.

**Comment by gingerwizard** [comment]
Latest 5.x changes haven't been merged. See https://github.com/elastic/ansible-elasticsearch/pull/234. Some outstanding test fixes.

0.2 tag is the latest and works against 2.x only. Once we have resolved the multi tests above we'll merge and update the role on galaxy.

**Comment by strootman** [comment]
Ok, I didn't realize it was intentional. 
I've seen other people make the same mistake (myself included).

**Comment by gingerwizard** [comment]
@strootman 5.x merged into master. We'll update the role in galaxy.

**Comment by strootman** [comment]
To recap, the following Ansible-Galaxy installation command will default to the `0.2` version:

    % mkdir tmp && cd tmp
    % ansible-galaxy install --roles-path . elastic.elasticsearch
    - downloading role 'elasticsearch', owned by elastic
    - downloading role from https://github.com/elastic/ansible-elasticsearch/archive/0.2.tar.gz
    - extracting elastic.elasticsearch to ./elastic.elasticsearch
    - elastic.elasticsearch (0.2) was installed successfully

However, as a  _**work around**_ you can install the latest by specifying the version:

    % ansible-galaxy install --roles-path . --force elastic.elasticsearch,master
    - changing role elastic.elasticsearch from 0.2 to master
    - downloading role 'elasticsearch', owned by elastic
    - downloading role from https://github.com/elastic/ansible-elasticsearch/archive/master.tar.gz
    - extracting elastic.elasticsearch to ./elastic.elasticsearch
    - elastic.elasticsearch (master) was installed successfully

**Comment by strootman** [comment]
With regard to how tags are used for versioning, I think it would be clear and consistent to mimic the scheme from the [elasticsearch repo](https://github.com/elastic/elasticsearch). For example, the current master (32c7a13b69db2b29e5c767ef668a61201d091aae) could be tagged with `v5.1.2`.

**Comment by TomasDuda** [comment]
Ansible Galaxy is still pointing to tag 0.2.

**Comment by strootman** [comment]
@TomasDuda I have started overriding the default version in my dependencies and Ansible Galaxy `requirements.yml` file.

**Comment by jakommo** [comment]
@gingerwizard can you have a look please?

**Comment by davidak** [comment]
@gingerwizard ping

**Comment by lobsterdore** [comment]
Can you cut a new version? Pointing to the master of a Git repo is less than ideal.

**Comment by davidak** [comment]
They told me on Twitter they will look at it: https://twitter.com/elastic/status/859877047258062849

But still nothing happened. Ansible seams to have no priority.

**Comment by strootman** [comment]
@lobsterdore @davidak 
https://docs.ansible.com/ansible/galaxy.html#id7

If you know the commit hash you want to target, you won't need to wait for a tag.

Though, I'd prefer a tag which matched the Elastic-Stack version, https://github.com/elastic/ansible-elasticsearch/issues/236#issuecomment-282493221

**Comment by davidak** [comment]
@strootman thanks for your response.

So can you create a tag and push to galaxy?

**Comment by strootman** [comment]
@davidak no, I can't.
My point is, whether you install the role, there are options to specify commit hashes instead of tags.

**Comment by davidak** [comment]
@strootman yes, but i want a stable commit and you know best which one that is.
What is the problem to create a tag? Is it not ready for a stable 5.x release?

**Comment by strootman** [comment]
@davidak if I were a maintainer, there would be a tag. 
It is not my intent to cause frustrations, I'm trying to be helpful :man_shrugging:

**Comment by davidak** [comment]
@strootman ok, i thought you where related to this project. nevermind

I will try the current commit and wait for some maintainer to add a tag.

**Comment by strootman** [comment]
@davidak 
This works in an Ansible Galaxy `requirements.yml` file:

    - src: git@github.com:elastic/ansible-elasticsearch.git                                                                                                                                                            
      name: elastic.elasticsearch                                                                                                                                                                                      
      scm: git
      version: 8002829bbe8f6fa43699a1bd32cb86a59000e349

**Comment by gingerwizard** [comment]
I've returned to working on this role after some absence. I appreciate the pain here and apologise this wasn't addressed. Before i cut a new release for 5.5.1 i'd like to close a few other issues. At that point i will point the galaxy role at the specific version. From there moving forward, we'll aim to always cut a release and ensure they are lock step.

**Comment by gingerwizard** [comment]
Tagged 5.5.1 and updated in galaxy. Will release 5.5.2 shortly - adding support for --check flag.  https://github.com/elastic/ansible-elasticsearch/issues/242 and issues with locking.
