### ISSUE TITLE
Failing on Ubuntu 14.x - TASK [elastic.elasticsearch : Debian - Ensure Java is installed]

### ISSUE THREAD

**Issue by codereviewvideos** [elastic/ansible-elasticsearch#237]
Hi, 

Firstly, thanks for this role, it is a very valuable time saver for me which I truly appreciate.

Just as a heads up, I was struggling with this issue:

https://github.com/elastic/ansible-elasticsearch/issues/233

So, I pulled down the latest master branch (#72ba86d) as suggested in that ticket, which got me past the issue, but another arose - `openjdk-8-jre-headless` doesn't appear to be a valid package for Ubuntu 14.x.

In my instance, this was for a new server so I have been able to upgrade to Ubuntu 16 LTS and that resolves the problem. Others may not have that as an option.

At a guess, is a solution here to set a variable of `es_java: "openjdk-8-jre"` ? 

thanks

Chris

**Comment by ShakataGaNai** [comment]
The other option is to modify vars/Debian.yml and change "openjdk-8-jre-headless" to "openjdk-7-jre-headless". Granted v7 isn't recommended but should (?) work. OpenJDK8 isn't ported back to 14.04 and looks like it probably never will.

**Comment by rozling** [comment]
Just out of curiosity, is there any reason not to install the Oracle JDK 8 for use with Elasticsearch?

**Comment by jakommo** [comment]
> Just out of curiosity, is there any reason not to install the Oracle JDK 8 for use with Elasticsearch?

no, that's absolutely fine.

> The other option is to modify vars/Debian.yml and change "openjdk-8-jre-headless" to "openjdk-7-jre-headless". Granted v7 isn't recommended but should (?) work

This depends on the Elasticsearch version you are installing. >=5.0 requires Java 8, on 2.x Java 7 also works, but Java 8 is recommended.

> OpenJDK8 isn't ported back to 14.04 and looks like it probably never will.

Yes, this is a problem with 5.x (which is currently in master) on 14.04. As ubuntu does not provide a Java 8 in the official repos, it's up to the user if he wants to solve this by a ppa with a backport or by using Oracle Java 8.

**Comment by gingerwizard** [comment]
Closing this as i think the larger discussion is how we handle java. See https://github.com/elastic/ansible-elasticsearch/issues/268
