### ISSUE TITLE
Copy default templates to elasticsearch

### ISSUE THREAD

**Issue by maulanasly** [elastic/ansible-elasticsearch#240]
Error when installation process on copying template:

> ERROR! The requested handler 'load-templates' was not found in either the main handlers list nor in the listening handlers list

**Comment by gingerwizard** [comment]
@maulanasly is this still reproducible? Can you confirm you are using master?

**Comment by vbarba** [comment]
same here. Do you use any specific config on your ansible.cfg file to handle the static include?

**Comment by gingerwizard** [comment]
Fixed. https://github.com/elastic/ansible-elasticsearch/pull/358
