### ISSUE TITLE
Separate Elastic repo/package installation into separate role

### ISSUE THREAD

**Issue by strootman** [elastic/ansible-elasticsearch#241]
Now that ES has consolidated its repositories, it would be beneficial to separate the task of configuring Redhat/Debian repos and installation by package into a separate role.

This role would then be used here via Ansible-Galaxy dependencies, you could still control execution of those tasks with tags and/or variables.

This kind of re-usability is what Ansible roles are meant for, and could be used for future Ansible roles for things like Beats, Logstash, or Kibana.

I'll issue a PR when I have something together, but wanted to mention it here to see if this would be desirable.

**Comment by drybjed** [comment]
For Debian/Ubuntu installation, you can check out [debops.elastic_co](https://galaxy.ansible.com/debops/elastic_co/) Ansible role.

**Comment by strootman** [comment]
@drybjed That is my first time seeing this! Looks like DebOps is your thing. I'll definitely be suggesting this to my colleagues!

**Comment by drybjed** [comment]
@strootman I'm finishing up a rewrite of the Elasticsearch role as well, should be ready this week.

**Comment by drybjed** [comment]
@strootman The new version of [debops.elasticsearch](https://github.com/debops/ansible-elasticsearch/) Ansible role is up, with [documentation](https://docs.debops.org/en/latest/ansible/roles/ansible-elasticsearch/docs/index.html), available also via [Ansible Galaxy](https://galaxy.ansible.com/debops/elasticsearch). Cheers. :-)

**Comment by gingerwizard** [comment]
Closing in favour of https://github.com/elastic/ansible-elasticsearch/issues/274
