### ISSUE TITLE
Restart of elasticsearch service after reboot fails if `es_user` is non-default

### ISSUE THREAD

**Issue by strootman** [elastic/ansible-elasticsearch#242]
I've reproduced this on CentOS and Ubuntu, systemd-supported OSs. Installation of elasticsearch was performed from the Elastic package repositories.

This is caused by improper ownership of the `/var/run/elasticsearch` directory, which is established via systemd [tmpfiles](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html). Specifically,

      % cat /usr/lib/tmpfiles.d/elasticsearch.conf
      d    /var/run/elasticsearch   0755 elasticsearch elasticsearch - -

If elasticsearch is installed with the default `elasticsearch` user, everything is fine.

It seems that the solution is to repeat the same pattern this role takes with the systemd service file, creating an instance specific version which maps to the `es_pid_dir`/`pid_dir` variables.

---
`templates/tmpfiles.d/elasticsearch.conf.j2`

      d    {{ pid_dir }}   0755 {{ es_user }} {{ es_group }} - -

`tasks/elasticsearch-config.yml`

      ...
      - name: Copy Tmpfiles.d File for Instance
        template: src=systemd/tmpfiles.d/elasticsearch.conf.j2 dest={{instance_tmpd_script}} mode=0644 force=yes
        when: use_system_d
      ...
      ## Optionally delete original file

**Comment by gingerwizard** [comment]
@strootman do you want to make a PR for this?
