### ISSUE TITLE
5.x: Debian: systemd service file not recognized

### ISSUE THREAD

**Issue by akhayyat** [elastic/ansible-elasticsearch#244]
If I use this role with `es_instance_name: instance1`, I end up with the systemd service file `/usr/lib/systemd/system/instance1_elasticsearch.service`.

This causes two problems:

1. Uninstalling via apt fails, because it tries to uninstall `/usr/lib/systemd/system/elasticsearch.service`, which does not exist (instance name prefix is missing from the filename). For apt to be able to uninstall the package, I must rename `/usr/lib/systemd/system/instance1_elasticsearch.service` to `/usr/lib/systemd/system/elasticsearch.service`.

2. Starting the service by this role fails, because it does not recognize the systemd service file. I must run `systemctl daemon-reload` and then start the service. I can fix this issue with the following patch (pull request ready; will submit if acceptable):

```diff
diff --git a/tasks/elasticsearch-Debian.yml b/tasks/elasticsearch-Debian.yml
--- a/tasks/elasticsearch-Debian.yml
+++ b/tasks/elasticsearch-Debian.yml
@@ -38,6 +38,10 @@
   when: not es_use_repository
   register: elasticsearch_install_from_package
 
+- name: Debian - Load elasticsearch systemd service
+  command: systemctl daemon-reload
+  when: elasticsearch_install_from_repo.changed or elasticsearch_install_from_package.changed
+
 # ansible uri module requires httplib2
 - name: python-httplib2
   apt: name=python-httplib2
```

**Comment by jakommo** [comment]
Hi @akhayyat thanks for raising this. 

For 1. I don't see a solution for this as the role does not provide a "decommission" aspect. I'm not sure if it's too much of a problem as I would imagine the role is used to setup machines and they are nuked if not used anymore anyway. 

For 2. good catch, I'm open to a PR. I would imagine that this is not a debian issue but a systemd thing in general, so I think it should be implemented that it applies to systemd in general, not just on debian.

**Comment by mdcroce** [comment]
Thanks @akhayyat! This worked!

**Comment by strootman** [comment]
For 1. This role deletes the original `elasticsearch.service` file. With systemd, another option could be to ensure that the original service is both stopped and masked.

    sudo systemctl mask elasticsearch

Or, since you depend on Ansible `v2.2.0`, you could use the [systemd module](https://docs.ansible.com/ansible/systemd_module.html)

    - when: use_system_d
      name: Ensure default service is masked
      systemd:
        name: elasticsearch
        state: stopped
        masked: yes
        daemon_reload: yes

**Comment by jakommo** [comment]
Thanks @strootman that sounds like a good approach. It will probably not be enough for a full decommission (as a lot of files/dirs will be created outside of the deb) but a good first step.

**Comment by pellenberger** [comment]
@akhayyat Thank you for you precisions, I was missing it !

About your changes, I'd propose to add tests in case the vars are undefined : 
```
- name: Debian - Load elasticsearch systemd service
  command: systemctl daemon-reload
  when: (elasticsearch_install_from_repo is defined and elasticsticsearch_install_from_repo.changed) or 
  (elasticsearch_install_from_package is defined and elasticsearch_install_from_package.changed)
```

**Comment by gingerwizard** [comment]
Issue 2 was solved with a PR and the service is now reloaded in the hander.  Support for decommissioning is to be discussed under https://github.com/elastic/ansible-elasticsearch/issues/277
