### ISSUE TITLE
Unable to install es plugins with the installed elasticsearch

### ISSUE THREAD

**Issue by dling** [elastic/ansible-elasticsearch#245]
The values in the 'bin/elasticsearch-plugin' appears to be incorrect when installed with this ansible playbook. The values such as '/etc/sysconfig/elasticsearch' etc needs to be replaced with the correct path using 'es_instance_name' variable etc.

**Comment by dling** [comment]
The values that needs to be updated via template are for CONF_DIR and ES_ENV_FILE.

**Comment by gingerwizard** [comment]
@dling its not clear what issue you are raising here. We don't touch elasticsearch-plugin ever.  This relies on reading the variables above which are set on invoking the command to the appropriate values - defined by the es_instance_name.  If you are trying to use the role to install plugins on a manual installed es instance this is not supported.

**Comment by jakommo** [comment]
I think its probably the same as https://github.com/elastic/ansible-elasticsearch/issues/58#issuecomment-238975418 ?

**Comment by gingerwizard** [comment]
Agreed there seems to be continued confusion as to the purpose of this role.  If you are using Ansible and use this role, DONOT ever touch the the server manually. The role restructures the folders to support multiple nodes.

If you are not using Ansible, refer to the main elasticsearch install guide.
