### ISSUE TITLE
failed in ubuntu 16 with below error

### ISSUE THREAD

**Issue by mkscala** [elastic/ansible-elasticsearch#247]
TASK [elasticsearch : set_fact] ************************************************
task path: /etc/ansible/roles/elasticsearch/tasks/elasticsearch-parameters.yml:26
fatal: [es-master-n1]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'default_file' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/elasticsearch/tasks/elasticsearch-parameters.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact: instance_default_file={{default_file | dirname}}/{{es_instance_name}}_{{default_file | basename}}\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}

**Comment by gingerwizard** [comment]
@mkscala can you provide your playbook? Are you defining es_instance_name. This is mandatory.

**Comment by gingerwizard** [comment]
No response closing. Cant reproduce.
