### ISSUE TITLE
Why is 'ansible-elasticsearch' not listed in the provided configuration management tools docs?

### ISSUE THREAD

**Issue by strootman** [elastic/ansible-elasticsearch#248]
https://www.elastic.co/guide/en/elasticsearch/reference/current/install-elasticsearch.html

`puppet-elasticsearch` and `cookbook-elasticsearch` are listed.

I've made a [PR against the docs](https://github.com/elastic/elasticsearch/pull/23058).

**Comment by jakommo** [comment]
Good catch, thanks @strootman

**Comment by jakommo** [comment]
Merged upstream, closing this.
