### ISSUE TITLE
Fix idempotence issue with certificates

### ISSUE THREAD

**Issue by ddidier** [elastic/ansible-elasticsearch#255]
in `tasks/java.yml` the following command always update the certificates, then there is always one "changed":

```
- name: refresh the java ca-certificates
  command: /var/lib/dpkg/info/ca-certificates-java.postinst configure
  when: ansible_distribution == 'Ubuntu' and open_jdk.rc == 0
```

**Comment by rusnyder** [comment]
I don't think this is accurate.  It's actually the command before this one that is always indicating "changed":

```
- command: java -version 2>&1 | grep OpenJDK
  register: open_jdk
```

I'd advocate the solution be to set ```changed_when: False``` since this is never actually performing any kind of change.

I'll put out a PR.

**Comment by gingerwizard** [comment]
Merged and backported through https://github.com/elastic/ansible-elasticsearch/pull/264
