### ISSUE TITLE
/usr/local/lib/python2.7/dist-packages/urllib3/contrib/socks.py:31: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies

### ISSUE THREAD

**Issue by chaica** [elastic/ansible-elasticsearch#258]
While running the job ansible-elasticsearch, I do have the following error message:

 ```
"module_stderr": "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/socks.py:31:
DependencyWarning: SOCKS support in urllib3 requires the installation of
optional dependencies: specifically, PySocks.
 For more information, see https://urllib3.readthedocs.org/en/latest/contrib.html#socks-proxies\n  DependencyWarning\nTraceback (most recent call last):\n 
File \"/tmp/ansible_xsqaD2/ansible_module_elasticsearch_shield_role.py\", line 237, in <module>\n    main()\n  File \"/tmp/ansible_xsqaD2/ansible_module_elasticsearch_shield_role.py\", line 211, in main\n    present, role = shield_role.get_role(name)\n  File \"/tmp/ansible_xsqaD2/ansible_module_elasticsearch_shield_role.py\", line 146, in get_role\n    url = urlparse.urljoin(self.elasticsearch_api, '/_shield/role/%s' % name)\nAttributeError: 'function' object has no attribute 'urljoin'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
```

It means (I guess) I do have to upgrade my urllib3 in order to manage Socks, which is quite difficult because it is the ubuntu package python-urllib3 and I do have a lot of dependencies on this package.

My question: is it mandatory to have this urllib3/contrib/socks.py or is it possible to deactivate its use by ansible-elasticsearch somehow?

**Comment by chaica** [comment]
my version of urllib3 is 1.7 and does not ship urllib3/contrib/socks.py

**Comment by jakommo** [comment]
@chaica which ansible version are you using and how does your playbook look like? 
> My question: is it mandatory to have this urllib3/contrib/socks.py or is it possible to deactivate its use by ansible-elasticsearch somehow?

I'm not sure if this is an issue with the role or with ansible itself.

**Comment by chaica** [comment]
sorry, that was not the blocking issue. Closing this one.
