### ISSUE TITLE
Replace -D with -E for proxy specification in x-pack installation

### ISSUE THREAD

**Issue by jdlourenco** [elastic/ansible-elasticsearch#259]
The x-pack installation [task ](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/xpack/elasticsearch-xpack-install.yml#L30) is still using the -D option sintax for configuring the proxy that seems to have been deprecated:

`{{es_home}}/bin/elasticsearch-plugin install --silent --batch x-pack {% if es_proxy_host is defined and es_proxy_host != '' %} -Dhttp.proxyHost={{ es_proxy_host }} -Dhttp.proxyPort={{ es_proxy_port }} {% endif %}`

I changed it to the following and it works:

`{{es_home}}/bin/elasticsearch-plugin install --silent --batch x-pack {% if es_proxy_host is defined and es_proxy_host != '' %} -Ehttp.proxyHost={{ es_proxy_host }} -Ehttp.proxyPort={{ es_proxy_port }} {% endif %}`

Best regards,
José Lourenço

**Comment by jdlourenco** [comment]
Is installing plugins behind a proxy even supported in 5.x?

It is not mentioned here https://www.elastic.co/guide/en/x-pack/5.0/installing-xpack.html

**Comment by strootman** [comment]
@jdlourenco Not obvious to find, but check out this link;

https://www.elastic.co/guide/en/elasticsearch/plugins/5.2/_other_command_line_parameters.html


I got there by searching for `plugins` in the [Elasticsearch Reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html), which brings you to the following link;

https://www.elastic.co/guide/en/elasticsearch/reference/5.2/modules-plugins.html

**Comment by jdlourenco** [comment]
Thanks for pointing that out @strootman

So I guess the line should be changed to:

`{% if es_proxy_host is defined and es_proxy_host != '' %} ES_JAVA_OPTS="-Dhttp.proxyHost={{ es_proxy_host }} -Dhttp.proxyPort={{ es_proxy_port }} -Dhttps.proxyHost={{ es_proxy_host }} -Dhttps.proxyPort={{ es_proxy_port }}" {% endif %} {{es_home}}/bin/elasticsearch-plugin install --silent --batch x-pack`

**Comment by strootman** [comment]
@jdlourenco Looks like you're ready for a PR! Then you would get the benefit of all the kitchen.ci tests if you don't want to run them locally.

**Comment by gingerwizard** [comment]
@jdlourenco feel free to make a PR. Looks like a valid issue. I suspect this isn't being tested on the jenkins infra so it slipped through. 
Let us know if you want to address or ill raise a PR.

**Comment by jdlourenco** [comment]
Is there any guide on testing the changes locally?

**Comment by gingerwizard** [comment]
@jdlourenco there isn't but i did consider adding a CONTRIB.md with instructions. I'll put some details together.

**Comment by gingerwizard** [comment]
im not sure how we actually test this. We'd need a proxy in the build env.  @dliappis do we still have one we can use? plugin installation for one of our tests could use.

**Comment by gingerwizard** [comment]
Merged closing.
