### ISSUE TITLE
Ansible still checks for startup when es_start_service is set to false

### ISSUE THREAD

**Issue by johnr-spindance** [elastic/ansible-elasticsearch#270]
When using `es_start_service: false`, ansible honors that but still tries to check that the elasticsearch service started...

```
RUNNING HANDLER [ansible-elasticsearch : restart elasticsearch] ****************
skipping: [52.90.61.249] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [34.207.192.229] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [54.225.14.85] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [ansible-elasticsearch : Wait for elasticsearch to startup] ***************
task path: /Users/johnr/src/bluescape/ansible-infrastructure/galaxy_roles/ansible-elasticsearch/tasks/main.yml:47
fatal: [54.225.14.85]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for localhost:9200"}
fatal: [52.90.61.249]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for localhost:9200"}
fatal: [34.207.192.229]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for localhost:9200"}
	to retry, use: --limit @/Users/johnr/.ansible-retry/efk_stack.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0
34.207.192.229             : ok=56   changed=16   unreachable=0    failed=1
52.90.61.249               : ok=56   changed=16   unreachable=0    failed=1
54.225.14.85               : ok=56   changed=16   unreachable=0    failed=1
```

**Comment by gingerwizard** [comment]
Nice catch thanks. Easily fixed - id like to include a test for this though.

**Comment by johnr-spindance** [comment]
@gingerwizard , would you like me to submit a PR from this on my forked branch? I am not as familiar with the testing stuff in this repo but would be willing to submit a fix for the issue.

**Comment by johnr-spindance** [comment]
@gingerwizard , please see https://github.com/elastic/ansible-elasticsearch/pull/275

Also, I'm curious about the difference between the two vars:

es_start_service
es_restart_on_change

They both have to be set to true in order for the service to restart or not. Was es_start_service meant to ensure that elasticsearch was started when installed and es_restart_on_change to restart only when there is a change?

**Comment by johnr-spindance** [comment]
@gingerwizard, any idea on when this could be reviewed or worked? I have a PR with comments asking me to merge this but I really don't have that kind of access here. You don't have to use my PR if you have a better fix for this.

**Comment by gingerwizard** [comment]
Apologies for the delay i stepped away from this role, but due to popular demand i will be returning as the maintainer.

In response to your question @johnr-spindance , yes i think that was the original intention of those switches. However, the logic has changed and one now seems redundant. I would like to longer term remove for something clearer - maybe in 6.x. They only serve the purpose now of clarify as i single switch might not be clear e.g. just `es_start_service` might not be clear as to how to stop ES from being bounced on changes.

Happy for to take input.
