### ISSUE TITLE
Proposed role re-factoring

### ISSUE THREAD

**Issue by strootman** [elastic/ansible-elasticsearch#274]
This discussion is an extension to #268.

The core functionality of this role should _always_ be the installation and management of one or more `elasticsearch` instances. However, with the introduction of `x-pack` management features, this role's task of _"installaing, configuring, and managing"_ an `elasticsearch` cluster is growing more and more complex.

That being said, I have a proposal for how this role could be re-factored to support not only `elasticsearch`, but the whole stack.

----

I have a role, which is still a **work in progress**, that I have been using for various _elastic-stack_ management purposes.
It may be used on its own, but is designed to be used as a dependency to other roles.

The intent of the role is to isolate package/binary installation tasks, as well as `configuration_file.yml` management into a single role which supports either default or multi-instance installation.
[CyVerse-Ansible.elastic-stack-install](https://galaxy.ansible.com/CyVerse-Ansible/elastic-stack-install/)

This role is used as a dependency in the [CyVerse-Ansible.beats](https://galaxy.ansible.com/CyVerse-Ansible/beats/) role, which I've been using to install/configure multiple beat agents on a single host (i.e. multiple `[TYPE]beat` instances).

While I am using these, I still consider them a *Work in Progress*, mostly due to inadequate testing and documentation.
 
My plan was to present these roles to you all when they were more complete :man_shrugging:. However, given the current activity in this role, I thought it prudent to bring it up.

Please take a look.

----

With respect to *this* role, extracting the installation steps could definitely help, but we could do a little more encapsulation.

This role can be split up into multiple roles. Each role would, as @barryib put it, _Do one thing, and do it well_.

I believe the two primary candidates for extraction would be;
1. Package/binary installation
  * I think you can see the benefit of extracting these tasks from this role can allow for Ansible management of the whole stack.
1. X-Pack

Thoughts?

@jakommo @gingerwizard @dliappis @barryib

**Comment by gingerwizard** [comment]
Lets discuss this for 6.x. Baring some details and how we split i'm in favour. Right now i'm focusing on getting the current role stable and issues resolved on 5.x. Ill post my thoughts on this split shortly but generally +1

**Comment by gingerwizard** [comment]
@strootman  this seems be aligned with this https://github.com/elastic/ansible-elasticsearch/issues/241

I'm going to close that in favour of this ticket.

@jpcarey this is what we were discussing. I would propose the following 4 roles for 6.x:

1. Installation of any Elastic Stack component e.g. ES, Filebeat,Kibana.
1. Configuration for each component. I'd propose we initially focus on just ES. i believe a lot of the complication stems from supporting multiple nodes on a box currently. We need to decide if this is something we support moving forward.
1. X-Pack support
1. Cluster wide operations e.g. rolling restarts

@strootman @barryib  @jakommo

**Comment by strootman** [comment]
I've been working with the multi-node per host, and it has its difficulties.
I think the role can be designed s.t. multi-node/host is supported, but the real trick is how to "draw the line in the sand" and communicate it effectively.

**Comment by strootman** [comment]
Modularizing the parts of the role can go a long way, especially with the Ansible's [include_role](https://docs.ansible.com/ansible/latest/include_role_module.html) module. But that is a longer term consideration.

**Comment by deroude** [comment]
Meanwhile would it be awfully complicated to add a variable such as "es_package_install" and condition the inclusion of elasticsearch.yml in main.yml on that variable? :) Cloud operation usually works with already built images that contain all the packages. The role is used in that case to configure each node as what it's supposed to be and start services. Thanks.
