### ISSUE TITLE
Decommissioning of elasticsearch instances?

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/ansible-elasticsearch#277]
Hello,
I've not been able to "remove" an Elasticsearch instance.
I tried to list specific tasks & tags, but there are none linked to this feature.

**Comment by gingerwizard** [comment]
This isn't currently supported. We would need a "remove_es" flag which overrides everything - probably using the current config to do a cleanup. Ideas @barryib @strootman @jakommo

**Comment by gingerwizard** [comment]
this is relevant if we implement this https://github.com/elastic/ansible-elasticsearch/issues/244#issuecomment-280761463

**Comment by strootman** [comment]
Like @jakommo said, a step toward implementing the feature.
