### ISSUE TITLE
Urls for configuration via HTTP API use http (but https could be required)

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/ansible-elasticsearch#278]
All internal calls to HTTP APIs use http while https could be necessary in case of ssl deployment.

**Comment by gingerwizard** [comment]
I'll merge https://github.com/elastic/ansible-elasticsearch/pull/302 tomorrow which should address

**Comment by gingerwizard** [comment]
Held of merging this as discussing whether we solve as part of SSL support. Probably 5.5.2

**Comment by abraxxa** [comment]
Any news on https support?

**Comment by kaneda-fr** [comment]
Is it only required for the API calls as part of the role ?

**Comment by abraxxa** [comment]
Yes

**Comment by jmlrt** [comment]
#500 was also created for the same feature request and had more activity. FYI we are working on it #479. I'm closing this one as duplicate.
