### ISSUE TITLE
Tracking of upstream changes needs reconsideration

### ISSUE THREAD

**Issue by jasontedor** [elastic/ansible-elasticsearch#285]
I came across #279. This pull request is concerning to me. Not because it is incorrect, it's not, but because it means that the jvm.options are not tracking upstream changes. The JVM option here is crucial for the stability of Elasticsearch, the fact that it's currently missing from Ansible-based deployments from this repository is awful for those end-users. There has to be a better way, but this is not a good situation. I'm sorry to be critical here. To be clear, it's not critical of #279, it's critical that this pull request is necessary, and that users of this Ansible role have been without this fix for almost three months.

**Comment by jpcarey** [comment]
It also appears the referenced pull is missing
+-Dio.netty.allocator.type=unpooled

**Comment by jasontedor** [comment]
We do not set that setting currently.

**Comment by gingerwizard** [comment]
@jasontedor this role indeed relies on us manually syncing the init, systemd, logging and jvm options file every time we release in ES. This is something we need to address as the role has just gone another 2-3 months without these files being updated. In the short term we can explicitly state on the README that this is the case - the role is only tested against and uses the files from version X of ES.
The largest concern is users use the role for a version greater than that it was tested/developed against. Whilst this might work they then don't benefit from changes to the above files - which maybe critical.

Possibly we could also error if the version is greater than a supported version or atleast warn, thus ensuring users atleast becoming aware they are not benefiting from the full benefits of an upgrade - potentially.

In the longer term we need to ensure this role is released reliably with ES versions - something beyond the scope of this ticket.

**Comment by abraxxa** [comment]
The version compatibility is discussed in #419
