### ISSUE TITLE
Documentation for license management written as if lookup runs on remote machines.

### ISSUE THREAD

**Issue by welchwilmerck** [elastic/ansible-elasticsearch#294]
In README.md, the procedure for adding a license blob is written as if lookup runs on remote machines. All lookups run only on the control machine.

Current documentation:

> es_xpack_license - X-Pack license. The license should be declared as a json blob. Alternative use Ansible vault or copy the license to the target machine as part of a playbook and access via a lookup e.g.

`es_xpack_license: "{{ lookup('file', '/tmp/license.json')  }}"`

How about:

> es_xpack_license - X-Pack license. The license should be declared as a json blob. Alternatively, use Ansible vault or place license file in a cluster-specific directory for files, .gitignore license files, and access via a lookup. For example: 

```
files/**
!files/your_prod_cluster1/**
!files/your_test_cluster2/**
# keep license files out of git
files/**/license.json
```
`es_xpack_license: "{{ lookup('file', playbook_dir + '/files/' + es_cluster_name + '/license.json')  }}"`

**Comment by barryib** [comment]
@welchwilmerck Can you please make an PR for this clarification?

**Comment by welchwilmerck** [comment]
#359

**Comment by gingerwizard** [comment]
Thanks
