### ISSUE TITLE
Add a way to use custom repositories or package source

### ISSUE THREAD

**Issue by srinathman** [elastic/ansible-elasticsearch#312]
Currently we have  "es_use_repository" variable and when it's set to yes, it will add the elastic repository and if it's not set it will try to download the package from the default URL or and customer defined URL.

We need an option that assumes that the repository will be defined elsewhere instead of trying to define it. Then it would just install the package.

A second option would be to assume the installation is done elsewhere and just do the configuration.
This is useful when installing from and internal mirror, for example.

**Comment by gingerwizard** [comment]
@srinathman what currently prevents you from overriding `es_apt_url`?

**Comment by srinathman** [comment]
We have a case were ES packages are already in another internal repository, which also contains other packages unrelated to ES.

**Comment by jmlrt** [comment]
@srinathman this is fixed by https://github.com/elastic/ansible-elasticsearch/pull/582
