### ISSUE TITLE
XPack License Warning at 

### ISSUE THREAD

**Issue by mattiblohm** [elastic/ansible-elasticsearch#313]
Hello,
i got that warning on an putting a license in the ES:

> "warning": "299 Elasticsearch-5.3.1-5f9cf58 \"[PUT /_license] is deprecated! Use [PUT /_xpack/license] instead.\" 

may corect it in future releases.

Greeting
Matthias

**Comment by gingerwizard** [comment]
Will be fixed under https://github.com/elastic/ansible-elasticsearch/pull/338

**Comment by gingerwizard** [comment]
https://github.com/elastic/ansible-elasticsearch/pull/361 closes
