### ISSUE TITLE
Elasticsearch startup times out on Centos 7 in Vagrant

### ISSUE THREAD

**Issue by tonyrush** [elastic/ansible-elasticsearch#315]
Using the simplest playbook that doesn't error out because the user must be root and the ansible_local provisioner:
---
- name: Simple Example
  hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - { role: elasticsearch, es_instance_name: "node1" } 
vars:

Fails with:

 [Wait for elasticsearch to startup] ***********************
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for localhost:9200"}
	to retry, use: --limit @/vagrant/simple.retry

PLAY RECAP *********************************************************************
localhost                  : ok=39   changed=19   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
s_instance_name: "node1" }

**Comment by rhinoman** [comment]
I'm seeing the same thing on CentOS 7 on Linode.  But elasticsearch *is* running according to systemctl status

**Comment by gingerwizard** [comment]
Reproducible on latest version of ES. Investigating.

**Comment by gingerwizard** [comment]
Addressed in https://github.com/elastic/ansible-elasticsearch/pull/366
