### ISSUE TITLE
need to install "jmespath" prior to running json_query filter

### ISSUE THREAD

**Issue by sangdrax8** [elastic/ansible-elasticsearch#321]
I am using Ubuntu 16LTS, and attempting to install a plugin with the ansible playbook results in an error about a missing python package. 

`
TASK [ansible-elasticsearch : set_fact] ******************************************************************************************************
fatal: [**********]: FAILED! => {"failed": true, "msg": "You need to install \"jmespath\" prior to running json_query filter"}
`

After installing python-jmespath on my local machine (where I run ansible) everything works.
`apt-get install python-jmespath`

I don't know if there is a way to ensure this is installed, or simply documentation stating required python packages that are above and beyond what is required to run ansible.

**Comment by bobcallaway** [comment]
also experiencing this error on amazon linux

**Comment by luisamador** [comment]
I have just come across this same issue on Ubuntu 16.04 LTS. I noticed that if the variable 'es_plugins_reinstall' is set to true 'es_plugins_reinstall: true' then Ansible runs without any problem (I am not saying this is a solution).

es_plugins_reinstall - defaults to false. If true, all currently installed plugins will be removed from a node. Listed plugins will then be re-installed.

**Comment by philipwigg** [comment]
Related - https://github.com/ansible/ansible/issues/24319

**Comment by gingerwizard** [comment]
We do indeed install this as a dependency for our tests e.g. https://github.com/elastic/ansible-elasticsearch/blob/master/.kitchen.yml#L31 as the tests run locally.

I think a comment in our README this is needed locally is probably sufficient. I added a note under https://github.com/elastic/ansible-elasticsearch/pull/362

**Comment by tb3088** [comment]
> also experiencing this error on amazon linux

The actual issue likely has to do with the 'Ansible' package (eg. RPM) itself. In Amazon Linux1 the EPEL version of the RPM has a hard dependency for Python 2.6. But if you update your system Python 2.7 will get installed. so while /usr/bin/python -> /etc/alternatives/pythong -> python27, /usr/bin/python2 likely still points to python2.6. Therefore you have to install the 2.6 version of the 'jmespath' module.

Alternatively fix /usr/bin/python2 to point to 2.7. Which begs the qeustion, why is Ansible apparently invoking 'python2' instead of just 'python'?

**Comment by DirectedSoul1** [comment]
> I am using Ubuntu 16LTS, and attempting to install a plugin with the ansible playbook results in an error about a missing python package.
> 
> `TASK [ansible-elasticsearch : set_fact] ****************************************************************************************************** fatal: [**********]: FAILED! => {"failed": true, "msg": "You need to install \"jmespath\" prior to running json_query filter"}`
> 
> After installing python-jmespath on my local machine (where I run ansible) everything works.
> `apt-get install python-jmespath`
> 
> I don't know if there is a way to ensure this is installed, or simply documentation stating required python packages that are above and beyond what is required to run ansible.

on RHEL we can use `yum install python3-jmespath`
