### ISSUE TITLE
Startup scripts require systemd for Red Hat 7

### ISSUE THREAD

**Issue by olbonc01** [elastic/ansible-elasticsearch#327]
To get this to work on Red Hat 7, I had to change line 44 in elasticsearch-parameters.yml to:

- set_fact: use_system_d={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}

**Comment by rbu** [comment]
Seems this is a duplcate of #249 / #250. Are you on logstash 2?

**Comment by olbonc01** [comment]
Not on Logstash.

Clay Olbon
Accenture | Advanced Technology & Architecture

**Comment by gingerwizard** [comment]
This was addressed as pointed out above. Closing.
