### ISSUE TITLE
Unknown setting [ES_USER]

### ISSUE THREAD

**Issue by gregbkr** [elastic/ansible-elasticsearch#329]
Hello,

I tried to install/run elasticsearch 5.4.1 with xpack 5.4.1 as a different user than root.
I got this error message:
`Suppressed: java.lang.IllegalArgumentException: unknown setting [ES_USER] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.4.1.jar:5.4.1]`

my /etc/elasticsearch/elasticsearch.yml : 
```
cluster.name: staging
node.name: ${HOSTNAME}

ES_USER: es01
ES_GROUP: es01
...
```

I can't understand what is wrong...
Can't find the doc for 5.4.1 but these settings seem right in https://www.elastic.co/guide/en/elasticsearch/reference/2.1/setup-service.html

Thank you for your help!
Greg

**Comment by jpcarey** [comment]
`ES_USER` & `ES_GROUP` do not go into the elasticsearch.yml. Those are used typically in the startup script that starts the elasticsearch process.
