### ISSUE TITLE
Ansible dry run (--check) fails due to missing variables

### ISSUE THREAD

**Issue by sangdrax8** [elastic/ansible-elasticsearch#330]
Running a "dry run" with ansible fails because some variables are not populated in check mode making other tasks error.  This can be fixed by setting those commands which populate varaibles used by other tasks (and are them self safe to always run) with check_mode: no.  The following diff's are what I needed to fix in my install, but there could be others like them in sections that I am not using

```
diff --git a/tasks/elasticsearch-plugins.yml b/tasks/elasticsearch-plugins.yml
index 8ec9e25..7d764af 100644
--- a/tasks/elasticsearch-plugins.yml
+++ b/tasks/elasticsearch-plugins.yml
@@ -16,6 +16,7 @@
   register: installed_plugins
   changed_when: False
   ignore_errors: yes
+  check_mode: no
   environment:
     CONF_DIR: "{{ conf_dir }}"
     ES_INCLUDE: "{{ instance_default_file }}"
diff --git a/tasks/java.yml b/tasks/java.yml
index c0c63b8..990899a 100644
--- a/tasks/java.yml
+++ b/tasks/java.yml
@@ -21,6 +21,7 @@
 - shell: java -version 2>&1 | grep OpenJDK
   register: open_jdk
   ignore_errors: yes
+  check_mode: no
   changed_when: false
```

**Comment by gingerwizard** [comment]
@sangdrax8 i'm trying to ensure the role works with `--check` .  Some tasks generate variables which are subsequently used, yet they perform state changing actions. For example,

https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-Debian.yml#L27

Fails in dry run mode if the elasticsearch repo is not added in the previous task. I can set this previous tasks to dry_run but this seems to somewhat defeat the purpose.

Furthermore, 

https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-plugins.yml#L50

fails as it checks its own output via` plugin_installed.rc`.  This command can't be set to `check_mode:no` as it makes state changing actions are relies on ES being instanced. Where you able to overcome these issues?

**Comment by gingerwizard** [comment]
I think we can aspire to supporting check mode on the 2nd run but im not convinced its going to be possible on the 1st run.

**Comment by gingerwizard** [comment]
I think we can support --check even on the 1st run. For the first problem we can simply skip the installation if the repo is not installed - an additional check is required. The alternative was to set the apt_respository task to `check_mode: no`, which seemed to defeat the purpose somewhat.

For the plugin task we can do similar - confirm ES is installed before executing the commands. This should avoid the failure of plugin installation if --check is run on the 1st installation.

This approach can be re used elsewhere and ill test accordingly before making a PR.

**Comment by maharg101** [comment]
@gingerwizard I used this approach for the elasticsearch-Debian.yml:

```
*** elasticsearch-Debian.yml.dist	2018-10-15 10:27:10.000000000 +0100
--- elasticsearch-Debian.yml	2018-10-15 10:29:30.000000000 +0100
***************
*** 41,54 ****
      service:
        name: '{{ instance_init_script | basename }}'
        state: stopped
!     when: elasticsearch_package.stdout == 'install ok installed'

    - name: Debian - Remove elasticsearch package if we are installing the oss package
      become: yes
      apt:
        name: 'elasticsearch'
        state: absent
!     when: elasticsearch_package.stdout == 'install ok installed'

  - name: Debian - Ensure elasticsearch is installed
    become: yes
--- 41,58 ----
      service:
        name: '{{ instance_init_script | basename }}'
        state: stopped
!     when:
!       - elasticsearch_package.stdout is defined
!       - elasticsearch_package.stdout == 'install ok installed'

    - name: Debian - Remove elasticsearch package if we are installing the oss package
      become: yes
      apt:
        name: 'elasticsearch'
        state: absent
!     when:
!       - elasticsearch_package.stdout is defined
!       - elasticsearch_package.stdout == 'install ok installed'

  - name: Debian - Ensure elasticsearch is installed
    become: yes
```
