### ISSUE TITLE
Default File Incorrect "/etc/sysconfig/elasticsearch"

### ISSUE THREAD

**Issue by jyoukers** [elastic/ansible-elasticsearch#334]
In "elasticsearch/vars/RedHat.yml", the variable "default_file: "/etc/sysconfig/elasticsearch"" is inconsistent with what is actually created. After Elasticsearch is installed, the file created is actually dependent on the "es_instance_name: "node1"" value in the .yml file being run.

For instance, if the es_instance_name value is "node1", the file created is actually:
/etc/sysconfig/node1_elasticsearch

**Comment by gingerwizard** [comment]
This is as intended to support multi node deployments @jyoukers
