### ISSUE TITLE
Support for multi-instance install

### ISSUE THREAD

**Issue by visaxin** [elastic/ansible-elasticsearch#337]
1. play-book can specify N instance on one hosts with different http.port and data/logs path
2. support install not using apt-get, may be using a http-get a elastic.tar.gz and export it.

**Comment by jakommo** [comment]
HI @visaxin,

1. is already in place, see [this example](https://github.com/elastic/ansible-elasticsearch#multi-node-server-installations)
2. I don't think this will happen as it would require a complete redesign of the role and I don't see what advantage this should have.
