### ISSUE TITLE
readme bug: version parameters are in "vars" not in "es_config"

### ISSUE THREAD

**Issue by amitron72** [elastic/ansible-elasticsearch#343]
here: 
https://github.com/elastic/ansible-elasticsearch/blob/master/README.md#additional-configuration
is says that the es_version and es_major_version are in es_config :

> **Additional parameters to es_config** allow the customization of the Java and Elasticsearch versions, in addition to role behaviour. Options include:
> 
> es_major_version (e.g. "5.1" ). Should be consistent with es_version. For versions >= 5.0 this must be "5.x".
> es_version (e.g. "5.1.2").

**Comment by gingerwizard** [comment]
I'll reword. It should read "In addition to es_config, the following parameters...."

Also there is a mistake on e.g. 5.1. It should be 5.x

**Comment by gingerwizard** [comment]
Resolved under https://github.com/elastic/ansible-elasticsearch/pull/365
