### ISSUE TITLE
Need to remove default.path.home on starting from version 5.4

### ISSUE THREAD

**Issue by carlosfunk** [elastic/ansible-elasticsearch#349]
Ran in to this today upgrading from 5.2...

java.lang.IllegalArgumentException: unknown setting [default.path.home]

https://www.elastic.co/guide/en/elasticsearch/reference/5.4/breaking-changes-5.4.html#breaking_54_settings_changes

**Comment by gingerwizard** [comment]
Closed by https://github.com/elastic/ansible-elasticsearch/pull/358
