### ISSUE TITLE
Confusing README.md

### ISSUE THREAD

**Issue by GoodMirek** [elastic/ansible-elasticsearch#367]
**Elasticsearch version**
5.5.2

**Role version**:  (If using master please specify github sha)
ea5a373155e96dfc4941b2bec3920e7f76eb28de

**JVM version** (`java -version`):
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
uname -a
Linux ubuntu1 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behaviour**:
Following examples in https://github.com/elastic/ansible-elasticsearch/blob/master/README.md are confusing, as plugin `elasticsearch-cloud-aws` does not exist in 5.5.2.
```
  es_plugins:
    - plugin: elasticsearch-cloud-aws
```

**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

**ES Logs if irrelevant**:

**Comment by gingerwizard** [comment]
Agreed ill tidy up the README and make a PR now

**Comment by gingerwizard** [comment]
Closed by https://github.com/elastic/ansible-elasticsearch/pull/376
