### ISSUE TITLE
"apt-get remove" fails due to a wrong service name configured in pre-remove hook

### ISSUE THREAD

**Issue by kamax7C0** [elastic/ansible-elasticsearch#372]
**Elasticsearch version**: 5.5.2

**Role version**:  5.5.1

**JVM version**: Oracle JDK8

**OS version** (`uname -a` if on a Unix-like system): Linux 3.16.0-4-amd64 #1   SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

**Description of the problem including expected versus actual behaviour**:
The installation of an Elasticsearch cluster is flawless, but when trying to remove the elasticsearch from the server with "sudo apt-get remove --purge elasticsearch" the following error occurs: 
_Entfernen von elasticsearch (5.5.2) ...
Stopping elasticsearch service...Failed to stop elasticsearch.service: Unit elasticsearch.service not loaded. 
dpkg: Fehler beim Bearbeiten des Paketes elasticsearch (--purge):
Unterprozess installiertes pre-removal-Skript gab den Fehlerwert 5 zurück_
Sry for German, but, in the end it complains about the absence of the "elasticsearch.service" , which is configured in "/var/lib/dpkg/info/elasticsearch.prerm" and which is correct, because I have a clustered installation, where the master's service name is automatically "node1.elasticsearch.service"

**Playbook**:
Please specify the full playbook used to reproduce this issue.
# Playbook to install the ES Cluster
- hosts: es_master_node
  remote_user: elk
  sudo: yes
  vars:
    favcolor: blue
  vars_files:
    - group_vars/all.yml
  roles:
    - role: commons
    - {role: ansiblebit.oracle-java, oracle_java_set_as_default: yes, ansible_distribution: 'Debian'}
    - {role: elastic.elasticsearch, es_instance_name: "node1", es_heap_size: "2g", es_java_install: false, es_api_host: "{{ansible_hostname}}",
    es_config: {
        cluster.name: "es-staging",
        discovery.zen.ping.unicast.hosts: "{{ansible_hostname}}:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: true,
        bootstrap.memory_lock: false,
        network.host: "{{ansible_hostname}}"
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: elk

**Comment by gingerwizard** [comment]
Thanks @kamax7C0 currently we don't support decommissioning but its come up https://github.com/elastic/ansible-elasticsearch/issues/277


https://github.com/elastic/ansible-elasticsearch/issues/244#issuecomment-280761463 was the proposed solution i.e. we mask the old service. I think its a good idea and probably worth adding. I'll work on a PR but its unlikely we will support a full decomission.
