### ISSUE TITLE
Issues when the inventory_hostname changes 

### ISSUE THREAD

**Issue by ServerNinja** [elastic/ansible-elasticsearch#384]
**Elasticsearch version**: 5.2.2

**Role version**:  `7714c925e06e8538a09b6e9d8c1bd074813e9639`

**JVM version** (`java -version`): `OpenJDK Runtime Environment (build 1.8.0_121-b13)`

**OS version** (`uname -a` if on a Unix-like system): (CentOS 7.3)
```Linux ip-192-168-0-145.common.bluescape.local 3.10.0-514.6.2.el7.x86_64 #1   SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```

**Description of the problem including expected versus actual behaviour**:

We had a situation where the inventory_name had changed from ansible's perspective, which caused the es_data_dirs to change the location of the data directory.

What happened:

For the affected node, the elasticsearch data was originally located in `/var/lib/elasticsearch/54.152.101.73-dev`, which was originally created by elasticsearch when the elasticsearch.yml.j2 template from this role populated the paths as such:

```
#################################### Paths ####################################

# Path to directory containing configuration (this file and logging.yml):
path.conf: /etc/elasticsearch/dev

path.data: /var/lib/elasticsearch/54.152.101.73-dev

path.logs: /opt/elasticsearch/logs/54.152.101.73-dev
```

When a change occurred with the elasticsearch instance in AWS which resulted in a different instance_hostname being reported from the AWS dynamic discovery, a new directory created after running the ansible playbook and elasticsearch was restarted. This new directory had been created and elasticsearch believed that it had lost all its shards on that node: `/var/lib/elasticsearch/192.168.0.145-dev`. 

This actually caused an outage where the elasticsearch cluster was in a "red" state until we discovered what had happened with the path.data change that the ansible-elasticsearch role had made in elasticsearch.yml. Fortunately, no data was lost.

In looking through the code to find out how this had happened, I saw that the `es_data_dirs` variable in ansible was being populated with information about the `inventory_hostname`, which seems to have caused this problem. 

https://github.com/elastic/ansible-elasticsearch/blob/7ab416c782f0a0d90430d1863150d405c1efdc3b/tasks/elasticsearch-parameters.yml#L51-L56

In the code from the link above, there is a comment on line 51 saying `#For directories we also use the {{inventory_hostname}}-{{ es_instance_name }} - this helps if we have a shared SAN.`

I'm not sure that this applies to all elasticsearch clusters by default. However this should either be changed or maybe defaulted to something else with the option for using a shared SAN. The problem at hand is that when using dynamic discovery, this value does have the potential to change from time to time. 

I would recommend using the `es_instance_name` by default and have a switch one could flip to append hostnames or unique names if using shared storage. I'm can imagine that it is not a recommended practice to use shared storage for your nodes in an elasticsearch cluster as it would be a single point of failure.

**Playbook**:
```
- hosts:
    - 'elastic_dev_nodes'
  become: true

  pre_tasks:
    - include_vars:
        dir: ../../group_vars/vagrant

    - name: Build Elasticsearch Cluster Config
      set_fact:
        efk_percent_heap: .8
        es_config:
          node.name: "elastic-dev-1"
          network.host: '0.0.0.0'
          cluster.name: "elastic-dev"
          http.port: '9200'
          transport.tcp.port: '9300'
          node.data: true
          node.master: true

  roles:
    - { role: ansible-elasticsearch,
        es_instance_name: "dev",
        es_use_repository: false,
        es_custom_package_url: 'https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.2.rpm',
        es_heap_size: '{{ (ansible_memtotal_mb * efk_percent_heap)|round|int|string }}m',
      }
```

**Comment by johnr-spindance** [comment]
Referencing PR: https://github.com/elastic/ansible-elasticsearch/pull/386
