### ISSUE TITLE
instead of running node1_elasticsearch i need it as default elasticsearch

### ISSUE THREAD

**Issue by virinche** [elastic/ansible-elasticsearch#388]
<!

**Describe the feature**:

**Elasticsearch version**

**Role version**:  (If using master please specify github sha)

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behaviour**:

**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

**ES Logs if irrelevant**:

**Comment by Crazybus** [comment]
Closing in favour of #354 . For what it is worth I really want to make this the default too. Most of the complexity in this playbook comes from supporting multiple instances on a single machine. While it won't be possible to fully remove the multiple instances requirement it should only be enabled for users actually using it 👍
