### ISSUE TITLE
Function to create keystore from ansible role.

### ISSUE THREAD

**Issue by usrlocalsbin** [elastic/ansible-elasticsearch#396]
<!

**Describe the feature**:

Now that s3 and aws auth is mandatory in keystore it would be nice to have the functionality from within ansible. 

**Elasticsearch version**
>= 5.6

**Role version**:  (If using master please specify github sha)
2.x

**JVM version** (`java -version`):
1.8

**OS version** (`uname -a` if on a Unix-like system):
Rhel 7
**Description of the problem including expected versus actual behaviour**:

**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

**ES Logs if irrelevant**:

**Comment by jmlrt** [comment]
This was implemented in https://github.com/elastic/ansible-elasticsearch/commit/e5809a3169a72a0a0c29f5ebea62a25868b6a6bb
