### ISSUE TITLE
Document ansible-galaxy way of installing role

### ISSUE THREAD

**Issue by janhoy** [elastic/ansible-elasticsearch#398]
**Describe the feature**:

I guess it is best practice to install the role from Galaxy (`ansible-galaxy install elastic.elasticsearch`) keeping the role link in a `roles.yml` file, instead of cloning the Git repo.

This is mainly a documentation issue...

**Comment by jmlrt** [comment]
Hi @janhoy,
Sorry for the late answer.
Ansible Galaxy instructions are in the README now.
