### ISSUE TITLE
Feature Request: Readonlyrest

### ISSUE THREAD

**Issue by teadur** [elastic/ansible-elasticsearch#410]
Describe the feature:

As of X-pack is quite expensive for small install maybe someone would be willing to support
readonlyrest plugin with this role so that people could use basic auth easily.

Reading from the docs, it seems it would solve https problem aswell mentioned in elastic/ansible-elasticsearch#409 

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin

**Comment by jmlrt** [comment]
Hi @teadur,
Sorry for the very late answer.
Authentication is now [free with Basic tier](https://www.elastic.co/blog/security-for-elasticsearch-is-now-free).
In addition, while you can manually install Readonlyrest plugin on Elasticsearch nodes deployed with this Ansible role. We will not include support for tiers plugin inside the role.
