### ISSUE TITLE
(node1_elasticsearch) is actually an init script but the system is managed by systemd

### ISSUE THREAD

**Issue by pavolloffay** [elastic/ansible-elasticsearch#418]
(node1_elasticsearch) is actually an init script but the system is managed by systemd

**Elasticsearch version**

**Role version**:  (If using master please specify github sha)
d7a5af8

**JVM version** (`java -version`):
```
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
`Linux dhcp-10-40-1-69.brq.redhat.com 4.13.16-100.fc25.x86_64 #1   SMP Mon Nov 27 19:52:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behaviour**:

**Playbook**:
Please specify the full playbook used to reproduce this issue.
```
- name: Simple Example
  hosts: localhost
  roles:
    - { role: elasticsearch, es_instance_name: "node1" }
```

**Provide logs from Ansible**:
```
TASK [elasticsearch : Copy message auth key to elasticsearch] ********************************************************************************************************************************
skipping: [localhost]

TASK [elasticsearch : Ensure security conf directory exists] *********************************************************************************************************************************
skipping: [localhost]

TASK [elasticsearch : Set Plugin Directory Permissions] **************************************************************************************************************************************
changed: [localhost]

TASK [elasticsearch : Set elasticsearch.keystore Permissions] ********************************************************************************************************************************
skipping: [localhost]

RUNNING HANDLER [elasticsearch : restart elasticsearch] **************************************************************************************************************************************
 [WARNING]: The service (node1_elasticsearch) is actually an init script but the system is managed by systemd

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Service is in unknown state", "status": {}}
	to retry, use: --limit @/home/ploffay/tmp/es-ansible/playbook2.retry

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=38   changed=15   unreachable=0    failed=1  
```

**ES Logs if irrelevant**:

**Comment by Crazybus** [comment]
Hi Pavol,

The problem seems to be that Fedora Core 25 is not currently supported by this playbook. It also isn't a [supported platform](https://www.elastic.co/support/matrix) for elasticsearch.

The first issue (which you are hitting) is that the [playbook decides](https://github.com/elastic/ansible-elasticsearch/blob/d7a5af8c33c5adb3aeff5d9e2caba2e2f853cd4d/tasks/elasticsearch-parameters.yml#L47) whether or not to use systemd based on the `ansible_distribution` and `ansible_distribution_version`

```
- set_fact: use_system_d={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}
```

You could try setting something like `or (ansible_distribution == 'Fedora' and ansible_distribution_version | version_compare('25', '>='))`.

**Comment by sustacek** [comment]
Hello @Crazybus, I've stumbled upon the same, but using Amazon Linux 2 (supported for ES).

Could you please describe how I could force the role to recognize the OS as a "systemd one"? I'm installing ES using ansible-playbook call and local connection, if that helps. Thanks in advance.
