### ISSUE TITLE
permission denied for elasticsearch

### ISSUE THREAD

**Issue by karthik-KSK** [elastic/ansible-elasticsearch#424]
karthikksk@E460:/usr$ cd ..
karthikksk@E460:/$ cd usr/share/elasticsearch
karthikksk@E460:/usr/share/elasticsearch$ bin/elasticsearch
bin/elasticsearch-env: line 70: /etc/default/elasticsearch: Permission denied
karthikksk@E460:/usr/share/elasticsearch$ bin/elasticsearch-plugin install x-pack
bin/elasticsearch-env: line 70: /etc/default/elasticsearch: Permission denied

**Comment by andyshinn** [comment]
It looks like this may be an issue with Elasticsearch 6.2. In 6.1 the `elasticsearch-env` file has:

```
if [ -f /etc/default/elasticsearch ]; then source /etc/default/elasticsearch; fi
```

But in 6.2 it is just:

```
source /etc/default/elasticsearch
```

The `/etc/default/elasticsearch` file doesn't exist because we remove it at use a custom named one instead.

**Comment by andyshinn** [comment]
I think this is now fixed in 6.2.2 by #431.

**Comment by Crazybus** [comment]
It is indeed. Thanks @andyshinn!

**Comment by weyderfs** [comment]
I think that not fix, I'm using the latest ELK version on Ubuntu Server 18.04 installed by repositories and happened this issue...
