### ISSUE TITLE
Service not starting and Task for Plugins fails after adapting "es_version" to the actual 6.2.1

### ISSUE THREAD

**Issue by xtruthx** [elastic/ansible-elasticsearch#426]
<!

**Describe the feature**:

**Elasticsearch version**
6.2.1

**Role version**:   latest master(If using master please specify github sha)

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system): 

3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Derived from Red Hat Enterprise Linux 7.4 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core) 
CentOS Linux release 7.4.1708 (Core) 

**Description of the problem including expected versus actual behaviour**:
If i change the default var for the ES Version to the latest 6.2.1 then the Tasks related to plugins are failing and the elasticsearch service is not starting.
I figured out that the problem is after changing version from 6.1.3 to 6.2.1 that the following will not be adapted in /usr/share/elasticsearch/bin/elasticsearch-env:

```
...
export HOSTNAME=$HOSTNAME

source /etc/sysconfig/elasticsearch
...
```
The role requires a instance_name and the sysconfig file will be deployed as "/etc/sysconfig/instancename_elasticsearch"

What is the best way to fix that or better was cause it. I can find the right parts. I already thought about fixing it through deploying the file with a template.

**Playbook**:
- hosts:
    - esnode1
    - esnode2
    - esnode3
  become: true
  roles:
    - { role: elasticsearch, es_instance_name: "{{ ansible_nodename }}", es_heap_size: "2g",
    es_config: {
        node.name: "{{ ansible_nodename }}",
        cluster.name: "test-cluster",
        discovery.zen.ping.unicast.hosts: ["192.168.121.11:9300", "192.168.121.12:9300", "192.168.121.13:9300"],
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: true,
        bootstrap.memory_lock: false,
        network.host: "_local_, _site_,"
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: vagrant
    es_plugins:
     - plugin: ingest-geoip

**Provide logs from Ansible**:

**ES Logs if irrelevant**:
logs from the system:

```
Feb 15 10:48:35 localhost ansible-command: Invoked with warn=True executable=None _uses_shell=False _raw_params=systemctl daemon-reload removes=None creates=None chdir=None stdin=None
Feb 15 10:48:35 localhost systemd: Reloading.
Feb 15 10:48:36 localhost ansible-systemd: Invoked with no_block=False name=esnode1_elasticsearch enabled=True daemon_reload=False state=restarted user=False masked=None
Feb 15 10:48:36 localhost systemd: Reloading.
Feb 15 10:48:36 localhost systemd: Started Elasticsearch-esnode1.
Feb 15 10:48:36 localhost systemd: Starting Elasticsearch-esnode1...
Feb 15 10:48:36 localhost elasticsearch: /usr/share/elasticsearch/bin/elasticsearch-env: line 70: /etc/sysconfig/elasticsearch: No such file or directory
Feb 15 10:48:36 localhost systemd: esnode1_elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Feb 15 10:48:36 localhost systemd: Unit esnode1_elasticsearch.service entered failed state.
Feb 15 10:48:36 localhost systemd: esnode1_elasticsearch.service failed.
Feb 15 10:48:36 localhost ansible-systemd: Invoked with no_block=False name=esnode1_elasticsearch enabled=True daemon_reload=False state=started user=False masked=None
Feb 15 10:48:36 localhost systemd: Started Elasticsearch-esnode1.
Feb 15 10:48:36 localhost systemd: Starting Elasticsearch-esnode1...
Feb 15 10:48:36 localhost elasticsearch: /usr/share/elasticsearch/bin/elasticsearch-env: line 70: /etc/sysconfig/elasticsearch: No such file or directory
Feb 15 10:48:36 localhost systemd: esnode1_elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Feb 15 10:48:36 localhost systemd: Unit esnode1_elasticsearch.service entered failed state.
Feb 15 10:48:36 localhost systemd: esnode1_elasticsearch.service failed.
Feb 15 10:48:37 localhost ansible-wait_for: Invoked with active_connection_states=['ESTABLISHED', 'FIN_WAIT1', 'FIN_WAIT2', 'SYN_RECV', 'SYN_SENT', 'TIME_WAIT'] host=localhost port=9200 delay=5 msg=None state=started sleep=1 timeout=300 exclude_hosts=None search_regex=None path=None connect_timeout=1
Feb 15 10:53:37 localhost systemd-logind: Removed session 2.
Feb 15 10:53:49 localhost systemd: Started Session 5 of user vagrant.
Feb 15 10:53:49 localhost systemd-logind: New session 5 of user vagrant.
Feb 15 10:53:49 localhost systemd: Starting Session 5 of user vagrant.
```

**Comment by eRadical** [comment]
Related https://github.com/elastic/elasticsearch/issues/28619

**Comment by Crazybus** [comment]
Workaround has been applied in https://github.com/elastic/ansible-elasticsearch/pull/431 (by setting those files to be empty instead of absent)

**Comment by Crazybus** [comment]
@xtruthx please feel free to reopen if this isn't working for you (all integration tests are passing nicely now)

**Comment by xtruthx** [comment]
Thx for letting me know. I will test it this week and let you know if that works.
