### ISSUE TITLE
Test Idempotent behaviour of Role

### ISSUE THREAD

**Issue by gingerwizard** [elastic/ansible-elasticsearch#43]
All current tests install to a clean docker image.  The image is destroyed on completion of the test run.  No tests currently confirm the behaviour if a role is applied multiple times to an image.

Whilst this is difficult to achieve with Kitchen tests, we could test the behaviour is correct when the role is applied to a docker image which already has nodes installed.  This could be used to confirm:
1. No changes are applied and the nodes are NOT restarted i.e. the role is Idempotent
2. Changes are correctly applied and result in node restarts.

@electrical I propose choosing one platform on which to test this - in Kitchen it will require another platform/docker image preloaded with Elasticsearch.  To avoid test explosion we might just limit to one platform therefore.

**Comment by gingerwizard** [comment]
@strootman maybe of interest.

**Comment by strootman** [comment]
So, the kitchen lifecycle is in order: `destroy, create, converge, setup, verify, destroy`.
As @gingerwizard pointed out in #57, running `test` with a regex expression will `destroy` each container before proceeding to the next test. 
I would have to test this out, but here is my proposal.
You would have 2 suites; one to set up and one to test the idempotency. The _setup suite_ would specify an `driver_config.instance_name: "setup"` and it would set the appropriate volumes on that named container; `driver_config.volume: - [CONF_DIR]`.
```
- name: setup_suite 
  ...
  driver_config:
    instance_name: setup
    volume:
       - [CONF_DIR]
       - [ES_HOME]
       - etc
```

Then, the second suite would use `volumes_from: setup`. 

You would have to run these suites together with a `kitchen verify` to prevent the tests from tearing the container down between each test.
I've successfully tested the overriding of `driver_config` at the suite level. Also, if needed, you can limit the platforms you test with in the suite as well.

Like I said, I have not tested this out. And I won't be able to get to it until after next week.
If nobody gets to it before I do, I'll report back!

**Comment by gingerwizard** [comment]
https://github.com/neillturner/kitchen-ansible/issues/116

**Comment by gingerwizard** [comment]
The above is simpler and i believe will deliver what we need

**Comment by strootman** [comment]
Much simpler :+1:

**Comment by gingerwizard** [comment]
This is needed prior to any further work on improving plugin https://github.com/elastic/ansible-elasticsearch/issues/84

**Comment by gingerwizard** [comment]
Working on.

**Comment by bbaassssiiee** [comment]
Maybe use molecule to test idempotency?

**Comment by gingerwizard** [comment]
https://github.com/elastic/ansible-elasticsearch/pull/267

**Comment by gingerwizard** [comment]
https://github.com/elastic/ansible-elasticsearch/pull/267 closes this issue.
