### ISSUE TITLE
Ansible 2.5.0 fails to install elasticsearch becuase its already installed

### ISSUE THREAD

**Issue by abraverm** [elastic/ansible-elasticsearch#439]
**Elasticsearch version** : 5.6.5
**Role version**:  3bdcd8f
**JVM version** (`java -version`): openjdk version "1.8.0_161"
**OS version** (`uname -a` if on a Unix-like system): Fedora 26
**Ansible version**: 2.5.0rc3

**Description of the problem including expected versus actual behaviour**:
Fails to install Elasticsearch with error: "elasticsearch-5.6.5-1.noarch providing elasticsearch-5.6.5 is already installed"

The issue is with the until statement:
`until: '"failed" not in redhat_elasticsearch_install_from_repo'`

The new ansible (2.5.0) has a different output for yum:
`
ok: [elasticsearch] => {
    "redhat_elasticsearch_install_from_repo": {
        "changed": false,
        "failed": false,
        "msg": "",
        "rc": 0,
        "results": [
            "elasticsearch-5.6.5-1.noarch providing elasticsearch-5.6.5 is already installed"
        ]
    }
}
`

**Playbook**:

---
- hosts: elasticsearch
  vars:
     es_templates_fileglob: "templates/elasticsearch/*.json"
     es_templates: true
     es_instance_name: es-test
     es_major_version: 5.x
     es_version: 5.6.5
     es_config:
       network.bind_host:
       - _local_
       - _eth0_
       network.publish_host: _eth0_
  roles:
  - ansible-elasticsearch

**Provide logs from Ansible**:
`
TASK [ansible-elasticsearch : RedHat - Install Elasticsearch] ******************
task path: /var/jenkins/workspace/test/roles/ansible-elasticsearch/tasks/elasticsearch-RedHat.yml:16
FAILED - RETRYING: RedHat - Install Elasticsearch (5 retries left).
FAILED - RETRYING: RedHat - Install Elasticsearch (4 retries left).
FAILED - RETRYING: RedHat - Install Elasticsearch (3 retries left).
FAILED - RETRYING: RedHat - Install Elasticsearch (2 retries left).
FAILED - RETRYING: RedHat - Install Elasticsearch (1 retries left).
fatal: [elasticsearch]: FAILED! => {"attempts": 5, "changed": false, "msg": "", "rc": 0, "results": ["elasticsearch-5.6.5-1.noarch providing elasticsearch-5.6.5 is already installed"]}
`
**ES Logs if relevant**:

**Comment by abraverm** [comment]
#423

**Comment by Crazybus** [comment]
@abraverm The above pull request has been approved and merged. Can you confirm that this fixes your issue? If so could you please close this issue for me?

**Comment by abraverm** [comment]
I will check it today.
BTW, there are some problems with the contributor agreement, who can we contact in Elastic to resolve it?
