### ISSUE TITLE
No module for Search Guard in Elastic Search ## Finding Difficulties ## Bug

### ISSUE THREAD

**Issue by bishwajitsamanta1689** [elastic/ansible-elasticsearch#443]
Hi,

I am unable to install Search Guard Plugin for Elastic Search through ansible. It seems ansible doesnt have any Module created. I have done head plugin installation through elasticsearch_plugin module. But whenever iam trying to put search-guard-2 it says not found.

Ansible Version: 2.4
Type: Bug

Can anyone help me please for Search Guard installation in Elastic Search through Ansible.

[root@ansible-master ansible]# ansible-playbook 6.1_ansible_el_pg.yaml

PLAY [deploy] ***************************************************************************************************************************

TASK [deploy : Install Elastic Search Head Plugin] **************************************************************************************
Monday 16 April 2018  19:05:25 +0530 (0:00:00.035)       0:00:00.035 **********
ok: [192.168.56.121]

TASK [deploy : Install Elastic Search Search Guard Plugin] **************************************************************************************
Monday 16 April 2018  19:05:26 +0530 (0:00:00.854)       0:00:00.889 **********
fatal: [192.168.56.121]: FAILED! => {"changed": false, "err": "failed to download out of all possible locations..., use --verbose to get detailed information", "msg": "Is search-guard-2 a valid plugin name?"}
        to retry, use: --limit @/root/ansible/6.1_ansible_el_pg.retry

PLAY RECAP ******************************************************************************************************************************
192.168.56.121             : ok=1    changed=0    unreachable=0    failed=1

Monday 16 April 2018  19:05:41 +0530 (0:00:14.426)       0:00:15.316 **********
===============================================================================
deploy : Install Elastic Search Head Plugin ------------------------------------------------------------------------------------- 14.43s
deploy : Install Elastic Search Search Guard Plugin -------------------------------------------------------------------------------------- 0.85s

**Comment by jmlrt** [comment]
Hi @bishwajitsamanta1689,
Sorry for the very late answer.
Authentication is now [free with Basic tier](https://www.elastic.co/blog/security-for-elasticsearch-is-now-free).
In addition, while you can manually install Search Guard plugin on Elasticsearch nodes deployed with this Ansible role. We won't include support for tiers plugins inside the role.
