### ISSUE TITLE
Push new release to ansible Galaxy

### ISSUE THREAD

**Issue by average-joe** [elastic/ansible-elasticsearch#453]
<!

**Describe the feature**:

**Elasticsearch version**
6.2.4
**Role version**:  (If using master please specify github sha)
6.2.4 & Master (d0ed1da10753eda07fb659d89c44aaf33eeb4ce7)
**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
Centos 7 -  3.10.0-693.2.2.el7.x86_64
**Description of the problem including expected versus actual behaviour**:
Request a new ansible galaxy release be pushed.  In currently available version, the following task is failing because of the `until` parameter even though elasticsearch version is already installed:

```
- name: RedHat - Install Elasticsearch
  become: yes
  yum: name=elasticsearch{% if es_version is defined and es_version != ""  %}-{{ es_version }}{% endif %} state=present update_cache=yes
  when: es_use_repository
  register: redhat_elasticsearch_install_from_repo
  notify: restart elasticsearch
  until: '"failed" not in redhat_elasticsearch_install_from_repo'
  retries: 5
  delay: 10
```
In the latest Master version, the `until` parameter is modified and succeeds:
```
  until: redhat_elasticsearch_install_from_repo.rc == 0
```

**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

**ES Logs if relevant**:

**Comment by Crazybus** [comment]
Done! https://galaxy.ansible.com/elastic/elasticsearch/ and https://github.com/elastic/ansible-elasticsearch/releases/tag/6.2.4.1
