### ISSUE TITLE
elastic.elasticsearch/files/templates/basic.json (/_template/basic) times out in data node setup

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/ansible-elasticsearch#465]
[RESOLVED: es_templates: false for data nodes]

Bug report 
Elasticsearch version 
6.3.0
Role version:  (If using master please specify github sha)
JVM version (`java -version`):
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
OS version:
Linux ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Description of the problem including expected versus actual behaviour:
When setting up data node, (node.data: true, node.master: false) _template/basic call times out. this behaviour does not manifest with master node setup.
Playbook:
`---
- name: Elasticsearch Data Nodes Install
  become: yes
  hosts: data_nodes
  post_tasks:
    - include: debug.yml
  roles:
    - elastic.elasticsearch
  vars:
    es_instance_name: "{{ansible_hostname}}"
    es_data_dirs:
      - "/opt/elasticsearch/data-1"
      - "/opt/elasticsearch/data-2"
    es_config:
      discovery.zen.ping.unicast.hosts: "{{ groups['unicast_hosts'] }}"
      network.host: "_site_"
      network.publish_host: " _site_"
      network.bind_host: "_site_"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: false
      bootstrap.memory_lock: true
    es_scripts: true
    es_templates: true
    es_heap_size: "2g"
    es_api_host: "{{ansible_default_ipv4.address}}"
    es_api_port: 9200
    es_plugins:
      - plugin: ingest-geoip
    es_enable_xpack: true
    es_xpack_custom_url: "https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-{{ es_version }}.zip"      
    es_xpack_features:
      - monitoring
      - graph
      - ml      
`
**ES Logs if relevant**:
TASK [elastic.elasticsearch : ensure templates dir is created] ***********************************************************************************************************************
ok: [192.168.5.118]
TASK [elastic.elasticsearch : Copy templates to elasticsearch] ***********************************************************************************************************************
ok: [192.168.5.118] => (item=/home/steph/Ansible/roles/elastic.elasticsearch/files/templates/basic.json)
TASK [elastic.elasticsearch : Install templates without auth] ***********************************************************************************************************************
failed: [192.168.5.118] (item=/home/steph/Ansible/roles/elastic.elasticsearch/files/templates/basic.json) => {"changed": false, "content": "", "item": "/home/steph/Ansible/roles/elastic.elasticsearch/files/templates/basic.json", "msg": "Status code was -1 and not [200]: Connection failure: timed out", "redirected": false, "status": -1, "url": "http://192.168.5.118:9200/_template/basic"}

**Comment by Crazybus** [comment]
> [RESOLVED: es_templates: false for data nodes]

Glad to see you figured this out! I'm closing this one out for now.
