### ISSUE TITLE
Default configuration fails to install Elasticsearch

### ISSUE THREAD

**Issue by zyrikby** [elastic/ansible-elasticsearch#468]
**Describe the feature**:

Simple example configuration cannot be used to install Elasticsearch:
```
TASK [elastic.elasticsearch : fail when api credentials are not declared when using security] ************************************************************************************
fatal: [es_main]: FAILED! => {"changed": false, "msg": "Enabling security requires an es_api_basic_auth_username and es_api_basic_auth_password to be provided to allow cluster operations"}
```

The issue is in the xpack. By default, it assumes that xpack with security is enabled and requires to set basic username and password.

Moreover, currently it is impossible to set `license.self_generated.type` to `basic`. Current options are either to install oss-elasticsearch or to provide license file. 

**Elasticsearch version**
6.3

**Role version**:  (If using master please specify github sha)
6.3.0.1

**JVM version** (`java -version`):
```bash
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```bash
Linux laptop 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behaviour**:

**Playbook**:
```yaml
- name: Installing Elasticsearch server
  hosts: es_main
  gather_facts: true
  become: yes
  tags:
    - elasticsearch_installation
  roles:
    - role: elastic.elasticsearch
```

**Provide logs from Ansible**:
```bash
PLAY [Installing Elasticsearch server] *******************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [es_main]

TASK [elastic.elasticsearch : os-specific vars] **********************************************************************************************************************************
ok: [es_main]

TASK [elastic.elasticsearch : Set the defaults here otherwise they can't be overriden in the same play if the role is called twice] **********************************************
ok: [es_main]

TASK [elastic.elasticsearch : Detect if es_version is before X-Pack was open and included] ***************************************************************************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|version_compare` use `result is version_compare`. This feature will be removed in version
2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [es_main]

TASK [elastic.elasticsearch : If this is an older version we need to install X-Pack as a plugin and use a differet users command] ************************************************
skipping: [es_main]

TASK [elastic.elasticsearch : Use the oss repo and package if xpack is not being used] *******************************************************************************************
skipping: [es_main]

TASK [elastic.elasticsearch : fail when es_instance is not defined] **************************************************************************************************************
skipping: [es_main]

TASK [elastic.elasticsearch : fail when es_proxy_port is not defined or is blank] ************************************************************************************************
skipping: [es_main]

TASK [elastic.elasticsearch : debug message] *************************************************************************************************************************************
skipping: [es_main]

TASK [elastic.elasticsearch : debug message] *************************************************************************************************************************************
skipping: [es_main]

TASK [elastic.elasticsearch : debug message] *************************************************************************************************************************************
skipping: [es_main]

TASK [elastic.elasticsearch : fail when heap size is not specified when using memory lock] ***************************************************************************************
skipping: [es_main]

TASK [elastic.elasticsearch : fail when api credentials are not declared when using security] ************************************************************************************
fatal: [es_main]: FAILED! => {"changed": false, "msg": "Enabling security requires an es_api_basic_auth_username and es_api_basic_auth_password to be provided to allow cluster operations"}
        to retry, use: --limit @/home/yury/PROJECTS/ansible/our_system/elasticsearch_playbook.retry

PLAY RECAP ***********************************************************************************************************************************************************************
es_main                    : ok=13   changed=2    unreachable=0    failed=1
```

**Comment by Crazybus** [comment]
Hi @zyrikby!

The short answer it that the default x-pack features which are enabled include security. This is stated in the [readme](https://github.com/elastic/ansible-elasticsearch#installing-x-pack-features) and you can see the defaults in the [defaults.yml](https://github.com/elastic/ansible-elasticsearch/blob/8b92ab9edcfe67756086ba860b357dd49e9e2220/defaults/main.yml#L33). However these defaults make zero sense now that X-Pack (without a license) is the default installation method. So thank you for opening this issue since this is very much a bug. 

The quick fix for you is to disable all of the X-Pack features that you don't want.

So setting `es_xpack_features` to an empty list would allow you to install X-Pack without needing a license.
```
es_xpack_features: []
```

I'm going to leave this issue open to make sure that ansible doesn't attempt to enable features which are not available in the default version of X-Pack.

**Comment by zyrikby** [comment]
Hi @Crazybus!

Thank you for your answer. Indeed, with this configuration elasticsearch can be installed. 
However, I decided to make a step further. I experimented a bit trying to install elasticsearch from a repository and installing it using ansible. Then, from both installations I extracted default configuration using the following command:
```bash
curl -XGET "http://127.0.0.1:9200/_cluster/settings?pretty&include_defaults=true"
```

and I compared the outputs using the command:

```bash
diff -y <(jq -S . ansible_config.json) <(jq -S . default_config.json)
```

Besides the obvious differences (due to the defaults ansible configuration), I found the following related to xpack (first value for ansible, second for default):
1. xpack.graph.enabled:  false | true
2. xpack.monitoring.enabled: false | true
3. xpack.security.enabled: false | true
4. xpack.watcher.enabled: false | true

I am not really good in elasticsearch configurations, but it seems that with the configuration set to `es_xpack_features: []` some basic functionality may be not available (e.g., monitoring). Therefore, to me more appropriate configuration should be at least: `es_xpack_features: ["monitoring"]` Am I right?


Moreover, there is a difference not related to xpack:
1. http.type: "" | "security4"
2. transport.type: "" | "security4"

**Comment by Crazybus** [comment]
> I am not really good in elasticsearch configurations, but it seems that with the configuration set to es_xpack_features: [] some basic functionality may be not available (e.g., monitoring). Therefore, to me more appropriate configuration should be at least: es_xpack_features: ["monitoring"] Am I right?

Yup you are right! However the weird thing here is not all of those features are available in the "basic" version of X-Pack.

**Comment by rlex** [comment]
stumbled upon same problem.
```
es_enable_xpack: false 
```
seems to fixed it if you don't need xpack.

**Comment by zyrikby** [comment]
@rlex if you do not need any features from x-pack, this is a solution! However, based on my observation it is safe to use the following values for the variables:
```
es_enable_xpack: true
es_xpack_features: ["monitoring"]
```

**Comment by zachdesai** [comment]
In case others stumble upon this - 
Setting "es_enable_xpack: false" will break Kibana as Kibana goes searching for xpack related indices - es_xpack_features: ["monitoring"] is likely a better quick fix vs digging into Kibana configurations to determine how to disable xpack Kibana side.

**Comment by jmlrt** [comment]
Hello,
This should be fixed by https://github.com/elastic/ansible-elasticsearch/pull/560

**Comment by jmlrt** [comment]
@zyrikby can you confirm that this is fixed by https://github.com/elastic/ansible-elasticsearch/pull/560?

**Comment by jmlrt** [comment]
I'm closing the issue as there is no answer, don't hesitate to reopen it if you have any question.
