### ISSUE TITLE
Yum versionlock does not properly lock elasticsearch-oss

### ISSUE THREAD

**Issue by conet** [elastic/ansible-elasticsearch#475]
**Elasticsearch version**
6.3.2

**Role version**:  (If using master please specify github sha)
4ec1f3b650b01aee612b334fecc8e30b0ab340c1

**JVM version** (`java -version`):
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behaviour**:

Yum versionlock does not properly lock `elasticsearch-oss` when `es_enable_xpack` is `false`, instead it always locks `elasticsearch` see this https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-RedHat-version-lock.yml#L7

**Playbook**:
```
    es_version: "6.3.2"
    es_version_lock: true
    es_enable_xpack: false
```

**Comment by Crazybus** [comment]
@conet nice catch! I just opened a PR to fix this up.
