### ISSUE TITLE
[Feature] Override wait time in "Wait 15 seconds for the Native Relm to come up" 

### ISSUE THREAD

**Issue by cstegm** [elastic/ansible-elasticsearch#485]
On my old test hardware it tooks around 20s until the Realm is up. Please introduce a default var that we can override.

**Comment by abraxxa** [comment]
For me that's completely unnecessary, can someone explain when this delay is required?

**Comment by pemontto** [comment]
It was added back in 2017 as part of #379. I've added a var `es_api_sleep` that can be overridden in #620

**Comment by jmlrt** [comment]
I'm closing this issue since it was implemented in https://github.com/elastic/ansible-elasticsearch/pull/620/commits/7fd243827c2cdaf75c810c7f42c80c29eff589ce
