### ISSUE TITLE
Xpack basic licence 6.4

### ISSUE THREAD

**Issue by wixaw** [elastic/ansible-elasticsearch#491]
Hi

How can I add the basic license of xpack by ansible?

There is no equivalent to "xpack.license.self_generated.type"

Thanks in advance
William

**Comment by Crazybus** [comment]
Hi @wixaw 

Taken from: https://github.com/elastic/ansible-elasticsearch#installing-x-pack-features

es_xpack_license - X-Pack license. The license is a json blob. Set the variable directly (possibly protected by Ansible vault) or from a file in the Ansible project on the control machine via a lookup:
```
es_xpack_license: "{{ lookup('file', playbook_dir + '/files/' + es_cluster_name + '/license.json') }}"
```

Is this what you are looking for?

**Comment by wixaw** [comment]
Thanks, but since 6.4, there is no need for a license for basic features.
I set "xpack.license.self_generated.type=basic" to elasticsearch.yml https://www.elastic.co/guide/en/elasticsearch/reference/master/license-settings.html

So "es_xpack_license" shouldn't necessarily a file directory. 
In that case, i think it missing a new field like "es_xpack_license_type"

**Comment by Crazybus** [comment]
You are right, it is included. So if you want to only use the basic license then you don't need to configure anything at all.

An example of an install with the basic license is in the automated tests
 https://github.com/elastic/ansible-elasticsearch/blob/master/test/integration/xpack.yml

Are you running into errors?

**Comment by wixaw** [comment]
So it works. Sorry for the inconvenience. I did not think it would automatically activate
It should be specified in the documentation

Thank you

**Comment by Crazybus** [comment]
Got any ideas of where this should be documented and how to word it? I'm not really sure since this feels more like an Elasticsearch documentation question rather than something specific to Ansible.
