### ISSUE TITLE
ES_PATH_CONF environment variable isn't set by playbook

### ISSUE THREAD

**Issue by SETI** [elastic/ansible-elasticsearch#492]
When installing elasticsearch with this ansible role, the ES_PATH_CONF environmental variable isn't set for the system or isn't enabled.  I'm running the playbook against an Ubuntu 16.04 VM that I've built from scratch.

When I attempt to run an apt upgrade, I get an error with the elasticsearch package indicating that it can't be upgraded/updated as the ES_PATH_CONF variable is not set.  

Is this a problem with the playbook? or am I missing a step?

<!

**Describe the feature**:

**Elasticsearch version**

**Role version**:  (If using master please specify github sha)

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behaviour**:

**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

**ES Logs if relevant**:

**Comment by Crazybus** [comment]
> Is this a problem with the playbook? or am I missing a step?

There was a bug which was introduced in 6.3 which was just fixed in the 6.4 release by https://github.com/elastic/ansible-elasticsearch/pull/476 . There is a [specific task](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-Debian-version-lock.yml) which locks the package version so that only ansible is upgrading Elasticsearch and not apt.

Could you fill out the template to specify which role version and elasticsearch version you are using? If you are using < 6.4 as the role version and the `elasticsearch-oss` package then I think you have hit this bug.

**Comment by koteikin** [comment]
I have this problem to

**Elasticsearch version:** 6.4.0
**JVM version:**
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)
**OS version :**
Ubuntu 18.04.1 LTS \n \l
Linux elastic-ansible-test 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Playbook:**
---
- name: Install Elastic, Kibana, nginx, java
  hosts: elastic
  become: true
  gather_facts: yes

  roles:
#    - common
#    - openjava
#    - nginx
    - elastic.elasticsearch
    - elastic-plugin
    - geerlingguy.kibana

  vars_files:
    - group_vars/all

group_vars/all:
domain_name: test.com

kibana_user: ***
kibana_pass: ***

es_java_install: true
es_major_version: 6.x
es_config:
  network.host: 0.0.0.0   #{{ domain_name }}
  node.data: false
  node.master: true
es_instance_name: elastic-test
#es_scripts: false
#es_templates: false
#es_version_lock: false
es_heap_size: 4g
#es_api_port: 9201
es_api_basic_auth_username: elastic
es_api_basic_auth_password: elastic
# es_plugins_reinstall: true
# es_plugins:
#   - plugin: analysis-ukrainian


kibana_server_port: 5601
kibana_server_host: "localhost"
kibana_elasticsearch_url: "http://localhost:9200" # http://{{ domain_name }}:9200

**Comment by SETI** [comment]
Hi,

not sure about the version of the role that I'm using.  However, I started working with it about 2-3 weeks ago.  I think most if not all of the changes since then are focused on the test suite.

Also, I'm running elasticsearch version 6.4.0.  I see a variable called es_version_lock: false.  I'm changing this to true and then trying again.

**Comment by SETI** [comment]
Hey, pretty sure this fixed my problem.  thanks again! for anyone else, but sure that es_version_lock is set to true and the playbook will lock the elasticsearch package.

**Comment by Crazybus** [comment]
> Also, I'm running elasticsearch version 6.4.0. I see a variable called es_version_lock: false. I'm changing this to true and then trying again.

Ahh I had forgotten that this was set to `false` by default 🤦‍♂️ . Glad you got it sorted though!

@koteikin looking at your config it seems you also don't have `es_version_lock: true`. If you are still having problems feel free to open another issue.
