### ISSUE TITLE
es_version_lock: false doesn't remove existing hold

### ISSUE THREAD

**Issue by abraxxa** [elastic/ansible-elasticsearch#499]
**Elasticsearch version**
6.4.1

**Role version**:
tag 6.4.0

**JVM version** (`java -version`):
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux nac-prod 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1 (2018-04-28) x86_64 GNU/Linux

**Description of the problem including expected versus actual behaviour**:
including elasticsearch-Debian-version-lock.yml is skipped instead of included with different parameters

**Comment by jmlrt** [comment]
Closed by https://github.com/elastic/ansible-elasticsearch/pull/601
Thanks @LukeRoz
