### ISSUE TITLE
Activating X-Pack doesn't work with https

### ISSUE THREAD

**Issue by cstegm** [elastic/ansible-elasticsearch#500]
On our cluster is SSL enabled, but all connections to the cluster in this role are using http.

Feature request: make it configureable or provide https as fallback.

**Comment by cstegm** [comment]
Ah there is a pull request for this :)
https://github.com/elastic/ansible-elasticsearch/pull/479

**Comment by itsmed** [comment]
Thanks for opening this ( bumping the thread ) @cstegm . I'm taking a look at the issues with #479 . I'm going to leave this issue open until #479 is merged.

**Comment by cstegm** [comment]
Any updates here?

**Comment by doctore74** [comment]
+1

**Comment by DRhyme** [comment]
Nothing happend so far. Why? Please fix this issue...

**Comment by abraxxa** [comment]
I modify the role myself by changing http to https in several files and it works fine, no idea why Elastic isn't adding this feature to the playbook.

**Comment by jmlrt** [comment]
I closed the other issues related to **Encrypting Communications in Elasticsearch** and we'll continue working on it on this Issue.

Current work-in-progress PR are https://github.com/elastic/ansible-elasticsearch/pull/479 and https://github.com/elastic/ansible-elasticsearch/pull/597

**Comment by jmlrt** [comment]
I'm closing it since #620 was merged.
