### ISSUE TITLE
access elasticsearch from public IP, es_api_host: "0.0.0.0" not working 

### ISSUE THREAD

**Issue by shixudongleo** [elastic/ansible-elasticsearch#506]
In `templates/elasticsearch.yml.j2`, please consider add the following: 

{% if es_api_host is defined %}
network.host: {{ es_api_host }}
{% endif %}

**Comment by Crazybus** [comment]
As specified in the readme the `es_api_host` is used to connect to the host. `0.0.0.0` is not going to work for a lot reasons.

> * ```es_api_host``` The host name used for actions requiring HTTP e.g. installing templates. Defaults to "localhost".

You want to be setting the network.host directly.

> * ```es_config['network.host']``` - sets both network.bind_host and network.publish_host to the same host value. The network.bind_host setting allows to control the host different network components will bind on.

So you would want:
```
es_config:
  network.host: 0.0.0.0
```
