### ISSUE TITLE
xpack.monitoring.collection.enabled

### ISSUE THREAD

**Issue by kakoni** [elastic/ansible-elasticsearch#517]
There has been changes how monitoring is configured in elasticsearch.

"If the Elasticsearch cluster's xpack.monitoring.collection.enable is not set to true, the x-pack endpoint for monitoring will silently ignore any monitoring events that are sent to it (even if its xpack.monitoring.enable is set to true). As this was explained to me, enabling the feature as a whole allows you to look at dashboards of existing data in Kibana, while enabling collection allows new data to be ingested." (https://github.com/elastic/logstash/issues/9901)

So if es_xpack_features monitoring is enabled, then xpack.monitoring.collection.enabled needs to be set to true (default is false)

**Comment by kakoni** [comment]
So perhaps 
```yaml
{% if "monitoring" in es_xpack_features %}
xpack.monitoring.collection.enabled: true
{% endif %}
```

would do in elasticsearch.yml.j2

**Comment by Crazybus** [comment]
> So if es_xpack_features monitoring is enabled, then xpack.monitoring.collection.enabled needs to be set to true (default is false)

It makes sense for this ansible role to follow the same defaults that Elasticsearch it self does. This setting is [disabled by default](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/monitoring-settings.html) even when enabling the monitoring feature so it would be unexpected if enabling the feature also changed your configuration. 

I believe the main reason this is disabled by default is that it isn't recommended to send monitoring data to a live production cluster. Instead it is expected that you enable collection and point it towards your [monitoring cluster at the same time](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/collecting-monitoring-data.html). So the change your are suggesting would be directly going against best practices. 

> By default, monitoring is enabled but data collection is disabled. To enable data collection, use the xpack.monitoring.collection.enabled setting.

So the correct way to enable collection (if the user choses to) is to add this setting into `es_config`. Did you have problems when trying to enable this setting via the `es_config` variable?

**Comment by kakoni** [comment]
Ok this makes sense. I'll use es_config for this.
