### ISSUE TITLE
Multiple data_dir definitions does not work

### ISSUE THREAD

**Issue by robin13** [elastic/ansible-elasticsearch#52]
Defining multiple data directories:

```
 es_data_dir: "/mnt/xvdb,/mnt/xvdc"
```

Results in

```
DATA_DIR=/mnt/xvdb,/mnt/xvdc/ec2_marvel-rclarke_marvel
```

The node name is pasted after the last directory.

I don't think it is necessary to have a separate directory for each node running on a single machine, same as it is not necessary to have a separate directory for logs or work I think...

**Comment by gingerwizard** [comment]
Whilst not necessary it makes identifying the data/logs associated with a node much simpler for little complexity.  Its a consistent separation we try to maintain throughout.  Agreed this should support a list however. Next release.

**Comment by gingerwizard** [comment]
Fixed in pull request [74](https://github.com/elastic/ansible-elasticsearch/pull/74)
