### ISSUE TITLE
Is it possible pass from oss to basic license?

### ISSUE THREAD

**Issue by fedelemantuano** [elastic/ansible-elasticsearch#520]
I'd like to pass from `oss` to `basic` license. Is this possible without lose data?
If it's possible, maybe you should change the role, that can pass from basic to oss, but not vice versa.

**Elastic version**
6.5.1

**Playbook version**
6.5.1.1

**Java version**
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

**OS version**
Linux xxxxx 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behaviour**:

**Playbook**:
```
#!/usr/bin/env ansible-playbook
---
- name: Install Elasticsearch Cluster
  hosts: elasticsearch
  become: true

  pre_tasks:
    - name: include commons variables
      include_vars: "vars/commons.yml"

  roles:
    - role: elasticsearch

  tasks:
    - name: Set vm.swappiness to 1
      sysctl:
        name: vm.swappiness
        value: 1
        state: present

  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
```

**Error**
```
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager, versionlock
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Resolving Dependencies
--> Running transaction check
---> Package elasticsearch.noarch 0:6.5.4-1 will be installed
--> Processing Conflict: elasticsearch-oss-6.5.1-1.noarch conflicts elasticsearch
--> Restarting Dependency Resolution with new changes.
--> Running transaction check
---> Package elasticsearch-oss.noarch 0:6.5.1-1 will be updated
---> Package elasticsearch-oss.noarch 0:6.5.4-1 will be an update
--> Processing Conflict: elasticsearch-oss-6.5.4-1.noarch conflicts elasticsearch
--> Processing Conflict: elasticsearch-6.5.4-1.noarch conflicts elasticsearch-oss
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by Crazybus** [comment]
> I'd like to pass from oss to basic license. Is this possible without lose data?

Yes. Although as always it's recommended to follow the [upgrading guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html) which includes super important steps like testing the upgrade on a development environment (you can use the [local testing environment](https://github.com/elastic/ansible-elasticsearch#testing) for this if you don't have one). And also making sure that you take backups before the upgrade process. 

> If it's possible, maybe you should change the role, that can pass from basic to oss, but not vice versa.

Oddly enough the playbook already supported going from the standard package to oss but not the other way around. I have created #521 which fixes this up to make sure switching works in both directions!
