### ISSUE TITLE
'dict object' has no attribute 'stdout'

### ISSUE THREAD

**Issue by badfiles** [elastic/ansible-elasticsearch#525]
**Elasticsearch version**
elasticsearch-oss.noarch              6.5.4-1

**Role version**:  (If using master please specify github sha)
commit b37723aa1fabcd2ca5ce538995dd6e37253c1446

**JVM version** (`java -version`):
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
ubuntu 18.04 (control), centos 7 (target)
**Description of the problem including expected versus actual behaviour**:
TASK [elastic.elasticsearch : correct java version selected] **************************************************************************************************
fatal: [host]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/home/vlad/.ansible/roles/elastic.elasticsearch/tasks/java.yml': line 23, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: correct java version selected\n  ^ here\n"}

**Playbook**:
...
  roles:
    - dj-wasabi.zabbix-agent
    - geerlingguy.apache
    - geerlingguy.php
    - elastic.elasticsearch
...

**Provide logs from Ansible**:
ansible-2.7.5

TASK [elastic.elasticsearch : os-specific vars] ***************************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/main.yml:2
ok: [*****] => {
    "ansible_facts": {
        "default_file": "/etc/sysconfig/elasticsearch",
        "es_home": "/usr/share/elasticsearch",
        "java": "{{ es_java | default('java-1.8.0-openjdk.x86_64') }}"
    },
    "ansible_included_var_files": [
        "/home/vlad/.ansible/roles/elastic.elasticsearch/vars/RedHat.yml"
    ],
    "changed": false
}

TASK [elastic.elasticsearch : Set the defaults here otherwise they can't be overriden in the same play if the role is called twice] ***************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/compatibility-variables.yml:9
ok: [*****] => {
    "ansible_facts": {
        "es_install_xpack": false,
        "es_open_xpack": true,
        "es_repo_name": "6.x",
        "es_users_path": "users",
        "es_xpack_conf_subdir": "",
        "es_xpack_users_command": "elasticsearch-users"
    },
    "changed": false
}

TASK [elastic.elasticsearch : Detect if es_version is before X-Pack was open and included] ********************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/compatibility-variables.yml:18
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|version_compare` use `result is version_compare`. This feature will be 
removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : If this is an older version we need to install X-Pack as a plugin and use a differet users command] *****************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/compatibility-variables.yml:23
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : Use the oss repo and package if xpack is not being used] ************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/compatibility-variables.yml:32
ok: [*****] => {
    "ansible_facts": {
        "es_package_name": "elasticsearch-oss",
        "es_repo_name": "oss-6.x"
    },
    "changed": false
}

TASK [elastic.elasticsearch : fail when es_instance is not defined] *******************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:3
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : fail when es_proxy_port is not defined or is blank] *****************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:7
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : debug message] ******************************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:11
ok: [*****] => {
    "msg": "WARNING - It is recommended you specify the parameter 'http.port'"
}

TASK [elastic.elasticsearch : debug message] ******************************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:15
ok: [*****] => {
    "msg": "WARNING - It is recommended you specify the parameter 'transport.tcp.port'"
}

TASK [elastic.elasticsearch : debug message] ******************************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:19
ok: [*****] => {
    "msg": "WARNING - It is recommended you specify the parameter 'discovery.zen.ping.unicast.hosts'"
}

TASK [elastic.elasticsearch : fail when heap size is not specified when using memory lock] ********************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:24
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : fail when api credentials are not declared when using security] *****************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:29
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : set fact file_reserved_users] ***************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:33
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : fail when changing users through file realm] ************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:37
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : set fact instance_default_file] *************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:42
ok: [*****] => {
    "ansible_facts": {
        "instance_default_file": "/etc/sysconfig/*****_elasticsearch"
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact instance_init_script] **************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:44
ok: [*****] => {
    "ansible_facts": {
        "instance_init_script": "/etc/init.d/*****_elasticsearch"
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact conf_dir] **************************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:46
ok: [*****] => {
    "ansible_facts": {
        "conf_dir": "/etc/elasticsearch/*****"
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact m_lock_enabled] ********************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:48
ok: [*****] => {
    "ansible_facts": {
        "m_lock_enabled": true
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact use_system_d] **********************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:60
ok: [*****] => {
    "ansible_facts": {
        "use_system_d": true
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact instance_sysd_script] **************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:63
ok: [*****] => {
    "ansible_facts": {
        "instance_sysd_script": "/usr/lib/systemd/system/*****_elasticsearch.service"
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact instance_suffix] *******************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:68
ok: [*****] => {
    "ansible_facts": {
        "instance_suffix": "*****-*****"
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact pid_dir] ***************************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:70
ok: [*****] => {
    "ansible_facts": {
        "pid_dir": "/var/run/elasticsearch/*****-*****"
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact log_dir] ***************************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:72
ok: [*****] => {
    "ansible_facts": {
        "log_dir": "/var/log/elasticsearch/*****-*****"
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact log_dir] ***************************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml:74
ok: [*****] => {
    "ansible_facts": {
        "data_dirs": [
            "/var/lib/elasticsearch/*****-*****"
        ]
    },
    "changed": false
}

TASK [elastic.elasticsearch : detect if we need the .deb or .rpm] *********************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:5
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : get the minor version] **********************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:9
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : set the package_name] ***********************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:13
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : generate the artifacts url] *****************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:17
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : get latest snapshot build] ******************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:21
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : use the custom package url instead of the repository] ***************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:31
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : split up the snapshot url so we can create the plugin url] **********************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:39
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : set base plugin url] ************************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:43
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : create es_plugins with the snapshot url] ****************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:47
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : override the original es_plugins with the snapshot version] *********************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/snapshot-release.yml:52
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : set fact java_state to present] *************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/java.yml:3
ok: [*****] => {
    "ansible_facts": {
        "java_state": "present"
    },
    "changed": false
}

TASK [elastic.elasticsearch : set fact java_state to latest] **************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/java.yml:6
skipping: [*****] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [elastic.elasticsearch : RedHat - Ensure Java is installed] **********************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/java.yml:10
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e ***** '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<*****> (0, b'/home/*****\n', b'')
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e ***** '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/*****/.ansible/tmp/ansible-tmp-1547192913.7005382-52434115531058 `" && echo ansible-tmp-1547192913.7005382-52434115531058="` echo /home/*****/.ansible/tmp/ansible-tmp-1547192913.7005382-52434115531058 `" ) && sleep 0'"'"''
<*****> (0, b'ansible-tmp-1547192913.7005382-52434115531058=/home/*****/.ansible/tmp/ansible-tmp-1547192913.7005382-52434115531058\n', b'')
Using module file /usr/local/lib/python3.6/dist-packages/ansible/modules/packaging/os/yum.py
<*****> PUT /home/vlad/.ansible/tmp/ansible-local-21967ru7impvq/tmpibqfgs1r TO /home/*****/.ansible/tmp/ansible-tmp-1547192913.7005382-52434115531058/AnsiballZ_yum.py
<*****> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e '[*****]'
<*****> (0, b'sftp> put /home/vlad/.ansible/tmp/ansible-local-21967ru7impvq/tmpibqfgs1r /home/*****/.ansible/tmp/ansible-tmp-1547192913.7005382-52434115531058/AnsiballZ_yum.py\n', b'')
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e ***** '/bin/sh -c '"'"'chmod u+x /home/*****/.ansible/tmp/ansible-tmp-1547192913.7005382-52434115531058/ /home/*****/.ansible/tmp/ansible-tmp-1547192913.7005382-52434115531058/AnsiballZ_yum.py && sleep 0'"'"''
<*****> (0, b'', b'')
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e -tt ***** '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=ykikvnpmxcjkzwnahcfswlnpxdomfwfr] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ykikvnpmxcjkzwnahcfswlnpxdomfwfr; /usr/bin/python /home/*****/.ansible/tmp/ansible-tmp-1547192913.7005382-52434115531058/AnsiballZ_yum.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<*****> (0, b'\r\n\r\n{"msg": "", "invocation": {"module_args": {"update_cache": false, "conf_file": null, "exclude": [], "allow_downgrade": false, "disable_gpg_check": false, "disable_excludes": null, "use_backend": "auto", "state": "present", "disablerepo": [], "releasever": null, "skip_broken": false, "autoremove": false, "enable_plugin": [], "installroot": "/", "name": ["java-1.8.0-openjdk.x86_64"], "download_only": false, "bugfix": false, "list": null, "install_repoquery": true, "update_only": false, "disable_plugin": [], "enablerepo": [], "security": false, "validate_certs": true}}, "changed": false, "results": ["1:java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64 providing java-1.8.0-openjdk.x86_64 is already installed"], "rc": 0}\r\n', b'Shared connection to ***** closed.\r\n')
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e ***** '/bin/sh -c '"'"'rm -f -r /home/*****/.ansible/tmp/ansible-tmp-1547192913.7005382-52434115531058/ > /dev/null 2>&1 && sleep 0'"'"''
<*****> (0, b'', b'')
ok: [*****] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "installroot": "/",
            "list": null,
            "name": [
                "java-1.8.0-openjdk.x86_64"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": false,
            "update_only": false,
            "use_backend": "auto",
            "validate_certs": true
        }
    },
    "msg": "",
    "rc": 0,
    "results": [
        "1:java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64 providing java-1.8.0-openjdk.x86_64 is already installed"
    ]
}

TASK [elastic.elasticsearch : Get the installed java path] ****************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/java.yml:15
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e ***** '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<*****> (0, b'/home/*****\n', b'')
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e ***** '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/*****/.ansible/tmp/ansible-tmp-1547192915.5023282-232899254394373 `" && echo ansible-tmp-1547192915.5023282-232899254394373="` echo /home/*****/.ansible/tmp/ansible-tmp-1547192915.5023282-232899254394373 `" ) && sleep 0'"'"''
<*****> (0, b'ansible-tmp-1547192915.5023282-232899254394373=/home/*****/.ansible/tmp/ansible-tmp-1547192915.5023282-232899254394373\n', b'')
Using module file /usr/local/lib/python3.6/dist-packages/ansible/modules/commands/command.py
<*****> PUT /home/vlad/.ansible/tmp/ansible-local-21967ru7impvq/tmprqgvygtt TO /home/*****/.ansible/tmp/ansible-tmp-1547192915.5023282-232899254394373/AnsiballZ_command.py
<*****> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e '[*****]'
<*****> (0, b'sftp> put /home/vlad/.ansible/tmp/ansible-local-21967ru7impvq/tmprqgvygtt /home/*****/.ansible/tmp/ansible-tmp-1547192915.5023282-232899254394373/AnsiballZ_command.py\n', b'')
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e ***** '/bin/sh -c '"'"'chmod u+x /home/*****/.ansible/tmp/ansible-tmp-1547192915.5023282-232899254394373/ /home/*****/.ansible/tmp/ansible-tmp-1547192915.5023282-232899254394373/AnsiballZ_command.py && sleep 0'"'"''
<*****> (0, b'', b'')
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e -tt ***** '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=fhttfvnbnojxlfbijoclgofzrjlhcqaz] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-fhttfvnbnojxlfbijoclgofzrjlhcqaz; /usr/bin/python /home/*****/.ansible/tmp/ansible-tmp-1547192915.5023282-232899254394373/AnsiballZ_command.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<*****> (0, b'\r\n\r\n{"msg": "skipped, running in check mode", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": true, "_raw_params": "update-alternatives --display java | grep \'^/\' | awk \'{print $1}\' | grep 1.8.0 | head -1", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin": null}}, "skipped": true}\r\n', b'Shared connection to ***** closed.\r\n')
<*****> ESTABLISH SSH CONNECTION FOR USER: None
<*****> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vlad/.ansible/cp/58fd294f9e ***** '/bin/sh -c '"'"'rm -f -r /home/*****/.ansible/tmp/ansible-tmp-1547192915.5023282-232899254394373/ > /dev/null 2>&1 && sleep 0'"'"''
<*****> (0, b'', b'')
skipping: [*****] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "_raw_params": "update-alternatives --display java | grep '^/' | awk '{print $1}' | grep 1.8.0 | head -1",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "msg": "skipped, running in check mode"
}

TASK [elastic.elasticsearch : correct java version selected] **************************************************************************************************
task path: /home/vlad/.ansible/roles/elastic.elasticsearch/tasks/java.yml:23
fatal: [*****]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/home/vlad/.ansible/roles/elastic.elasticsearch/tasks/java.yml': line 23, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: correct java version selected\n  ^ here\n"
}

**ES Logs if relevant**:

**Comment by Crazybus** [comment]
```
"msg": "skipped, running in check mode"
```

Can you confirm that you are running in check mode? I would actually be surprised if check mode did work based on the amount of shell tasks that we have. 

You can try setting `always_run: yes` to this task as it would be safe to run in check mode.

**Comment by Crazybus** [comment]
I just merged in #539 which fixes check mode for the failing task that you showed. Could you try again with the latest master?
