### ISSUE TITLE
 Permission denied during templates folder creation

### ISSUE THREAD

**Issue by GopalGitSdsu** [elastic/ansible-elasticsearch#533]
Elasticsearch version: 6.5.1

**Role version**:  6.5.1

**JVM version**: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version** :
Linux  4.4.0-119-generic #143-Ubuntu SMP  Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04.4

**Description of the problem **:
As seen on my playbook below,I had enabled "es_templates: true" and provided the json templates path.  During installation of Elasticsearch, encountered a permission issue on  creation of /etc/elasticsearch/templates folder. Following is the error message.

Using "become: yes" will fix , but don't want to disturb the role. 

FAILED! => {"changed": false, "msg": "There was an issue creating /etc/elasticsearch/templates as requested: [Errno 13] Permission denied: '/etc/elasticsearch/templates'", "path": "/etc/elasticsearch/templates", "state": "absent"}

Expected: Successful creation of /etc/elasticsearch/templates  

Playbook Used: 

- name: Setup ES Ingesters/Clients
  hosts: ingest
  roles:
    - role: elastic.elasticsearch
  vars:
    es_group_id: 999
    es_user_id: 999
    es_enable_xpack: false
    es_instance_name: "{{ansible_hostname}}"
    es_heap_size: "3g"
    es_api_host: "{{ansible_hostname}}"
    es_api_port: 9200
    es_config:
      cluster.name: "es-{{ _lifecycle }}"
      network.host: "{{ansible_hostname}}"
      discovery.zen.minimum_master_nodes: "{{ ((groups['master']|length) / 2)|round|int }}"
      discovery.zen.ping.unicast.hosts: "{{ groups['master'] }}"
      http.enabled: true
      http.compression: true
      http.cors.enabled: true
      http.cors.allow-origin: "*"
      http.port: 9200
      transport.tcp.port: 9300
      node.name: "{{ansible_hostname}}"
      node.data: false
      node.master: false
      node.ingest: true
      bootstrap.memory_lock: false
    es_scripts: false
    es_templates: true
    es_templates_fileglob: es_templates/*.json
    es_version_lock: false
    ansible_user: ubuntu

**Comment by Crazybus** [comment]
Could you show me the current permissions with `ls -lhatr /etc/elasticsearch/templates`? My best guess is that they are currently owned by a different user. Since you are setting `es_user_id: 999` it isn't possible for them to be removed.

**Comment by fastlorenzo** [comment]
Re-opening as I'm having the same issue here.

The `ansible_user` (`rtoperator` in this case) doesn't have the necessary rights to create the `/etc/elasticsearch/templates`, moving this folder to a temp location might fix.

![image](https://user-images.githubusercontent.com/768639/94262868-75535800-ff34-11ea-9865-e88d77d26d39.png)

Another option would be to add `become: true` to the template tasks.
