### ISSUE TITLE
feature: use standard paths instead of es_instance_name

### ISSUE THREAD

**Issue by tomryanx** [elastic/ansible-elasticsearch#547]
Would there be an appetite for a PR that exposes a var like `es_standard_paths` to put all ES files into their standard paths instead of using `es_instance_name` everywhere?

So instead of eg:

```
- name: set fact conf_dir
  set_fact: conf_dir={{ es_conf_dir }}/{{es_instance_name}}
```

we could have something more like:

```
- name: set fact conf_dir with es_instance_name
  set_fact: conf_dir={{ es_conf_dir }}/{{es_instance_name}}
  when: es_standard_paths is not defined or not es_standard_paths
- name: set fact conf_dir with standard path
  set_fact: conf_dir={{ es_conf_dir }}
  when: es_standard_paths is defined and es_standard_paths
```

If there is an appetite, I'd appreciate an indication of whether you'd prefer:
* duplicated "couplets" in-line in `elasticsearch-parameters.yml` like the example above
* two contiguous blocks (ie all `es_instance_name` params, followed by all standard path params)
* a separate parameters file and a `when` condition on the include statements

**Comment by jmlrt** [comment]
should be fixed by https://github.com/elastic/ansible-elasticsearch/pull/566

**Comment by jmlrt** [comment]
https://github.com/elastic/ansible-elasticsearch/pull/566 is merged.
I'm closing the issue, don't hesitate to reopen it if you have any question.
