### ISSUE TITLE
jvm.options missing DNS cache policy settings

### ISSUE THREAD

**Issue by rozling** [elastic/ansible-elasticsearch#553]
**6.6.1**

**Role version**: 6.6.0

**JVM version** (`java -version`):

**OS version** Linux 4.4.0-1075-aws #85-Ubuntu

**Description of the problem including expected versus actual behaviour**:
Recent versions of Elasticsearch have configurable DNS cache policy in jvm.options (see [this commit](https://github.com/elastic/elasticsearch/pull/36570/commits/d057d3c933c5f97c07c85c79efc46c81b04db3ed)), but this hasn't made it to the Ansible playbook.

Technically this might be a duplicate of https://github.com/elastic/ansible-elasticsearch/issues/382, but I believe that was looking for a 'playbooked' solution whereas this has now been handled within Elasticsearch?

**Comment by Crazybus** [comment]
Hey Eoin!

There is a configurable variable called `es_jvm_custom_parameters` which allows you to add any custom parameters to the jvm.options. You can add them by doing something like:

```
es_jvm_custom_parameters:
  - '-Des.networkaddress.cache.ttl=60'
  - '-Des.networkaddress.cache.negative.ttl=10'
```

**Comment by rozling** [comment]
@Crazybus awesome, thanks for that!

I've wondered before with this repo whether it would be worth breaking out readme.md to separate wiki pages.  There could be one for all variables, then a separate one for examples etc.  Seems like it would clean up readme.md a lot but I'm sure there are good arguments for and against

**Comment by Crazybus** [comment]
I'm going to close this out since it sounds like you get it working. 

>  There could be one for all variables, then a separate one for examples etc. Seems like it would clean up readme.md a lot but I'm sure there are good arguments for and against

Is there a way to get that to display nicely on [ansible galaxy](https://galaxy.ansible.com/elastic/elasticsearch)? If there is then I'm all for it! Otherwise I believe that is the reason that everyone sticks with a single big long readme. We could also look into adding table headers at the start of the readme to make it easier to digest.
