### ISSUE TITLE
Support for 6.8.0?

### ISSUE THREAD

**Issue by ohadbp** [elastic/ansible-elasticsearch#565]
Last supported version in Ansible Galaxy is 6.6, Is there a plan to support 6.8? 

Thanks.

**Comment by jmlrt** [comment]
Hi @ohadbp,

We don't release and test Ansible role for every Elasticsearch version.
This hasn't been tested but you should be able to use Ansible Galaxy 6.6 or  master branch of the GitHub repo to install ElasticSearch 6.8.0 by setting variable `es_version` to `6.8.0`.

**Comment by ohadbp** [comment]
Perfect, Thanks.

**Comment by jmlrt** [comment]
I'm closing the issue, don't hesitate to reopen it if you have any question.
