### ISSUE TITLE
Python3 "'dict object' has no attribute \"dict_keys(['... "

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/ansible-elasticsearch#570]
Env: Python 3.7.1
ansible-elasticsearch
elasticsearch-security-file.yml, line 73:
```"#Set passwords for all users declared - Required as the useradd will not change existing user passwords
- name: Set User Passwords
  become: yes
  command: >
    {{es_home}}/bin/{{es_xpack_users_command}} passwd {{ item }} -p {{es_users.file[item].password}}
  with_items: "{{ es_users.file.keys() | default([]) }}"
  when: manage_file_users
 ---
```
```hosts snippet:
es_users:
      file: 
        steph:
          password: 'xxxx'
          roles:
            - admin
```
Fails with Python3 (`python3 $(which ansible-playbook) -i hosts-prod  ./7-elasticsearch_master.yml`)
`'dict object' has no attribute \"dict_keys(['steph'])`
Succeeds in Python2

**Comment by jmlrt** [comment]
Hi @svanschalkwyk,
We don't currently test this role with Python3 but can take a look.

What version of Ansible are you using?

**Comment by svanschalkwyk** [comment]
ansible 2.9.0.dev0

**Comment by jmlrt** [comment]
This is related to some change in dictionaries in Python3: https://docs.ansible.com/ansible/2.4/playbooks_python_version.html#dictionary-views
