### ISSUE TITLE
[7.1.1] Upgrade docs error

### ISSUE THREAD

**Issue by abraxxa** [elastic/ansible-elasticsearch#574]
**Role version**:  7.1.1

**Description of the problem including expected versus actual behaviour**:

The [upgrade docs](https://github.com/elastic/ansible-elasticsearch/blob/master/docs/multi-instance.md#upgrade-procedure) lists the four variables that need to be set to the existing directories when upgrading from a previous playbook version to 7.1.1.
The variable `instance_name` was called `es_instance_name`, see [tag 6.6.0](https://github.com/elastic/ansible-elasticsearch/tree/6.6.0) for example.

As node.name defaults to the hostname using the ansible variable `ansible_hostname` might be a better recommendation instead of `node_name` which is undefined when using the previous playbook version.

**Comment by jmlrt** [comment]
Hi @abraxxa,

Thanks a lot for the issue, `{{ node_name }}` and `{{ instance_name }}` in the upgrade doc were more placeholders to replace than real ansible variables but you're totally right, it's more consistent and clearer to use ansible variables.

For `node_name`, I would use `inventory_hostname` instead of `ansible_hostname` to be fully consistent with previous behavior (https://github.com/elastic/ansible-elasticsearch/pull/566/files#diff-916074b85953579021fe6cee52c54d8bL65).

Would you mind creating a PR for that change?

**Comment by abraxxa** [comment]
Yeah I thought so but providing usable ones if available is even better :smile:

I have submitted PRs in the past which couldn't be merged because I can't sign the CLA, so please create it yourself.
Thanks!

**Comment by abraxxa** [comment]
You're right on `instance_name` as the previous playbook version used the fqdn for the node name, not just its hostname, so `inventory_hostname` works for me but might not if e.g. only the hostname is used for the inventory and `ansible_host` is defined.

**Comment by abraxxa** [comment]
And another issue I've encountered which fits this bug report as well:
LimitMEMLOCK=infinity isn't defined in the systemd service file of the Debian package and the playbook doesn't generate a `/etc/systemd/system/elasticsearch.service.d/override.conf` containing

> [Service]
> LimitMEMLOCK=infinity

as the docs suggest.
Should be generated by the playbook as well.

**Comment by wixaw** [comment]
@jmlrt I confirm same problem missing "LimitMEMLOCK=infinity" on Centos7
On my test cluster it worked without doing anything but at the moment when it was put in production it was missing this parameter

**Comment by jmlrt** [comment]
@abraxxa @wixaw FYI `LimitMEMLOCK=infinity` issue will be handled in https://github.com/elastic/ansible-elasticsearch/issues/585
