### ISSUE TITLE
[7.1.1] don't overwrite log4j2.properties with 6.x non-JSON version

### ISSUE THREAD

**Issue by abraxxa** [elastic/ansible-elasticsearch#577]
**Elasticsearch version**: 7.1.1

**Role version**:  7.1.1

**JVM version** (`java -version`): bundled JDK

**OS version** (`uname -a` if on a Unix-like system): Linux hostname 4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behaviour**:
The template file `templates/log4j2.properties.j2` shipped with the role is from version 6 and logs in plain text and not JSON.
We would prefer an option to not overwrite the file installed by the package at all, for example by setting `es_config_log4j2: null`.

**Comment by Crazybus** [comment]
>  The template file templates/log4j2.properties.j2 shipped with the role is from version 6 and logs in plain text and not JSON.

I think it might even be from version 5 looking at how old the commit messages are :o 

We can just remove it altogether and instead give the user an option to replace the logging config. I believe this was being manually added via a template back when this role supported running multiple instances at the same time.

**Comment by jmlrt** [comment]
@abraxxa, we just merged #637 which stop overwriting log4j2.properties among other things.

**Comment by abraxxa** [comment]
Thanks for the information, I can confirm that this works as expected.
