### ISSUE TITLE
Activate ES license fails with HTTPS

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/ansible-elasticsearch#579]
File: elasticsearch-xpack-activatton.yml
Current version.
Activation fails when SSL is used. 
I added a flag to route to https://{{es_api_host}}:{{es_api_port}}/_xpack/license?acknowledge=true"
when xpack.security.http.ssl.enabled: true

**Comment by Crazybus** [comment]
This is being currently worked on in #479 

Closing this issue as a duplicate of #500
