### ISSUE TITLE
ed

### ISSUE THREAD

**Issue by slimsheddy** [elastic/ansible-elasticsearch#580]
<!

**Describe the feature**:

**Elasticsearch version**

**Role version**:  (If using master please specify github sha)

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behaviour**:

**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

**ES Logs if relevant**:

**Comment by jmlrt** [comment]
closing the issue as there is no content
