### ISSUE TITLE
Does this role support Kibana installation too? 

### ISSUE THREAD

**Issue by icamys** [elastic/ansible-elasticsearch#584]

**Comment by ktibi** [comment]
no

**Comment by icamys** [comment]
@ktibi  Thanks for the answer

**Comment by jmlrt** [comment]
Hi @icamys,
this role is installing only elasticsearch, we don't have ansible role for kibana installation yet.

**Comment by icamys** [comment]
@jmlrt I am new to elasticsearch and I found this repo very vert useful to deploy clusters from scratch. The next step after most installations of elasticsearch is to install kibana to work with data and I believe it would be very nice to have an optional installation of kibana in this repo too.

**Comment by jmlrt** [comment]
Hi @icamys,
I'm really glad you found this Ansible role useful. Well Kibana is a different product and shouldn't be installed in the same nodes as Elasticsearch in a production architecture so ideally we should have some dedicated role ansible-kibana in addition of ansible-elasticsearch and ansible-beats existing roles. Unfortunately we don't have the time to develop that new role yet as we are only 2 peoples at elastic maintaining Ansible roles in a small part of our time currently.

**Comment by icamys** [comment]
@jmlrt The observation about that Kibana shouldn't be installed on the same hosts as Elasticsearch,  could you please share some more details about it or give some url where this info can be found?

**Comment by jmlrt** [comment]
> While Kibana isn’t terribly resource intensive, we still recommend running Kibana separate from your Elasticsearch data or master nodes. To distribute Kibana traffic across the nodes in your Elasticsearch cluster, you can run Kibana and an Elasticsearch client node on the same machine. For more information, see [Load Balancing Across Multiple Elasticsearch Nodes](https://www.elastic.co/guide/en/kibana/7.2/production.html#load-balancing).

https://www.elastic.co/guide/en/kibana/7.2/production.html
