### ISSUE TITLE
LimitMEMLOCK=infinity no longer implemented

### ISSUE THREAD

**Issue by broferek** [elastic/ansible-elasticsearch#585]
<!

**Elasticsearch version** : 7.1.1

**Role version**:  7.1.1

**JVM version** (`java -version`): openJDK 1.8.0

**OS version** (`uname -a` if on a Unix-like system): Centos 7

**Description of the problem including expected versus actual behaviour**: 
With 6.6 role, the systemd service template is deployed by the role and overload the setting LimitMEMLOCK=infinity. This behaviour disappeared with the 7.1.1 role and the service can't start because it can not lock the memory.

Is there another preconisation to work around this problem? Or shall the template be deployed again by the role?

Regards

**Comment by broferek** [comment]
@jmlrt I can propose a PR with a fix for this with a lineinfile task to add it if memory lock is enabled and the server uses systemD but if you can give me the reason why it has been removed, maybe it can help me finding another workaround

**Comment by jmlrt** [comment]
Hello @broferek,

Thanks for this issue.

With OS using systemd, this should be configured in `/etc/systemd/system/elasticsearch.service.d/override.conf` (see [elasticsearch.j2#L51-L59](https://github.com/elastic/ansible-elasticsearch/blob/master/templates/elasticsearch.j2#L51-L59) and [Systemd configuration](https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-system-settings.html#systemd)).

However, this should be added only in addition of [bootstrap.memory_lock](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#bootstrap-memory_lock) and only when user can't disable swap (see https://github.com/elastic/elasticsearch/issues/22734).

It would be great if you want to create a PR for that. 

`LimitMEMLOCK=infinity` should be set only when `m_lock_enabled` fact is set in [elasticsearch-parameters.yml#L33-L34](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-parameters.yml#L33-L34).

**Comment by broferek** [comment]
I'm on vacation but will propose a PR according to your advices for that when I'm back.

**Comment by jmlrt** [comment]
Thanks, I wish you good holidays then 😃
