### ISSUE TITLE
Add the ability to generate xpack security certificates and distribute them

### ISSUE THREAD

**Issue by manuasir** [elastic/ansible-elasticsearch#586]
Hello folks,

I'm trying to implement `XPACK security` with Ansible over my Elastic stack (Elasticsearch cluster + Kibana + Filebeat) `v7.1.1`. According to the documentation, it's needed to generate a `instances.yml` including the `name` and `IP` of each node. Once the certificates are generated, they have to be distributed over the instances. After all, the configuration files should be completed with the CA and certs paths (this is not the tricky stuff). 
How could be this approached the first part (generation and distribution) with Ansible? Any ideas will be appreciated.

Cheers

**Comment by Crazybus** [comment]
Did you already maybe see https://github.com/elastic/ansible-elasticsearch/pull/479? This is a PR where support is being added to be able to run a cluster with full security enabled. With the current release it is only possible to run security with only basic authentication enabled (no certificates). I'd keep an eye on this PR as once its working there will also be some documentation added for how to set it up.
