### ISSUE TITLE
Add Elasticsearch repository key very slow

### ISSUE THREAD

**Issue by isoboroff** [elastic/ansible-elasticsearch#589]
<!

**Describe the feature**:

This is running a basic playbook.  The task 'Debian - Add Elasticsearch repository key' takes a minute or two to complete.  I can't tell why... fetching the GPG key isn't the delay, there's no pause doing that with curl.  Is this a bug in the apt-key ansible module?

**Elasticsearch version**

**Role version**:  (If using master please specify github sha)

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
Ubuntu 18.04

**Description of the problem including expected versus actual behaviour**:

**Playbook**:
Please specify the full playbook used to reproduce this issue.
- name: ElasticSearch retrieval cluster configuration
  hosts: ...
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: "7.2.0"
    es_heap_size: "8g"
    es_data_dirs:
      - "/local/elastic/data"
    es_log_dir: "/local/elastic/logs"
    es_config:
      network.host: "_global_"
      cluster.name: "rg-cluster"
      discovery.seed_hosts: "..."
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: ...
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: "7.2.0"
    es_heap_size: "8g"
    es_data_dirs:
      - "/local/elastic/data"
    es_log_dir: "/local/elastic/logs"
    es_api_host: "_global_"
    es_config:
      cluster.name: "rg-cluster"
      network.host: "_global_"
      discovery.seed_hosts: "..."
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment
**Provide logs from Ansible**:
$ ansible --version
ansible 2.8.2
  config file = None
  configured module search path = ['/Users/soboroff/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/soboroff/elastic/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/soboroff/elastic/venv/bin/ansible
  python version = 3.7.3 (default, Mar 30 2019, 03:37:43) [Clang 10.0.0 (clang-1000.11.45.5)]

**ES Logs if relevant**:

**Comment by jmlrt** [comment]
Hi @isoboroff,
Thank you for your report however we couldn't reproduce your issue locally.
Task "Debian - Add Elasticsearch repository key" is taking ~2s in every of our tests.

Also [apt_key_module](https://docs.ansible.com/ansible/latest/modules/apt_key_module.html) issue should be reported directly to [ansible bug tracking](https://github.com/ansible/ansible/issues) as we don't maintain this module but only use it in ansible-elasticsearch role.
