### ISSUE TITLE
Better Support for Plugin removal

### ISSUE THREAD

**Issue by gingerwizard** [elastic/ansible-elasticsearch#59]
Ansible role currently only adds plugins and does not support plugin removal.

First improvement will:

1. Remove and re-install all plugins if ES is upgraded - as required in 2.x
2. Provide aa flag to re-install all plugins
3. Remove all plugins if none are specified and some are installed
4. Install plugins listed and not installed - currently supported

More tricky, and separate ticket:

1. Removal of plugins that are installed but not listed in the playbook.  Requires additional logic as ES lists names differently than install names

**Comment by barryib** [comment]
I think some of requested improvements are already supported:

1. ~~Remove and re-install all plugins if ES is upgraded - as required in 2.x~~ [elasticsearch-plugins.yml#L5](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-plugins.yml#L5)
2. ~~Provide aa flag to re-install all plugins~~ [`es_plugins_reinstall`](https://github.com/elastic/ansible-elasticsearch/blob/master/defaults/main.yml#L8)
3. ~~Install plugins listed and not installed - currently supported~~
4. Remove all plugins if none are specified and some are installed

**Comment by barryib** [comment]
Would it be nice to use the [elasticsearch_plugin for ansible](http://docs.ansible.com/ansible/elasticsearch_plugin_module.html) to manage plugins?

**Comment by electrical** [comment]
Would be nice but we still support ansible pre 2.0 :-)

**Comment by gingerwizard** [comment]
1-4 are not currently supported. There is no (2) and upgrades donot occur of plugins on upgrade of ES.
3 is supported.

**Comment by gingerwizard** [comment]
Is this module maintained for the latest version of ES? Does it work for 1.7 and 2.0 as plugin management commands will/have changed.

**Comment by barryib** [comment]
@gingerwizard I'm missing something. Can you please correcte me if I'm wrong on these following improvements:

- _Improvement 1:_ I think that when ES is re-installed, `es_plugins_reinstall`is set to `true`. This will remove listed plugins in `es_plugins`. And those will be installed during plugins installation.
- _Improvement 2:_ When the `es_plugins_reinstall` is set to `true`, this will lead to same case as (1).
- _Improvement 4:_ For me, only this is not currently supported.

@electrical @gingerwizard Right the ansible module doesn't work on ES 1.x and ES 2.x right now. Its only works on ES 1.x. This is due to the ES verbs changes. But, I think it's a minor bug and can be [fixed easily](https://github.com/ansible/ansible-modules-extras/issues/1214). We should consider using this module in a near future. Our contributions on that module are welcomed :)

**Comment by gingerwizard** [comment]
So currently it doesn't behave as it should. I'm about to make a pull request that will change this behaviour slightly. The main issue is that when you upgrade ES you need to remove ALL plugins and reinstall them.  If any of the plugins change between the listed version and the installed version, we will also have to remove all of them and re-install them - again the plugins require this e.g. shield.

This behaviour, due to class loader checks, may change in the future and we are discussing with the ES dev team.  

Happy to use the module for installation of the plugin, but this ticket deals with the above required behaviour.  I will add this either tomorrow or late today.

**Comment by barryib** [comment]
Ok, waiting for your PR for more informations.

For information, there are PR I made for the ansible's elasticsearch_plugin module to:
- [Get it works for ES 1.x and ES 2.x](https://github.com/ansible/ansible-modules-extras/pull/1570)
- [Use proxy for plugin installation](https://github.com/ansible/ansible-modules-extras/pull/1572)

**Comment by gingerwizard** [comment]
@barryib pull request [82](https://github.com/elastic/ansible-elasticsearch/pull/82) improves this i think.  We now remove all plugins and re-install them if the user changes elasticsearch version - as required.  If the user changes the defined list nothing happens however - they must use es_plugins_reinstall: true.  The next pull request i make (hopefully tomorrow) will diff the lists and remove those not required.  Closing this for now in favour of https://github.com/elastic/ansible-elasticsearch/issues/84
