### ISSUE TITLE
Fatal on Check if old users file exists

### ISSUE THREAD

**Issue by kenorb** [elastic/ansible-elasticsearch#604]
**Elasticsearch version** 7.1.0

**Role version**:  7.1.1

**JVM version** (`java -version`): 1.8.0_222

**OS version** (`uname -a` if on a Unix-like system): 4.15.0-1040-azure #44-Ubuntu

**Description of the problem including expected versus actual behaviour**:

I've got the following fatal error:

```
...
TASK [elastic.elasticsearch : Check if old users file exists] ************************************************
task path: ~/.ansible/roles/elastic.elasticsearch/tasks/xpack/security/...
fatal: [stage2-elk.uksouth.cloudapp.azure.com]: FAILED! => {"changed": false, "msg": "Permission denied"}
```

**Playbook**:

Playbook:

```
- hosts: master
  roles:
    - elastic.elasticsearch
```

Config:

```
es_install_xpack: true
es_version: 7.1.0
es_config:
  action.destructive_requires_name: true
  cluster.name: elk
  network.bind_host: 0
  network.host: _site_
```

As far as I can see, task is checking for this folder: `{{ es_conf_dir }}/x-pack/users`, however it doesn't exist on master under `/etc/elasticsearch`.

**Comment by jmlrt** [comment]
Hi @kenorb,
Thank you for submitting this issue.
This task exists only for legacy compatibility to allow migration from some old users files.
However it should not fail if this directory is missing.

We'lll investigate to see if these compatibility tasks are still needed and remove them if we can.
If we still need them, we'll fix the ansible task to not fail when the directory is missing.

**Comment by jmlrt** [comment]
I didn't pay attention to `es_install_xpack: true` in your config but this ansible variable is used only internally inside the role and should be set to true only for Elasticsearch < 6.3 (see [compatibility-variables.yml#L22-L34](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/compatibility-variables.yml#L22-L34)).

This is why your deployment is running [elasticsearch-xpack-install.yml](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/xpack/elasticsearch-xpack-install.yml) which is included [only when `es_install_xpack: true`](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/xpack/elasticsearch-xpack.yml#L6-L8).

As Elasticsearch < 6.3 is no more supported, we'll certainly be able to remove this part of code in https://github.com/elastic/ansible-elasticsearch/issues/607.

In the mean time can you try again you deployment after removing `es_install_xpack: true` from your config?

**Comment by jmlrt** [comment]
I'm closing the issue, don't hesitate to reopen it if you have any question.
