### ISSUE TITLE
Our es_xpack_features variable is broken as it doesn't allow us to select X-Pack features to install anymore

### ISSUE THREAD

**Issue by jmlrt** [elastic/ansible-elasticsearch#608]
OK after digging for a few hours into Elasticsearch documentation and Ansible code:

Since Elasticsearch 6.3, by default, when you install Elasticsearch, X-Pack is installed (except if you install oss package) (source: https://www.elastic.co/guide/en/elasticsearch/reference/7.1/setup-xpack.html).

There is no way to uninstall X-Pack (source: https://discuss.elastic.co/t/how-can-i-disable-or-uninstall-x-pack-in-elk-stack-version-6-7/175339/2)

If you are not using oss package, the only control that you have on X-Pack features is by enabling or disabling certain specific features in Elasticsearch configuration with `xpack.<FEATURE>.enabled: false`

This setting is available for `monitoring` or `security` for example.

Our `es_xpack_features` variable is broken as it doesn't allow us to select X-Pack features to install anymore and we'll need to address that in another ticket.

Regarding your use case, if you already have Elasticsearch > 6.2 with non oss package, you should already have X-Pack enabled and the upgrade shouldn't have any impact as long as you keep `es_enable_xpack=true`.

Regarding `readonlyrest` plugin interfering with X-Pack, I suspect that disabling security feature with `xpack.security.enabled: false` should be enough.

If you currently have Elasticsearch <= 6.2, then 6.3 was already a breaking change with the integration of X-Pack inside Elasticsearch non oss package and I'm afraid you won't be able to upgrade without any downtime with this ansible role.

_Originally posted by @jmlrt in https://github.com/elastic/ansible-elasticsearch/issues/602#issuecomment-528122756_

**Comment by jmlrt** [comment]
👍

**Comment by rpetre** [comment]
I am using es_xpack_features locally to enable monitoring and disable security and ml (although recently I'm toying with adding security as well). I believe it's still useful to permit declaring somehow  `xpack.FEATURE.enabled: false` individually, for cases where you don't necessarily want all of them.

All I had to do was a few extra tests in elasticsearch.yml.j2 (but I haven't tested it except on my setup), I can open a PR if you'd like.

Alternately, if this feature is going away, at least permit adding raw lines to elasticsearch.yml so i wouldn't have to maintain a local fork :)

**Comment by jmlrt** [comment]
All I had to do was a few extra tests in elasticsearch.yml.j2 (but I haven't tested it except on my setup), I can open a PR if you'd like.

Hi @rpetre, we already have #653 in progress to address this and expect to resume the work on it in a few weeks.

> Alternately, if this feature is going away, at least permit adding raw lines to elasticsearch.yml so i wouldn't have to maintain a local fork :)

You can already add raw lines in `elasticsearch.yaml` using `es_config` variable. Can you detail what is missing here?

**Comment by rpetre** [comment]
Hello,

Sorry, it's been quite a while since I needed this :) It's very likely I didn't realize `es_config` could be used to inject config bits :)

At the time I wanted to disable just the ML part of xpack and noticed this issue discussing the future of `es_xpack_features` so i just wanted to make my use case known. I'm personally toying now with the idea of enabling ML as well so I might not need for too long anyway.
