### ISSUE TITLE
Support plugin management for ES 1.x

### ISSUE THREAD

**Issue by barryib** [elastic/ansible-elasticsearch#61]
Between ES 1.x and 2.x plugins management verbs changed.
* **ES 1.x**: `bin/plugin --install [plugin_name]`
* **ES 2.x**: `bin/plugin install [plugin_name]`

We should catch this change during the plugin installation and removal. At least, as long we support ES 1.x

**Comment by electrical** [comment]
Hi,

the `install` command works on both ES 1.x and 2.x its just horribly documented :-(

**Comment by barryib** [comment]
Oh thats good. I didn't know that.
Thanks. I'm closing this issue.
