### ISSUE TITLE
Exception in thread "main" java.nio.file.FileSystemException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp /usr/share/elasticsearch/config/elasticsearch.keystore: Device or resource busy

### ISSUE THREAD

**Issue by daniel790426** [elastic/ansible-elasticsearch#632]
hello
I want to build elasticsearch (7.3.0) and run in kubernetes,but i get error

Error:

Exception in thread "main" java.nio.file.FileSystemException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp /usr/share/elasticsearch/config/elasticsearch.keystore: Device or resource busy

I want to build elasticsearch (7.3.0) and run in kubernetes,but i get error

Error:

Exception in thread "main" java.nio.file.FileSystemException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp /usr/share/elasticsearch/config/elasticsearch.keystore: Device or resource busy

my step

1.create secret
**kubectl create secret generic elasticsearch-keystore --from-file=./elasticsearch.keystore**
2.set secretmount  (values.yaml)
     **secretMounts:
    -name: elastic-certificates
      secretName: elastic-certificates
      path: /usr/share/elasticsearch/config/certs
      secretName: elasticsearch-keystore
      path: /usr/share/elasticsearch/config/elasticsearch.keystore
      subPath: elasticsearch.keystore**

i tried to chmod g+s  elasticsearch.keystore , but doesn't work Is there something I am missing?thanks

**Comment by jmlrt** [comment]
Hi @daniel790426, I don't understand how you are planning to run elasticsearch on kubernetes with Ansible, however if you want to run elasticsearch in kubernetes. I recommend you to use [Elastic Helm Chart](https://github.com/elastic/helm-charts).

**Comment by daniel790426** [comment]
@jmlrt hi
My Production cluster install elasticsearch in kubernetes,and version is 6.5
Because i want to xpack function,so i have to bulid 7.0.0 up version
So i choose elasticsearch version 7.3.0 and install by helm install elasticsearch 7.3.0
When i don't add elasticsearch-keystore, it can be work.
But when i add,it will happend this error

**Comment by jmlrt** [comment]
@daniel790426,
I'm sorry but I still don't understand how this is related with this Ansible role.
If you have an issue with Helm Charts, please open it here: https://github.com/elastic/helm-charts/issues/new/choose and we'll try to answer it.

**Comment by jmlrt** [comment]
I'm closing the issue, don't hesitate to reopen it if you have any question.
