### ISSUE TITLE
Validate configuration

### ISSUE THREAD

**Issue by babadofar** [elastic/ansible-elasticsearch#64]
Using a map for configuring elasticsearch.yml is super flexible and nice, but it makes it very easy to miscreate configurations that will not start. It would be very nice if there was some sort of validation that checks syntax.

**Comment by gingerwizard** [comment]
@babadofar whilst i like the idea of this feature, any validation will require us knowledge of the settings. This will somewhat negate the purpose of the map.

However, if it is just syntax checks you are after that maybe possible?
We might be able to convert it to configuration and ask the ES binary if its valid, stopping earlier if not.  Would this satisfy your requirement?

**Comment by babadofar** [comment]
When using the template function of ansible, there is an option to make it validate the file that results from running the template using a command that you can specify. I have used this previously  to validate Logstash configurations, using the Logstash --configtest parameter. I'm not sure whether there is such a parameter to elasticsearch. So perhaps this issue is better moved there?

**Comment by gingerwizard** [comment]
@babadofar yes this is indeed possible in ES.  I'll investigate and see if we can do this with ES.

**Comment by gingerwizard** [comment]
@babadofar So configuration validation is coming in ES 5.0.  I will raise a ticket asking for a -t flag and reference

**Comment by gingerwizard** [comment]
Discussing with ES dev the best way to do this will be to start a standalone node with the configuration.  I'm looking at ways to achieve this prior to running the playbook as a pre-check.

**Comment by strootman** [comment]
Docker may be a nice solution for this.

```
$ docker run -v [mount generated config file to correct location] elasticsearch:5.0 elasticsearch -t ...
```
Assuming that running `elasticsearch` with the `-t` option returns with correct exit codes.

**Comment by gingerwizard** [comment]
@strootman i was thinking we would need to download the version the user is using - as config is subject to change. Effectively local-action commands.   This way we can warn if settings are deprecated etc.  

This is likely to be a completely separate task with an optional switch.  Happy for someone to take this on as i'll be focusing on 5.0 support after the xpack pull request.

**Comment by ktham** [comment]
@gingerwizard Was Configuration validation ever released?

**Comment by xrkolovos** [comment]
Any news on this one?

**Comment by jruariveiro** [comment]
Any news under the sun?
