### ISSUE TITLE
`always` tag conflicts with other roles when using tags to converge servers

### ISSUE THREAD

**Issue by grzegorznowak** [elastic/ansible-elasticsearch#651]
Hey guys, Is there a reason to use `always` tag here ?

https://github.com/elastic/ansible-elasticsearch/blob/50321df03da4666b7c76e9d72fb7436a6f3d8bf9/tasks/main.yml#L22

We're rebuilding specific subsets of clusters with tag-targetting and this prevents this use case from happening with error like:
` The error was: 'ansible_os_family' is undefined`

unless we keep removing/re-adding ES role from playbooks constantly.

**Comment by jmlrt** [comment]
Hi @grzegorznowak, we already discussed it in https://github.com/elastic/ansible-elasticsearch/pull/594. `always` tag is mandatory for check-mode and for runnning only part of the role with the other tags.

**Comment by grzegorznowak** [comment]
Hey guys,

sorry let me continue this thread as the issue is constantly biting us unfortunately, and the `skip-tag` solution is no go, given our main Molecule playbook consists of 10 servers or so, some of which do use `always` tag for specific business' purposes. 

Instead I wonder was there a reason not to use the already existing flag to have the tasks execute in `check_mode` 

(taken from the official Ansible docs, under https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html)

```
Force a task to run in normal mode and make changes to the system, even when the playbook is called with --check. This is called check_mode: no.
```

so that's one part of the solution and the other bit is I can tell you're having specialized tags to target each possible subsystem this role can handle `java`, `install`, `config` etc.

We're not using the role with any of those tags but from what I can tell, instead of hijacking the `always` tag, we could just explicitly list those alongside the related `include` directives, that is:

Replace all:

```
tags:
  - always
```

With:

```
tags:
  - java
  - install
  - etc
```


Let me know if you did try that approach on your end and issues you might have faced with it. 
I can confirm both `check_mode` and regular converge works just fine if used with those mods. Albeit I haven't ran it through tag-targetted build as our model doesn't need it in any form. But it should be just fine from the look of things.

**Comment by grzegorznowak** [comment]
actually the tag-targetting would require a tweak in a form of probably duplicating `includes`, now as I think about it. Hopefully CI pipelines can pick up all the variations to be sure eventually
