### ISSUE TITLE
Unexpected Exception, this is probably a bug: invalid syntax (connectionpool.py, line 100)

### ISSUE THREAD

**Issue by henrypoter** [elastic/ansible-elasticsearch#655]
When I install the  elastic.elasticsearch on centos 6， the following exception occured

[root@dev ~]#  ansible-galaxy install elastic.elasticsearch,7.5.1 --ignore-errors
 [WARNING]: - elastic.elasticsearch was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): Failed to validate the SSL certificate for
galaxy.ansible.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the
python executable used (/usr/bin/python2.6) is version: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]) or you can install the `urllib3`, `pyOpenSSL`,
`ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is
unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The
exception msg was: [Errno 1] _ssl.c:492: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure.

After  pip install urllib3

[root@dev ~]# ansible-galaxy install elastic.elasticsearch,7.5.1 
ERROR! Unexpected Exception, this is probably a bug: invalid syntax (connectionpool.py, line 100)
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 97, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/lib/python2.6/site-packages/ansible/cli/galaxy.py", line 38, in <module>
    from ansible.galaxy.api import GalaxyAPI
  File "/usr/lib/python2.6/site-packages/ansible/galaxy/api.py", line 34, in <module>
    from ansible.module_utils.urls import open_url
  File "/usr/lib/python2.6/site-packages/ansible/module_utils/urls.py", line 95, in <module>
    from urllib3.contrib.pyopenssl import PyOpenSSLContext
  File "/usr/lib/python2.6/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 100
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax
[root@dev ~]# 

[root@dev ~]# ansible --version
ansible 2.6.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
[root@dev ~]# 

[root@dev ~]# uname -a
Linux dev.gzhc.local 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@dev ~]#

**Comment by jmlrt** [comment]
Hi @henrypoter,
Your issue is related to `ansible-galaxy` commandline, not `ansible-elasticsearch`role.
I suggest you to open an issue to https://github.com/ansible/ansible/issues.

**Comment by jmlrt** [comment]
I'm closing the issue, don't hesitate to reopen it if you have any question.
