### ISSUE TITLE
Repo internal links in ansible galaxy are broken

### ISSUE THREAD

**Issue by jakommo** [elastic/ansible-elasticsearch#656]
The internal Links of the ReadMe in ansible galaxy are broken and result in a 404.

I.e. on top of the ReadMe the `... follow upgrade procedure` points to https://galaxy.ansible.com/docs/multi-instance.md#upgrade-procedure and further down in the `X-Pack Security SSL/TLS` section the link for `... follow the SSL/TLS setup procedure` points to https://galaxy.ansible.com/docs/ssl-tls-setup.md. 
I tried adding the `/elastic/elasticsearch/` to the urls, but that also does not work.
Not sure how ansible galaxy generates those links and if this is something we can fix. 

In the Readme on github both links work fine.

**Comment by jmlrt** [comment]
Hi @jakommo,
Ansible Galaxy is retrieving the raw [Readme.md from the repo](https://github.com/elastic/ansible-elasticsearch/blob/master/README.md) without doing any links translation.
I think we should replace every relative links by absolute links in the README.
Could you create a PR for that?
