### ISSUE TITLE
Enhancement: provide tasks to perform cluster operations

### ISSUE THREAD

**Issue by faxm0dem** [elastic/ansible-elasticsearch#658]
It would be awesome to provide tasks that require some orchestration, like rolling cluster upgrades,
adding nodes, etc.

**Comment by jmlrt** [comment]
Hi @faxm0dem, thank you for submitting this request.

I understand that managing cluster operations via Ansible has a lot of benefits.

However this is not the goal of this role. This role focus on automating Elasticsearch installation and configuration on single nodes. While you can deploy this role on more than one node with the same config to create a cluster, this role won't manage the cluster orchestration itself.

I would recommend you to create a set of playbooks leveraging this ansible role for the different cluster orchestration tasks which you have.

**Comment by jmlrt** [comment]
I'm closing the issue, don't hesitate to reopen it if you have any other question.
