### ISSUE TITLE
ansible-galaxy - elastic.elasticsearch was NOT installed successfully: Unable to compare role versions 

### ISSUE THREAD

**Issue by cstegm** [elastic/ansible-elasticsearch#663]
- downloading role 'elasticsearch', owned by elastic
 [WARNING]: - elastic.elasticsearch was NOT installed successfully: Unable to compare role versions (0.1.0, 0.1.2, 6.2.2, 6.3.0, 6.3.0.1, 6.4.0, 6.5.1, 7.4.0, 7.4.1, 7.5.0, 6.3.0-1, 6.3.1, 0.1.1,
6.2.4-1, 7.5.1, 7.1.1, 6.2.4, 5.5.1, 6.2.3, 6.6.0, 6.1.3) to determine the most recent version due to incompatible version formats. Please contact the role author to resolve versioning conflicts,
or specify an explicit role version to install.

**Comment by jmlrt** [comment]
Hi @cstegm, 
Elasticsearch role doesn't support "latest" version. You always need to specify the version of the role you want to download as mentionned in the [README.md](https://github.com/elastic/ansible-elasticsearch#usage):

```
ansible-galaxy install elastic.elasticsearch,7.5.1
```

**Comment by cstegm** [comment]
OK. Thx. I think we can close issue.
