### ISSUE TITLE
es_validate_certs: true

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [elastic/ansible-elasticsearch#679]
**Describe the feature**:

**Elasticsearch version**: 7.5.1

**Role version**:  7.5.1

**JVM version** (`java -version`): 13.0.1

**OS version** (`uname -a` if on a Unix-like system): Red Hat Enterprise Linux Server release 7.7 (Maipo)

**Description of the problem including expected versus actual behaviour**:
https://discuss.elastic.co/t/ansible-elasticsearch-custom-ca-certificate-validation-failures/216843

Elasticsearch with ssl only works if es_validate_certs : false. The root cause of this problem is that the role installs all certificates, i.e. as well the CA cert in the node's certs directory (/etc/elasticsearch/certs). Tasks which use the Ansible uri role will therefor fail since uri only supports CA certs in standard certs location like /etc/pki/certs on Redhat/Centos. Since uri does not accept a custom cacert path like curl does, the elasticsearch role should either install CA certs properly or use curl instead with the appropriate cacerts path set.

**Playbook**:
Playbook variables:
es_enable_http_ssl: true
es_enable_transport_ssl: true
es_ssl_certificate_authority: files/ssl/CA/elk-ca-cert.pem
es_ssl_key: "files/ssl/certs/{{inventory_hostname}}-key.pem"
es_ssl_certificate: "files/ssl/certs/{{inventory_hostname}}-cert.pem"
es_ssl_certificate_path: /etc/elasticsearch/certs
es_validate_certs: false

Elasticsearch role:
ansible-elasticsearch/tasks/elasticsearch-ssl.yml
- name: Upload SSL Certificate Authority
  become: yes
  copy:
    src: "{{ es_ssl_certificate_authority }}"
    dest: "{{ es_ssl_certificate_path }}/{{ es_ssl_certificate_authority | basename }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "640"
  #Restart if this changes
  notify: restart elasticsearch
  when: (es_ssl_certificate_authority is defined) and (es_ssl_certificate_authority|length > 0)

**Provide logs from Ansible**:

**ES Logs if relevant**:

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
I'm sorry that we never found time to investigate, @bndabbs, do you think you could find time to take a look?

**Comment by Bernhard-Fluehmann** [comment]
@bndabbs In the meantime I have solved this by properly installing CA Certs to the Elasticsearch Linux Hosts with another Ansible role. The easiest solution would be to just to mention this in the README and leave the implementation as is.
