### ISSUE TITLE
Keystore Configuration

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [elastic/ansible-elasticsearch#684]
**Add suppot for elasticsearch.keystore entries**:
Some Elasticsearch features like watcher outputs or AD integration need entries stored in the elasticsearch keystore. As far as I can see this is currently not supported. Although the settings can be done outside of the playbook with a separate task it would still be easier to have this supported by the playbook.

**Elasticsearch version** 7.6.1

**Comment by Bernhard-Fluehmann** [comment]
In the meantime I have implemented the feature and created a pull request https://github.com/elastic/ansible-elasticsearch/pull/685
Comments and opinions are welcome.

**Comment by missnebun** [comment]
Exactly this feature I need it today ... I use real with active directory and I need to set the password.

**Comment by jmlrt** [comment]
this is still valid

**Comment by Bernhard-Fluehmann** [comment]
#757
