### ISSUE TITLE
Incorrect parameter check leads to missing config parts and confusion 

### ISSUE THREAD

**Issue by jrunu** [elastic/ansible-elasticsearch#688]
**Role version**:  7.6.2 

With 7.1.1 a new behaviour with regard to `es_xpack_features` was introduced, making checks like `"security" in es_xpack_features` non functional.

Such a check is used to in tasks/elasticsearch-parameters.yml line 13 to ensure that when the 
security features are enabled also a the http auth user for ansible is supplied. 

The fact that `es_basic_auth_username` and `es_basic_user_password` are needed for any security 
related config to be written (see templates/elasticsearch.yml.j2) is not reflected in the documentation.  Furthermore it is stated that these variables are soley needed for the configuration
of the native realm. 

Configuring security features but ommiting these variables, because the native realm is not used, leads to a silent fail of the parameter check mentioned above and subsequently all security 
parameters are ommited in the actual configuration file on the node.

**Comment by jmlrt** [comment]
Hi @jrunu, we already have #608 to issue related to `es_xpack_features` change and expect to resume #653 in a few weeks.

In addition, it seems that we need to improve the way we document authentication settings, this will be tracked in #662.

I'm closing this issue as duplicate, feel free to follow the mentionned issues.
