### ISSUE TITLE
Ubuntu 14.04 - elastic service cannot be stopped or restarted

### ISSUE THREAD

**Issue by einchance** [elastic/ansible-elasticsearch#69]
On Ubuntu 14.04 you cannot restart (or stop) the elastic service with this command:

service <es_instance_name_elasticsearch> restart

Currently you have to restart the service, you have to kill the process and then use:

service <es_instance_name_elasticsearch> start

**Comment by jakommo** [comment]
@einchance Are you using `es_start_service: true` in your playbook?

I did run some tests and this happend to me sometimes (strangely not all the times), but only if the process was started by ansible using `es_start_service: true`.
I was able to track this down to the `PID` file not being created and thus the init script didn't know which process to stop. After killing the process manually, running `service elasticsearch start/stop` several times, did work as expected. 

I thing it could be related to this https://github.com/elastic/elasticsearch/pull/16718, which will be backported to `2.3`.

**Comment by einchance** [comment]
Like you, it seems to be working for me now.  I'm not currently using the es_start_service setting.  I don't recall if I had it set to true at the time I filed this.  It seems likely as I did commit es_start_service: false at one point before later removing it.  I'll try and reproduce it with that setting and let you know the results.

**Comment by jakommo** [comment]
@einchance please keep me updated. 
I did some testing with the modified init script from https://github.com/elastic/elasticsearch/pull/16718 and this seems to fix the issue for me.

**Comment by gingerwizard** [comment]
@einchance @jakommo we need to backport this into the init script as this is copied by the ansible role - we don't use the one from the package. I'm labelling this a bug and marking for next release.

**Comment by gingerwizard** [comment]
Fixed in pull request [74](https://github.com/elastic/ansible-elasticsearch/pull/74)
