### ISSUE TITLE
Unable to compare role versions

### ISSUE THREAD

**Issue by ahmadalli** [elastic/ansible-elasticsearch#694]
**Description of the problem including expected versus actual behaviour**:

running `ansible-galaxy install elastic.elasticsearch` results in error:

```
[WARNING]: - elastic.elasticsearch was NOT installed successfully: Unable to compare role versions (0.1.1, 0.1.2, 5.5.1, 6.1.3, 6.2.2, 6.2.3,
6.2.4, 6.2.4-1, 6.3.0, 6.3.0-1, 6.3.1, 6.4.0, 6.5.1, 6.6.0, 7.1.1, 7.4.0, 7.4.1, 7.5.0, 7.5.1, 7.5.2, 7.6.0, 7.6.1, 7.6.2, 7.7.0, 6.3.0.1,       
0.1.0) to determine the most recent version due to incompatible version formats. Please contact the role author to resolve versioning conflicts, 
or specify an explicit role version to install.
```

**Comment by jmlrt** [comment]
Hi @ahmadalli , 
Elasticsearch role doesn't support "latest" version. You always need to specify the version of the role you want to download as mentionned in the [README.md](https://github.com/elastic/ansible-elasticsearch#usage):

```
ansible-galaxy install elastic.elasticsearch,7.7.0
```

**Comment by ahmadalli** [comment]
ah. I tried the command from ansible galaxy and expected it to work. Thanks for the info :)
