### ISSUE TITLE
Feature: Ability to configure systemd settings from the playbook

### ISSUE THREAD

**Issue by oliviercwa** [elastic/ansible-elasticsearch#695]
The current ansible script does not set the systemd property ```autorestart``` to True. One may way to configure this property and others.

It would be great to have a way ton configure the systemd settings from the ansible playbook (either through vars or through a file that gets copied).

**Comment by jmlrt** [comment]
Hi @oliviercwa,
I don't know about this `autorestart` systemd property.
Can you provide more details about it and a link to the doc?

**Comment by oliviercwa** [comment]
Hi jmlrt,
I was not clear. I am referring to the Systemd restart=always
https://www.freedesktop.org/software/systemd/man/systemd.service.html

By default, it seems that the ansible script does not set this systemd property and the service does not restart automatically.

**Comment by jmlrt** [comment]
Thanks for the details. 
We could eventually add a variable to allow managing it in the `override.conf.j2 template:

https://github.com/elastic/ansible-elasticsearch/blob/4420df6927556b770a45255dbfd57a892382530c/templates/override.conf.j2#L1-L7

However this has already been discussed at Elasticsearch level in [this post](https://discuss.elastic.co/t/anyone-using-systemd-to-ensure-elasticsearch-is-restarted-if-it-crashes/98080) and Elasticsearch team don't recommand it as it's better to be notified of some issue and investigate when a node is stopping than risking data loss by restarting the node automatically without fixing the issue.
