### ISSUE TITLE
Remove support for `es_user` / `es_group` customization

### ISSUE THREAD

**Issue by jmlrt** [elastic/ansible-elasticsearch#719]
We discovered in https://github.com/elastic/ansible-elasticsearch/issues/687#issuecomment-688425833 that `es_user` customization is not working anymore since 7.1.1 release more than one year ago.

As this feature don't seem to be really used, is not recommended upstream by Elasticsearch and is adding complexity to the chart, we should remove it instead of trying to fix it.

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by maehue** [comment]
@jmlrt what do you mean by 'not really used'? It is required that we run elasticsearch and really all applications in the elk stack as a nonroot user/service account.
