### ISSUE TITLE
[RFE] Support for container installation

### ISSUE THREAD

**Issue by ismaelpuerto** [elastic/ansible-elasticsearch#720]
Since this PR (https://github.com/elastic/ansible-elasticsearch/pull/566) ES recommend run multiples instances with docker/podman. Looks make sense support this type on installation for multi node even single node.

**Comment by jmlrt** [comment]
Hi @ismaelpuerto,
Ansible shouldn't be required to deploy containers, you can use Docker Compose instead ([exemple here](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/docker.html)) or if you're running Kubernetes, you can use [Elastic Kubernetes operator](https://github.com/elastic/cloud-on-k8s) or [Elastic Helm charts](https://github.com/elastic/helm-charts).
