### ISSUE TITLE
Issue with "Get the installed java path" in java.yml task

### ISSUE THREAD

**Issue by zacharystokes** [elastic/ansible-elasticsearch#721]
**Describe the feature**:

**Elasticsearch version**
6.8.13
**Role version**:  (If using master please specify github sha)
7.9.1 - latest
**JVM version** (`java -version`):
1.8.0_251
**OS version** (`uname -a` if on a Unix-like system):
RHEL 7.8 3.10.0-1127.13.1.el7.x86_64 #1 SMP Fri Jun 12 14:34:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behaviour**:
When a RedHat system has multiple distros of Java installed **of the same version** then the command `shell: "update-alternatives --display java | grep '^/' | awk '{print $1}' | grep 1.8.0 | head -1"` cannot distinguish between the two distros.

For example:
```
# alternatives --config java

There are 2 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
 + 1           /usr/lib/jvm/java-1.8.0-ibm-1.8.0.6.10-1jpp.1.el7.x86_64/jre/bin/java
*  2           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.x86_64/jre/bin/java)
```
If I replace `1.8.0` with `1.8.0-openjdk` in this instance, the playbook runs to completion (if I first remove /etc/elasticsearch/elasticsearch.keystore/tmp)

**Playbook**:
elastic.yaml (java.yaml within the Role)

**Provide logs from Ansible**:

**ES Logs if relevant**:

**Comment by jmlrt** [comment]
Hi @zacharystokes, thanks for submitting this issue.

As you mentionned, this should be fixed by replacing `shell: "update-alternatives --display java | grep '^/' | awk '{print $1}' | grep 1.8.0 | head -1"` by `shell: "update-alternatives --display java | grep '^/' | awk '{print $1}' | grep 1.8.0-openjdk | head -1"`.

Do you think you could create a PR?

**Comment by zacharystokes** [comment]
Hello Julian,

I have been told I can issue a Pull Request so long as there is no CLA or
(contributor license agreement) since I submitted with my corporate email
account.

Happy to do so if that answer is no.

Best,
Z

**Comment by jmlrt** [comment]
Hi @zacharystokes,
Unfortunately submitting PR requires signing CLA.

**Comment by zacharystokes** [comment]
Okay, still probably okay just I'll have to have it reviewed before I can
submit.
Thanks,
Z
