### ISSUE TITLE
Update defaults to 2.2 instead of 2.1

### ISSUE THREAD

**Issue by westover** [elastic/ansible-elasticsearch#73]
With 2.2 out and the default to install latest maybe you should update the defaults and docs to reflect that

**Comment by jakommo** [comment]
I'm :+1: , what's your opinion here @gingerwizard ?

**Comment by gingerwizard** [comment]
I'll test and see if it passes. If so, i'll include in the next release. Thanks

**Comment by gingerwizard** [comment]
Included in https://github.com/elastic/ansible-elasticsearch/pull/87
