### ISSUE TITLE
Add support for CentOS / RHEL 8.x

### ISSUE THREAD

**Issue by jmlrt** [elastic/ansible-elasticsearch#737]
Elasticsearch supports CentOS / RHEL 8.x since Elasticsearch 7.7.0.

This Ansible role should be updated to add centos-8 supports and test-kitchen tests.

**Comment by fourstepper** [comment]
I am running this role with the base settings on CentOS 8 and, aside from idempotence, it works great.

The main issues with idempotence I am seeing right now are at these tasks:
* [instance] => elastic.elasticsearch : RedHat - Install Elasticsearch
* [instance] => elastic.elasticsearch : Remove key password
