### ISSUE TITLE
no log4j2.properties in es_conf_dir

### ISSUE THREAD

**Issue by Gurpartap** [elastic/ansible-elasticsearch#748]
> Deployment of this Ansible role on new servers will get the default log4j2.properties provided by Elasticsearch without any override.

On a fresh install, with `es_conf_dir=/opt/elasticsearch/config`, there was no `log4j2.properties` inside the es_conf_dir.

```
RUNNING HANDLER [elastic.elasticsearch : restart elasticsearch] ***********************************************
fatal: [elasticidx-node1]: FAILED! => {
  "changed": false,
  "msg": "Unable to start service elasticsearch: Job for elasticsearch.service failed because a timeout was exceeded.\nSee \"systemctl status elasticsearch.service\" and \"journalctl -xe\" for details.\n"
}
```

I had to `cp /etc/elasticsearch/log4j2.properties /opt/elasticsearch/config/` to get it moving.

7.10

**Comment by jmlrt** [comment]
Hi @Gurpartap,

Thanks for opening this issue.

Indeed, this role doesn't copy the log4j2.properties file from deb/rpm default directory (/etc/elasticsearch/log4j2.properties) when `es_config_dir` is overrided. 

That's something we could add if you're interrested to submit a PR.

**Comment by Gurpartap** [comment]
.

**Comment by Gurpartap** [comment]
Issue reported has not been fixed, afaik.
