### ISSUE TITLE
delete elasticsearch

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [elastic/ansible-elasticsearch#764]
I have implemented basic support for uninstalling elasticsearch with this role.  
Currently only on Redhat.

Please let me know if you are interested in this feature. If yes, then I will do a proper implementation and create a pull request.

Some questions I have already:

- Should uninstall be selectable via tags (e.g. uninstall in addition to install)
- Should a state variable be used instead (es_state: present|absent) and debian, redhat etc. task files updated to properly support it
- Should it be organized in own tasks files and used separately to main, like with tasks_from: uninstall.yml

Please let me know your thoughts.

And mainly if you are interested in contribution. There are other features in the pipe, like rolling-upgrade, backup / restore etc.

**Comment by jmlrt** [comment]
Hi @Bernhard-Fluehmann,
Thanks for submitting this need.

I'm not sure if this would make sense to handle Elasticsearch uninstall in this role as usually a host without Elasticsearch shouldn't have anymore the ansible-elasticsearch role.

Usually, when some Elasticsearch node is replaced by a new one, the old one is destroyed or reinstalled from scratch (OS reinstallation) and there is no need to properly uninstall Elasticsearch before.

Also IMO, when there is still a need to uninstall Elasticsearch on some host, this is a one time action that should live in it's own custom playbook without calling the ansible-elasticsearch role.

However, I'm open-minded if there is other requests for it. Do you know some Ansible roles for other software which are handling uninstall?

>There are other features in the pipe, like rolling-upgrade

We see this Ansible role as a way to automate single node deployment, and I think that orchestration for multi nodes should be handled by custom playbooks calling this role if needed with different values on each nodes for example.

Do you have some example of roles being able to handle multi nodes orchestration inside the role?
