### ISSUE TITLE
Heapsize is set to 2GB when es_heap_size is not set

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/ansible-elasticsearch#776]
Hi all,
after installing a new cluster on 7.11 with this role, I mentioned that the Bundled JDK heap size is set to 2GB.
According to the docs at https://www.elastic.co/guide/en/elasticsearch/reference/7.11/important-settings.html#heap-size-settings the heap size is set automatically, when the bundled JDK is used and we should let it like that.
As I did not set es_heap_size in my Playbook, I thought, the automatic heap size would work. But in the jvm.conf the values
```
-Xms2g
-Xmx2g
```
are given.
Imho, this should not be there, when the bundled JDK is used an no es_heap_size value is given.
OS: UIbuntu 20.04.2 LTS
Role Version: 7.10.2

Thanks and cheers,
Marcus

**Comment by jmlrt** [comment]
Hi @MarcusCaepio,
Thanks for reporting this.
Automatic heap sizing seem to be a new feature coming in 7.11 and this role hasn't been updated to handle it yet.

Meanwhile, a workaround would be to override the `jvm.options` file without specifying `-Xms` and `-Xmx` using `es_config_jvm` (see https://github.com/elastic/ansible-elasticsearch#how-to-override-configuration-files-provided-by-ansible-elasticsearch).

**Comment by jmlrt** [comment]
Related to #738

**Comment by jmlrt** [comment]
still valid
