### ISSUE TITLE
FR: Install Elasticsearch-plugins with this role

### ISSUE THREAD

**Issue by ppuschmann** [elastic/ansible-elasticsearch#794]
**Install Elasticsearch-plugins with this role**

I think it would be helpful to also provide the installation of Elasticsearch-plugins with this role.

Use-Cases: https://www.elastic.co/guide/en/elasticsearch/plugins/7.12/discovery.html
* AWS EC2 discovery
* GCP GCE discovery

**Comment by jmlrt** [comment]
Hi @ppuschmann,
Elasticsearch plugins are managed by `es_plugins` variable, example:

```
  es_plugins:
    - plugin: ingest-attachment
```

**Comment by ppuschmann** [comment]
Yes, you're completely right!
I must have missed this when I created this issue.
