### ISSUE TITLE
gpg dependencies missing

### ISSUE THREAD

**Issue by DirectorSloan** [elastic/ansible-elasticsearch#810]
**Describe the feature**:

**Elasticsearch version**
7.13.4
**Role version**:  (If using master please specify github sha)
7.13.4
**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
debian 10.10
**Description of the problem including expected versus actual behaviour**:
install fails at:

```console
TASK [elastic.elasticsearch : Debian - Add Elasticsearch repository key] *************************************************************************************
fatal: [hostname.foo.bar]: FAILED! => {"changed": false, "msg": "Failed to find required executable gpg in paths: /usr/local/sbin:/usr/local/bin:/usr/s
bin:/usr/bin:/sbin:/bin"}                                                                                                                                     
``` 
**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

**ES Logs if relevant**:

**Comment by VMelnalksnis** [comment]
Also fails for Elasticsearch version 7.14.0 on Ubuntu 20.04.
