### ISSUE TITLE
Playbook not working with rh8

### ISSUE THREAD

**Issue by ninorito** [elastic/ansible-elasticsearch#818]
Hello,

**Elasticsearch version**: 7.14

**OS version** (`uname -a` if on a Unix-like system): rh8

**Description of the problem including expected versus actual behaviour**:
The playbook fail on rh8 when he tries to install yum version-lock.
In the playbook we have : 
- name: RedHat - install yum-version-lock
  become: yes
  yum:
    name: yum-plugin-versionlock
    state: present
    update_cache: yes

And for rh8 the name of the package is different : https://access.redhat.com/solutions/98873
We should use : python3-dnf-plugin-versionlock

**Comment by hendry-lim** [comment]
Same as #797
