### ISSUE TITLE
Remove Plugins that re installed but not listed in the playbook.

### ISSUE THREAD

**Issue by gingerwizard** [elastic/ansible-elasticsearch#84]
Currently if the user does the following:
1. Installs ES with plugins
2. Changes the plugins listed - adds and removed
3. Re-runs the playbook

The plugins are not changed to those in step (2) - they are required to specify es_plugins_reinstall:true.  My current proposal is to remove all plugins and re-install them in the event of ANY delta.

@jakommo thoughts?

**Comment by jakommo** [comment]
I'm :+1: on "remove all plugins and re-install them in the event of ANY delta."

**Comment by gingerwizard** [comment]
@jakommo i have a PR ready which would correct deltas. What was our reasoning (my bad memory) for removing ALL in the event of a delta?

**Comment by gingerwizard** [comment]
https://github.com/elastic/ansible-elasticsearch/pull/269 should resolve

**Comment by gingerwizard** [comment]
https://github.com/elastic/ansible-elasticsearch/pull/269 closes
