### ISSUE TITLE
Allow specification of own user name

### ISSUE THREAD

**Issue by gingerwizard** [elastic/ansible-elasticsearch#85]
Allow the specification of a different username under which elasticsearch should be run.  Currently we only support "elasticsearch".

I propose we do not create this user if it doesn't exist i.e. we assume its existence.

**Comment by gingerwizard** [comment]
@jakommo

**Comment by jakommo** [comment]
If we always use the deb/rpm the user should exist anyways, but it could be necessary to work around #36, where the UID/GID would need to be the same if NFS is used for snapshots and idmapd isn't in place. 
If we decide to do it, we also must edit the `tmpfiles.d` files created for systemd, as they define the user for the `/var/run/...` dir.

**Comment by gingerwizard** [comment]
I dont think this is an issue.  We already allow a username and group to be specified and we now support specification of the uid and gid.
