### ISSUE TITLE
Deploy to Ansible Galaxy

### ISSUE THREAD

**Issue by strootman** [elastic/ansible-elasticsearch#89]
Are there any plans to deploy this role to [Ansible Galaxy](https://galaxy.ansible.com/)?

**Comment by gingerwizard** [comment]
@strootman We're assessing but don't currently see any reason why not.

**Comment by patcon** [comment]
bump?

**Comment by strootman** [comment]
FYI, I've forked this repo and imported to ansible galaxy;

https://galaxy.ansible.com/CyVerse-Ansible/elasticsearch/

No promises on keeping it up to date ;)

**Comment by gingerwizard** [comment]
@strootman @patcon i'll look at this tomorrow.  It hasn't been on the priority list. We need to discuss as it seems to require giving access to the Elastic repo.

**Comment by strootman** [comment]
For those who may have looked at the role and found it wasn't up to date on Ansible galaxy, it is now up to date with the current master.

**Comment by bbaassssiiee** [comment]
Elastic, you only give read-access to your repo. The advantage of Galaxy is that we can all install a stable version of the vendor supported role instead of browsing through hundreds of homegrown roles by third parties where they don't keep up to their maintenance burden, like @strootman.

**Comment by gingerwizard** [comment]
When i tried this it needed  readonly access to the whole elastic repo. Given this contains commercial code i need @elasticdog  @dliappis input prior to proceeding.  cc @kevinkluge

**Comment by pmoust** [comment]
AFAIK Github does not provide a much needed granular control over oauth scopes per repo.
`repo` and `public_repo` provide read-only and ready-write access across the whole org as @gingerwizard mentions above. Ref: https://developer.github.com/v3/oauth/#scopes

**Comment by pmoust** [comment]
On the other hand, nothing prevents us from creating a bot user as an external collaborator with access only to `elastic/ansible-elasticsearch` and provide `public_repo` to its token. 
/cc @dliappis @elasticdog

**Comment by elasticdog** [comment]
I spoke with @gingerwizard and agree that it makes sense to have a dedicated machine user to provide access for this use case.

**Comment by bbaassssiiee** [comment]
🦄

**Comment by mariussturm** [comment]
The Galaxy app only requests access to public repositories, permissions look like:
  * Access public repositories
  * Read org and team membership
  * Access user email addresses (read-only)

**Comment by jesusch** [comment]
any news on this?

**Comment by strootman** [comment]
I've been pushing a fork of this repo to ansible galaxy, and I _just_ updated it.
https://galaxy.ansible.com/CyVerse-Ansible/elasticsearch/

**Comment by bbaassssiiee** [comment]
That is not the same thing, it is a fork, but the maintainer is not Elastic. Elastic pushed to GitHub, they can also tag the release and publish on Galaxy to do a proper job.

**Comment by mariussturm** [comment]
Using this role as a dependency is also only possible when there is an official Elastic role on Galaxy. We can't use a fork for that.

**Comment by strootman** [comment]
@bbaassssiiee @mariussturm then don't use it.
I put it up there _just in case_ it fit someone's needs. It fits mine.
I also don't keep up on it, and only updated it today since I saw that @jesusch posted a `*bump*` on this thread.

I would prefer that Elastic support it officially, but they don't yet.

I'm honestly glad to see so many people actively monitoring this issue.
I hope it illustrates that there is a real customer need for having this role published to ansible galaxy.

Particularly for its use as a dependency, as @mariussturm suggests :+1:

**Comment by gingerwizard** [comment]
Added https://galaxy.ansible.com/elastic/elasticsearch/
