### ISSUE TITLE
Logrotate as part of ES Ansible setup

### ISSUE THREAD

**Issue by grindthemall** [elastic/ansible-elasticsearch#90]
I just started using the ES Ansible playbook, and noticed that there aren't any logrotate entries.

Would be nice to see a logrotate file added for ES automatically as part of the playbook as I can't seem to find any reference to one.

**Comment by UnderGreen** [comment]
Hello. Role should install only elastic, plugins. It can configure elastic, but it should't configure 3rd party software, like logrotate. You must use logrotate role with config for elastic.

**Comment by gingerwizard** [comment]
@grindthemall i agree with @UnderGreen this really is beyond the responsibility of this role.
