### ISSUE TITLE
Unable to set java version

### ISSUE THREAD

**Issue by internatt** [elastic/ansible-elasticsearch#99]
I've been testing the role with a few plugins that require java 8 (openjdk-8-jre-headless). Attempting to set the `java:` variable directly in the playbook, or in a separate vars file does not override the default. As a workaround, I can set it using the --extra-vars flag on runtime.

The use of `include_vars:` in `tasks/main.yml` is the culprit. According to [https://github.com/ansible/ansible/issues/11807](url) , this is 'expected behaviour'.

**Comment by marji** [comment]
I have created [PR112](https://github.com/elastic/ansible-elasticsearch/pull/112) which enables to specify which java to install (by passing the java package name to the role).

Example: 
```
roles:
  - { role: elasticsearch, es_java: "openjdk-8-jre-headless", es_instance_name: "node1" }    
```
The role (current master as of June 5, 2016) fails on ubuntu 16.04 as it has hardcoded java package "openjdk-7-jre-headless" which is not present in ubuntu 16.04 repos.

**Comment by gingerwizard** [comment]
@internatt  i believe we merged in a fix for this. Thanks for the resolution @marji
